### ISSUE TITLE
Bad file descriptor on windows

### ISSUE THREAD

**Issue by Globik** [libuv/libuv#1062]
Why uv_pipe_open(loop, 3) always gives error of bad file descriptor on a windows machine?
is there any adecvate examples for windows developing ? Not just for linux.
I am looking in to the test directory and see only samples under linux.

**Comment by saghul** [comment]
Where does that fd come from?  On Windows we https://msdn.microsoft.com/en-us/library/ks2530z6.aspx internally to get the associated file handle.

**Comment by Globik** [comment]
Fd coming from command line argument to the child program where int fd = 3.

**Comment by Globik** [comment]
Is there an equivalent test for windows platform like this in a file
https://github.com/libuv/libuv/blob/b12624c13693c4d29ca84b3556eadc9e9c0936a4/test/test-close-fd.c
?

**Comment by saghul** [comment]
See this: https://github.com/libuv/libuv/blob/v1.x/test/test-pipe-getsockname.c#L208

The key difference is that the fd you are passing was opened in another process, right?  I may be wrong, but IIRC Windows keeps a fd mapping per process, so that fd  3 has no meaning in the one you're trying to use uv_pipe_open on.

**Comment by moteus** [comment]
In fact each runtime has its own table of fd->handle. And if you use e.g. msvcrt.dll each dynmic module will have its own table.

**Comment by saghul** [comment]
@Globik can we close this now?

**Comment by Globik** [comment]
Yes.
