### ISSUE TITLE
TCP CLIENT LOOP MUST BE THE SERVER LOOP？

### ISSUE THREAD

**Issue by lonerwolf** [libuv/libuv#107]
uv_accept: Assertion `server->loop == client->loop' failed.
i use two loop,server fd in one,and client init with another.it is wrong?

**Comment by saghul** [comment]
Yes, that's wrong. The listen callback runs in the loop thread, and none of
the APIs are thread safe (unless stated otherwise), so you can't accept a
handle which runs in another loop.

**Comment by lonerwolf** [comment]
@saghul for example
tcp_server(loop1).connect_cb{
          uv_accept(tcp_server(loop1),tcp_client(loop2);
}
i find uv_accept: Assertion `server->loop == client->loop' failed.but i see in code,the uv_accept only set server->accepted_fd to the client.io_watcher.fd, no other things.

**Comment by lonerwolf** [comment]
@saghul i think i know what you mean now.
uv_accept(tcp_server(loop1),tcp_client(loop2);
tcp_client.async_readXXXXX this is in loop1 thread,but add event in loop2.i should post thread SEM to the loop2 thread,and do  tcp_client.async_readXXXXX in the loop2 thread.
this is right?

**Comment by saghul** [comment]
I don't know what code you're dealing with :-S The rule is simple, the
accepted connection must run on the same loop, as of today.

You could accept connections on one loop and use an IPC pipe and uv_write2
to send it to another loop. (This doesn't work with loops running in
different threads on Windows at the moment though)

**Comment by lonerwolf** [comment]
thanks.i just run some loop in different thread,and give average handles in the loops.

**Comment by lonerwolf** [comment]
@saghul this is trouble.in uv_tcp_init->uv__handle_init->QUEUE_INSERT_TAIL(&(loop_)->handle_queue, &(h)->handle_queue); this is not thread safe

**Comment by saghul** [comment]
Exactly, that's not thread safe.

**Comment by Climax777** [comment]
This is why I wouldn't use libuv and rather stick with ASIO or something custom. In the age we're living in not compensating for, or leveraging, multicore architectures is a huge mistake.

**Comment by bnoordhuis** [comment]
@Climax777 Libuv's popularity indicates that a lot of people don't feel that way.  You're saying they're all wrong and you're right?

**Comment by Climax777** [comment]
@bnoordhuis I meant no disrespect. In fact I'm quite fond of the library and in particular node.js. I make use of Node.js in large projects.

The only reason I am not using libuv in other systems is due to the issue linked here. Single threaded just won't cut it and using a pipe is not very portable or elegant. 

I also feel strongly that popularity is by no means an indication of the quality or applicability of a product. It merely  says it is popular and suits most people's use cases. It doesn't say it fits every use case or that there is no room for improvement. 

If you are able to solve this issue in an elegant and safe way this library is close to perfect. 

Even so great work on a great library and I am excited to see how it grows.
