### ISSUE TITLE
Will read_cb be called immediately after alloc_cb for uv_read_start?

### ISSUE THREAD

**Issue by strrchr** [libuv/libuv#1085]
I found node_http_parser.cc allocates a single buffer for multiple parsers.
```
  static void OnAllocImpl(size_t suggested_size, uv_buf_t* buf, void* ctx) {
    Parser* parser = static_cast<Parser*>(ctx);
    Environment* env = parser->env();

    if (env->http_parser_buffer() == nullptr)
      env->set_http_parser_buffer(new char[kAllocBufferSize]);

    buf->base = env->http_parser_buffer();
    buf->len = kAllocBufferSize;
  }
``` 
Will read_cb be called immediately after alloc_cb for uv_read_start, especially in Windows IOCP?

**Comment by saghul** [comment]
Yes, for a given stream. On Windows it's possible to get alloc_cb and
read_cb intertwined, but from the perspective of a single stream, they will
always come one after the other.

PS: Please use the mailing list for questions next time.

On Oct 11, 2016 01:46, "strrchr" <notifications@github.com> wrote:

I found node_http_parser.cc allocates a single buffer for multiple parsers.

  static void OnAllocImpl(size_t suggested_size, uv_buf_t* buf, void* ctx) {
    Parser* parser = static_cast<Parser*>(ctx);
    Environment* env = parser->env();

    if (env->http_parser_buffer() == nullptr)
      env->set_http_parser_buffer(new char[kAllocBufferSize]);

    buf->base = env->http_parser_buffer();
    buf->len = kAllocBufferSize;
  }

Will read_cb be called immediately after alloc_cb for uv_read_start,
Especially in Windows IOCP?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/libuv/libuv/issues/1085>, or mute the thread
