### ISSUE TITLE
Add one-shot signal handler mode

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#1104]
See https://github.com/nodejs/node/issues/9050.  It can be useful to have a one-shot version of `uv_signal_start()` that resets the signal handler when the signal is received.

For anyone wanting to work on this, API and ABI compatibility should be preserved if you target the v1.x branch.

**Comment by mk-pmb** [comment]
To avoid confusion: The first few posts are about sync program structure. The "SIGINT once" part starts at [my 2nd post](https://github.com/nodejs/node/issues/9050#issuecomment-255557608).

**Comment by santigimeno** [comment]
WRT the 2nd example in https://github.com/nodejs/node/issues/9050#issuecomment-255557608:

```
node -e 'process.once("SIGINT", console.log.bind(console, "int!"));
  const blockUntil = Date.now() + 5e3; while (Date.now() < blockUntil) {}'
```

is it correct to assume that if this one-shot signal handler is implemented and 2 consecutive SIGINT are received, the process will exit after the second `SIGINT` but the SIGINT listener will not run because the loop hasn't moved forward?

**Comment by bnoordhuis** [comment]
@santigimeno Correct, the second SIGINT simply terminates the process.
