### ISSUE TITLE
udp on windows is not aio

### ISSUE THREAD

**Issue by sunlock21** [libuv/libuv#1129]
libuv udp on windows is not using asynchronous io, just using unblock mode. they two are not the same. unblock udp on windows is not the highest io rate.

**Comment by txdv** [comment]
https://github.com/libuv/libuv/blob/v1.x/src/win/udp.c#L436-L450

Are you sure about that? This code block looks to me like it is using IOCP if it doesn't immediately succeed.

**Comment by sunlock21** [comment]
Yes, I am sure.  IOCP not means AIO.  First ,udp in libuv created  never using WSA_FLAG_OVERLAPPED. Next, uv_active_udp_streams_threshold is a dead value zero, every recv using flag: MSG_PEEK, zero buf, IOCP here, just for detect data coming or not, then,do a  real recv data. Third, GetQueuedCompletionStatusEx is not using perfectly.  And, it is not able to  multiple recv or read in the same time.

**Comment by txdv** [comment]
Do you want to write a patch fixing this?

**Comment by bnoordhuis** [comment]
Does it make sense to use AIO for UDP?  Does the NT kernel block when it can't send the datagram right away or does it queue it up?

**Comment by sunlock21** [comment]
When I try to get  higher io bitrate in 10gb network,  I got a program using udp AIO,  but I cannot reach my target. So I try to using libuv to do it ( I think it's so good ), but it got more poor.  then, I  study the libuv codes.  Maybe It does not aim this.

**Comment by bnoordhuis** [comment]
Maybe it's different on Windows but on UNIX systems, if you simply want to pump out datagrams at the highest possible rate, the event loop model is a poor fit because of the latency it introduces.  Standard operating procedure is to have one or more dedicated threads that simply call sendmsg() in a loop.

**Comment by piscisaureus** [comment]
UDP on Windows is undoubtedly using a AIO for UDP.

There's an additional optimization where the asynchronous notification is bypassed a send/receive operation can be completed no blocking, which is maybe throwing you off.

If you don't believe me, try to find the place in the source where we poll the file descriptor for readiness, which would be unavoidable if we were relying on nonblocking I/O only.

I would also like to remark that AIO isn't noticeably faster than nonblocking I/O, at least not on Windows 7 where I did most of the benchmarking. We use AIO because the preferred multiplexer GetQueuedCompletionStatusEx, which is much faster and than the alternatives (select etc), doesn't support readiness notifications (not always/officially anyway).

Closing this bug as invalid.
