### ISSUE TITLE
Graceful termination on process on Windows

### ISSUE THREAD

**Issue by johanneswuerbach** [libuv/libuv#1133]
Currently all child processes are forcefully killed on Windows https://github.com/libuv/libuv/blob/d9d207774ea1f734310982300e55dd64b3f5682b/src/win/process.c#L1167-L1189, which doesn't allow to perform any kind of cleanup in the child process.

Instead of always forcefully terminating, a https://msdn.microsoft.com/en-us/library/windows/desktop/ms632617(v=vs.85).aspx message should be send when possible to allow the child process to gracefully terminate (like SIGTERM on unix). I'm aware that this might not be possible in all cases, but should work when an application with windows (like a browser) is spawned.

**Comment by moteus** [comment]
There also `GenerateConsoleCtrlEvent` function may be useful in some cases.

**Comment by johanneswuerbach** [comment]
I'm currently working around this by spawning `taskkill` https://technet.microsoft.com/en-us/library/bb491009.aspx without `/F` https://github.com/testem/testem/blob/441504a48cbc4c51bfeaf7ac1ce9e3ffb6867e5e/lib/utils/process.js#L117-L133, which seems to do the right thing for non-headless processes.

**Comment by moteus** [comment]
If you send WM_CLOSE app may also ask about confirm about closing with message box.
Its not bad or good. Just need to remember.

**Comment by bnoordhuis** [comment]
Pull requests welcome.  They should probably be against the master branch because it sounds like a backwards incompatible change in behavior.

**Comment by sam-github** [comment]
WM_CLOSE sounds awful, if it pops up a box, that isn't compatible with window, and that child processes sometimes pop up terminals is already a source of complaint, adding a confirmation box is going the wrong way.

I don't have easy access to Windows ATM, but I was pretty sure that one or both of SIGINT/SIGTERM/SIGHUP (I don't see signs of the latter in the code) was emulated enough by libuv that windows node child processes could have a handler (not a true signal hander, because they don't exist, but something that looked like one), and that some cleanup could be done, but that if the process didn't then exit within a grace period of some seconds, windows would then terminate the process (unlike unix, where if you handle the signal you can choose to not terminate).

**Comment by johanneswuerbach** [comment]
My use-case is to terminate browser processes so I can't really influence the code.

Maybe WM_QUIT https://msdn.microsoft.com/en-us/library/windows/desktop/ms632641(v=vs.85).aspx would be more appropriate, but as I'm not a windows dev this is only an idea and not a recommendation

**Comment by bzoz** [comment]
There is an "How To Terminate an Application "Cleanly" in Win32" article here: https://support.microsoft.com/en-us/kb/178893. It says, that a proper clean way is to send `WM_CLOSE` to all windows of given app. There even is code sample that could be used. What we could do is use this method for `SIGTERM` and keep the old one (`TerminateProcess`) for `SIGKILL`. 

We can also have libuv send `WM_CLOSE`, and if that does not kill target process use `TerminateProcess` (after some timeout). As an alternative, there is `EndTask` function (https://msdn.microsoft.com/en-us/library/ms633492(VS.85).aspx) that seems to do just that.

@sam-github under Unix one can have handler for `SIGTERM`. User shouldn't assume that a process will surely terminate just after receiving it. I don't think that this is very different to a window poping out. 

@bnoordhuis are you sure this needs to go to 2.0? Especialy this method of first trying `WM_CLOSE` before `TerminateProcess` sounds like a compatible change

**Comment by bnoordhuis** [comment]
@bzoz Can it be implemented without changing the API or the ABI?  If the answer is 'no', e.g. because you need to add a timer handle somewhere, we don't need to be having this discussion.

**Comment by bzoz** [comment]
By using Windows thread pool for hosting delayed call to `TerminateProcess` this can be done without changing neither API nor ABI. Draft of the implementation is here: https://github.com/janeasystems/libuv/commit/3e64a3e4acb26f5ca5962d1c395048f4738af800.

There are however other problems. It seems there is no clean way to send CTRL-C nor CTRL-BRK to another process. There are workarounds [(related stackoverflow question)](http://stackoverflow.com/questions/813086/can-i-send-a-ctrl-c-sigint-to-an-application-on-windows) but they look fragile. So, one libuv app will not be able to send `SIGINT` to another libuv app, which would be surprising.

Also, if user uses `uv_kill` and then exits, process will terminate before worker thread calls `TerminateProcess`.

I'm not sure if we should add this to libuv, mostly because it would only sort-of works for windowed applications. However, I can make PR against 2.x if needed.

**Comment by sam-github** [comment]
> So, one libuv app will not be able to send SIGINT to another libuv app, which would be surprising.

Would it? windows doesn't have signals, uv emulates them for some very specific circumstances, but general IPC isn't among them. I think it just has to be documented. IIRC, SIGINT/TERM are just turned into TerminateProcess, and then (but only for child processes), uv modifies the exit status to look like they terminated by signal as they would have on unix.

**Comment by feifeipan** [comment]
hey, I've update graceful to support windows.

please see https://github.com/feifeipan/childprocess-exit for details.

**Comment by madwax** [comment]
Hi I've just ran head long into this one myself.   
Sending WM_CLOSE to a Win32 processes, that is the correct way for the OS but would do  WM_CLOSE to SIGINT and WM_QUIT to SIGKILL. Also for console apps you should do GenerateConsoleCtrlEvent().  As you don't know what the process is it's a case of having to do both :/
Also hack's out there do code injection which if your app is x86_64 and your child process is x86, your in trouble.

If anyone else runs into this  GenerateConsoleCtrlEvent() works if you don't pass UV_PROCESS_DETACHED but your application is sharing a console with the child process so you get CTRL-C.  You should be able to freeConsole() do the Genreate and then attachConsole() but it's not thread safe.
