### ISSUE TITLE
Unexpected timer behavior

### ISSUE THREAD

**Issue by dkrikun** [libuv/libuv#1142]
From what I understand from the docs, a timer shall take its callback execution time into account when. However, from the following test case I observe otherwise.

```
void timer_cb(uv_timer_t*)
{
    print("%d", GetTickCount());
    Sleep(1000);
}

int main(int argc, char** argc)
{
   uv_loop_t* loop = uv_ default _loop();
   uv_timer_t timer;

   uv_timer_init(loop, &timer);
   uv_timer_start(&timer, timer_cb, 0, 5000);

   uv_run(loop, UV_RUN_DEFAULT);L
```

You can see that the callback is called each 6000 msec.

**Comment by bnoordhuis** [comment]
I think I may have explained it confusingly in #181 and that ended up more or less verbatim in the documentation.  I've added the doc label, documentation pull requests welcome.

In your example, if you call `uv_update_time()` at the end of the timer callback, it runs again in five instead of six seconds.  The timer is rearmed relative to libuv's idea of now and that needs to be updated in long running callbacks.

**Comment by dkrikun** [comment]
Ktx
