### ISSUE TITLE
feature request: enable observation and troubleshooting of the work queue/thread pool usage

### ISSUE THREAD

**Issue by sam-github** [libuv/libuv#1144]
What kind of information can libuv expose to give an indication of work queue depth/thread utilisation/over utilisation?

I'd like to know the work queue depth over time, which implies (if non-zero) that there are no free threads in the pool. Actually, I guess there are two numbers: queued but not in progress, and in-progress.

Maybe it would also be useful to know number of free threads, but if the queued count is zero, does it matter?

What could the API look like?

One way would be a simple API to expose this number as a count. That would require sampling it, which might miss its highs and lows, so may not be so useful.

Perhaps a better way would be to collect statistics, and allow the stats to be cleared on sample:

- the total work requests
- total requests that spent time on queue
- total/average/mean/stddev of time on queue
- high/average/mean/stddev of queue depth

Or a third way might be to simply expose some kind of callback hook for the life-cycle of the queue:

- when requests are queued
- pulled off the queue
- completed

In this case, overhead is near-zero when unused (just a check against a null function pointer), and the user of the API can determine what stats they want to collect.

Also, I guess its possible to get this info for Node.js by implication: monkey-patching everything at the js layer that is known to use the thread pool. The problem with this is that its not possible to distinguish between latency due to how long (for example) getaddrinfo takes to complete, and latency due to getaddrinfo waiting in the work queue for a free thread.

Thoughts, @bnoordhuis?

cc: @tobespc

**Comment by piscisaureus** [comment]
+1

**Comment by bnoordhuis** [comment]
I don't recall exactly when we discussed it (earlier this week, yes, but that wasn't the original discussion) but submit/pre-process/post-process/completion hooks are arguably the most flexible mechanism.  We should be able to land that in a semver-minor release because it shouldn't need API- or ABI-incompatible changes.

Some thought should be given to what locks need to be held when modifying or iterating the hook's list of callbacks because it influences what libuv functions you can and cannot call from a callback.
