### ISSUE TITLE
Loop slippage feature

### ISSUE THREAD

**Issue by catroot** [libuv/libuv#1165]
Is there possible to realize configurable slippage for loop? I.e. defining a time quant for the loop and limit loop handlers to takeover the loop for a max quants, then bypass overdued handler to the next loop round?

This feature will allow to avoid lags for handlers with massive computations at huge load and loop will behave more smoothly.

**Comment by saghul** [comment]
As I said [here](https://github.com/saghul/pyuv/issues/226#issuecomment-265089851) I don't think it's possible to implement that.

**Comment by catroot** [comment]
Sad.

**Comment by saghul** [comment]
Do you have any suggestions?  I just don't know *how* this would work, at all.  How would you stop a running function if it goes beyond its allocated time slot and who is the entity resposible to do that?  The only way I know how to (sort of) do it is by using a form of cooperative multitasking, but that doesn't work in all cases, for instance it won't work with CPU bound  tasks, or it would require the task to cooperate. But we won't be adding green threads to libuv so that's kinda out of the question... Maybe SIGALRM? But that'd be a hell of a mess.

To the best of my knowledge, what you ask for it not possible, but I'd be glad to be shown otherwise :-)

**Comment by catroot** [comment]
Single threaded solution has no other way instead of recursion. The one loop round must be called from the handler cb function, this can be done explicitly in cb code at any time for now via handler.loop.run(UV_RUN_NOWAIT).  But this is not the same thing as i'm asking for.

To achieve slippage inside a loop we need a some kind of a partial wrapper, which will wrap callback to the middle of any loop handler callbacks, where it was called, and then add calling itself at the next round of the loop.
But i don't know how to create callback to the middle the running function to continue their execution later and return them.

**Comment by saghul** [comment]
> Single threaded solution has no other way instead of recursion. The one loop round must be called from the handler cb function, this can be done explicitly in cb code at any time for now via handler.loop.run(UV_RUN_NOWAIT).

The libuv loop is not recursive.  You cannot call `uv_run` from within `uv_run`.  Well, you *can*, but it's not designed to work that way and things will break.

> To achieve slippage inside a loop we need a some kind of a partial wrapper, which will wrap callback to the middle of any loop handler callbacks, where it was called, and then schedule calling itself at the next round of the loop.

I'm not sure what you mean here.  It's still not clear to me what would make a function to stop running.

> And you are right, for single threaded app there is no implicit way to make such feature.
> I will spawn the huge calcs to the dedicated thread.

Yeah.  You can use a `uv_async_t` to communicate with the loop thread.  Just make sure you can `uv_async_init` in the loop thread. 

I'm going to close this since there is no action to be taken in libuv.

**Comment by catroot** [comment]
> what would make a function to stop running
I`m talking about explicit way. Something must be called from inside handlers callback to trigger it.

**Comment by saghul** [comment]
> I`m talking about explicit way. Something must be called from inside handlers callback to trigger it.

In that case you should be able to do it without any cooperation from libuv: use `uv_queue_work` and attach some "state" to your work instance.  Send the work request and after you deem appropriate claim to finish but setting the state to something you know.  Then in the `after_work_cb` check what the state is and re-schefule the work request or finish.

Wouldn't this solve your usecase?

**Comment by catroot** [comment]
> I will spawn the huge calcs to the dedicated thread.

This is exactly what i mean.
