### ISSUE TITLE
Make check handle runs before the callbacks.

### ISSUE THREAD

**Issue by yihuang** [libuv/libuv#1170]
Currently, check handle runs after ``uv__io_poll``, which poll io events and call the io callbacks.
In my case, it would be much more useful if check handle can run right after poll io events, and before executing all the callbacks. So I can use prepare handle and check handle to wrap all the user codes.
Can we change the behavior of check handle or add some new kind of handles to do this.

**Comment by saghul** [comment]
I don't think we can, since it works like this by design.  Prepare handles run before i/o and check handles run after it, that's the invariant and I don't see that changing.

> So I can use prepare handle and check handle to wrap all the user codes.

I don't understand this.  If the i/o callbacks would run *after* the check handle callbacks, what exactly would you be wrapping?

Can you explain what you're trying to accomplish?  Maybe we can find a different approach :-)

**Comment by yihuang** [comment]
Currently, I have only one use case for this, to record all the time spend by user code in one frame(loop), exclude the time speed on poll wait.

**Comment by saghul** [comment]
Then this approach wouldn't work either because that would not count the time spent in timer, idle handles, and many other things which are i/o driven like async handles.

Maybe you can do this:

```
start_time = X;
uv_run(loop, UV_RUN_ONCE)
stop_time = X;
```

Then use a prepare / check pair to compute the amount of time spent in i/o and substract it from the calculation of an entire loop tick.

Would that work for you?

**Comment by yihuang** [comment]
I'm using libuv in client side GUI framework, and it would be helpful to identify the slow frames, maybe it's not that useful for server application.

**Comment by yihuang** [comment]
I don't understand your suggestion, basicly I have some timers runs at a stable frenquency, an async to handle inter Thread communications, some infrequent network activity. I don't want too many things happen in one loop, if that happens, I will try to distribute  them in different loops or background thread.

**Comment by saghul** [comment]
What I suggested is a way to measure how long a loop iteration takes, without counting i/o.  It basically consists on meassuring an entire loop iteration, by running it with UV_RUN_ONCE instead of UV_RUN_DEFAULT and then using a prepare / chek pair to compute how much was spent in i/o alone.  Then do the math and you'll have the duration of a loop iteration, excluding i/o.

I'm not sure if that is exactly what you need, but your usecase seems too specific to cover it generally in libuv.  Not to mention changing current core behavior.

**Comment by yihuang** [comment]
``UV_RUN_ONCE`` don't block if there is progress, but will block if there is no progress, right?
I only want to exclude the time spend on the blocking poll call, I guess I just want to include all the time spend on cpu.
I can understand if that's not covered.
I want to clarify myself with some pseudocode:

```
while True:
    process timers
    process prepare handle
    io_poll
        call system poll api, may blocking
        execute network io callbacks
        execute async callbacks
```
I only want to exclude the time spend on the system poll api call, not the whole part of io_poll, because there are significant user code running in io callbacks and async callbacks which I don't want to exclude.

**Comment by saghul** [comment]
> UV_RUN_ONCE don't block if there is progress, but will block if there is no progress, right?

Correct.

I think I now see your usecase, but it's too much on the edge, I'm afraid.

**Comment by yihuang** [comment]
@saghul I have another use case for this feature, I have a global lock need to be grabbed, and I want to release the lock only when waiting for io.
In other words, release the lock before waiting for io(prepare handle), grab the lock immediately after waiting io(?).

**Comment by saghul** [comment]
I stand by what I said here: https://github.com/libuv/libuv/issues/1170#issuecomment-267547625 Your usecase is too narrow to add a whole new handle for it.

**Comment by sam-github** [comment]
@bnoordhuis @saghul  The feature @yihuang desires sounds related to https://github.com/RuntimeTools/appmetrics/blob/82d7b9d750fb131f3cfbcf772d617703e36c41da/src/plugins/node/prof/watchdog.h#L291-L294, would it allow us to stop monkey-patching epoll? Or has the epoll patch been unnecessary since https://github.com/joyent/libuv/issues/1317 was fixed?

**Comment by bnoordhuis** [comment]
> Or has the epoll patch been unnecessary since joyent/libuv#1317 was fixed?

Yes.  app-metrics/strong-agent can drop it when it drops support for v0.10.

**Comment by yihuang** [comment]
@bnoordhuis 
Do you need to watch the ending of io poll? It's ok to use prepare handle to watch beginning of io poll, but it's problematic to use check handle to watch ending of io poll.
