### ISSUE TITLE
unix: uv_tty_init overwrites input tty file descriptor.

### ISSUE THREAD

**Issue by torque** [libuv/libuv#120]
Currently, any file descriptor that is a tty (according to `isatty`) passed in to `uv_tty_init` will be overwritten with a file descriptor pointing to `/dev/tty`. This is a problem because I want to stream data from a serial device disguised as a tty, `/dev/tty.usbserial`, which is distinctly not `/dev/tty`.

Blame points to b197515367d1a996dca9009483d202b306f9474e from joyent/libuv#1184. This leads me to believe this is somewhat intentional, but I can't find it mentioned in the documentation. If `uv_tty_t` is intended to only provide access to `/dev/tty`, this should be explicitly documented.

#19 seems to provide an alternate approach to solving this problem, but it's a larger change that needs to be reviewed, tested, and documented.

I think more reasonable behavior would be to duplicate the file descriptor passed to `uv_tty_init`.

The following patch fixes my problem, but I don't know what ramifications it may have for other use cases.

```diff
diff --git a/src/unix/tty.c b/src/unix/tty.c
index 068025e..c8847f2 100644
--- a/src/unix/tty.c
+++ b/src/unix/tty.c
@@ -66,7 +66,7 @@ int uv_tty_init(uv_loop_t* loop, uv_tty_t* tty, int fd, int readable) {

     newfd = r;

-    r = uv__dup2_cloexec(newfd, fd);
+    r = uv__dup2_cloexec(fd, newfd);
     if (r < 0 && r != -EINVAL) {
       /* EINVAL means newfd == fd which could conceivably happen if another
        * thread called close(fd) between our calls to isatty() and open().
```

**Comment by saghul** [comment]
Hi @torque, if your device is not really a TTY then you a probably better off by using `uv_pipe_open`. `uv_tty_t` handles are meant to work with TTYs, that's the expected behavior. Your change just dups the fd passed to `uv_tty_init` while still reopening `/dev/tty` for no purpose. The reason for reopening `/dev/tty` is explained here: https://github.com/libuv/libuv/commit/b197515367d1a996dca9009483d202b306f9474e#diff-dbb5fc0f79a267503afb54c61e57fcc7R46

I'll update the documentation to try to clarify this behavior.

**Comment by torque** [comment]
I figured the patch wasn't quite right, but I wanted to get some feedback. Thanks for the tip about uv_pipe. It seems to work fine for what I'm doing. Not sure how I missed it.

Clarifying the behavior is a fine way to resolve this. Thanks.
