### ISSUE TITLE
Document uv_tcp_duplicate_socket or expose UV_HANDLE_SHARED_TCP_SOCKET

### ISSUE THREAD

**Issue by alexhultman** [libuv/libuv#1204]
Hi,

I had this mental journey regarding duped sockets in libuv and I found that you need to manually set UV_HANDLE_SHARED_TCP_SOCKET in order to not have uv_close call shutdown on the socket on Windows (which messes with the duped socket).

Currently I have hardcoded the value of UV_HANDLE_SHARED_TCP_SOCKET which is not guaranteed to be portable. Maybe this flag could be exposed? Is it new?

Or, making uv_tcp_duplicate_socket more visible explaining this flag. Is that function new?

**Comment by saghul** [comment]
That's an internal function used by libuv when sharing sockets on Windows.  You shouldn't need to mess with it.

Can you please walk me through your use case? Note that dup-ing a socket "owned" by libuv is not a feature we currently support.

**Comment by alexhultman** [comment]
So what I do is I dup the fd of an uv_tcp_t followed by calling uv_close on the handle. Basically stripping the uv_tcp_t down to an fd. I use this in Node.js to strip away bloat and then I use the fd in an uv_poll_t instead. If I recall correctly you personally showed me how to do this?

It works, but recently I found a bug only affecting Windows in some special cases and the solution was to set this flag before calling uv_close, so that shutdown wasn't called. I figured, maybe this support should be made more official since it's now starting to get uglier and uglier. Node.js devs refuse to acknowledge my need for this feature and I'm apparently banned from their repo so I thought maybe libuv is a better place to discuss these things.

**Comment by alexhultman** [comment]
Hey I found our initial thread: https://groups.google.com/forum/#!topic/libuv/soDANDUb5bA

**Comment by saghul** [comment]
> It works, but recently I found a bug only affecting Windows in some special cases and the solution was to set this flag before calling uv_close, so that shutdown wasn't called.

Does this only happen when you do it for handles which you received over a pipe? Or for any Windows handle?

I know I told you to do this, some people use it, and it seems to work for the most part on Unix, but apparently not that great on Windows.  Note that the flag you mention is meant for something else, it just so happens to trigger the behavior you want, we'd need a more generic approach here.

**Comment by alexhultman** [comment]
I've done some testing and also looked at the sources of Node.js down to libuv calls and everything seems to be all right, even if it surely is in haxx-domain. The flag does exactly what it should do.

I get the uv_tcp_t from a Node.js callback, so I'm in the same process as Node.js and I don't use any libuv specific feature to send handles, I don't really know what you mean by "over a pipe".

**Comment by bnoordhuis** [comment]
> I don't really know what you mean by "over a pipe".

Handles sent from one process to another over a uv_pipe_t.

**Comment by alexhultman** [comment]
No it is only in the same process, no pipes or nothing.

**Comment by saghul** [comment]
Ah, I see what you mean now: https://github.com/libuv/libuv/blob/v1.x/src/win/tcp.c#L1385

I tried to understand why we would do that, and here is the original comment, which was removed when the code got factored out to another function in 2012:

```
      /* If we don't shutdown before calling closesocket, windows will */
      /* silently discard the kernel send buffer and reset the connection. */
```

I'd say we are trying too hard here.  If we call `uv_close` this shouldn't trigger a graceful shutdown, there is `uv_shutdown` for that.

Maybe @piscisaureus can enlighten us a bit, but ATM I'd say we get rid of that logic and do an abrupt teardown if the socket has a pending read.

**Comment by alexhultman** [comment]
Agree shutdown is too much for uv_close

**Comment by piscisaureus** [comment]
`uv_close()` without `uv_shutdown()` is supposed to gracefully close the socket (drain the send buffer, then send a FIN packet). This is in line with *nix behavior, and node.js relies on this to make http slightly faster (by avoiding an unnecessary `shutdown()` syscall). Windows does this properly, *except* if there's an asynchronous `WSARecv()` operation pending on the socket that's being closed; in that case it'll hard-reset the socket (throw away the send buffer and send a RST packet). 

The way around this is that we call `shutdown()` explicitly just before closing the socket; when we do that windows behaves as expected even if there are pending reads. 

However the workaround described above doesn't work for shared sockets, because if there's another handle to the same socket still open, it will also be affected by the explicit `shutdown()` call. When a socket is shared between processes, a `uv_close()` call in one process would render the duplicate in the other process unusable. That's why we only do it if the socket is non-shared; this allows libuv users to use shared TCP sockets with the caveat that if they do so they have to use call `uv_shutdown()` always before closing a socket.

But there's a way out: since we no longer support Windows XP/2k3, we could use `CancelIoEx()` to cancel any pending `uv_read()` requests in `uv_close()`. With that, we would no longer need to call `shutdown()`.

@saghul I hope I explained it in an understandable way. Let me know if you have any more questions.

**Comment by piscisaureus** [comment]
> I'd say we are trying too hard here. If we call uv_close this shouldn't trigger a graceful shutdown, there is uv_shutdown for that.

We could argue about this all day long, but this is not what the world has agreed upon. 

The behavior when sockets are closed is controlled with the `SO_LINGER` socket option. Documentation for this option is often not that great, so let me summarize: 

When a socket is closed with data still in the send buffer, the operating system gives you basically three options:

A. `close()` returns immediately (doesn't block); the data in the send buffer is discarded and the connection is reset.
B. `close()` blocks until all data in the send buffer is sent and the connection is gracefully closed.
C. `close()` returns immediately, but the operating system attempts to deliver and gracefully close in the background; optionally a timeout may be specified after which the OS gives up and resets the connection. 

The default behavior on all platforms is option C. It's efficient because an application can close and forget about a socket as soon as it has placed all outbound data in the send buffer.
(The downside is that an application is ultimately unable to tell whether transmission has succeeded - I will argue this really isn't a problem at all, but that's too far into the weeds for now).

It's also the desirable behavior for libuv, because otherwise we'd have to deal with a blocking call to either `shutdown()` or `close()`, which means that we'd always have to offload those operations to the thread pool, which is inefficient.

Links:
* [windows)[https://msdn.microsoft.com/en-us/library/windows/desktop/ms739165(v=vs.85).aspx]
* [linux](http://man7.org/linux/man-pages/man7/socket.7.html) (search for SO_LINGER)

**Comment by alexhultman** [comment]
So if we consider `int uv_tcp_open(uv_tcp_t* handle, uv_os_sock_t sock)` being called on an already duped SOCKET on Windows, then how do you tell libuv that this uv_tcp_t is a shared socket when the flag UV_HANDLE_SHARED_TCP_SOCKET is not exposed? uv.h does not define UV_HANDLE_SHARED_TCP_SOCKET, right?

I'm neutral regarding the behavior of uv_close, I just want the feature to mark a socket as shared to be exposed, or any other official interfaces for doing the same.

**Comment by piscisaureus** [comment]
> So if we consider int uv_tcp_open(uv_tcp_t* handle, uv_os_sock_t sock) being called on an already duped SOCKET on Windows, then how do you tell libuv that this uv_tcp_t is a shared socket when the flag UV_HANDLE_SHARED_TCP_SOCKET is not exposed? uv.h does not define UV_HANDLE_SHARED_TCP_SOCKET, right?

True, I could see a case for augmenting the `uv_tcp_open()` to take that option.

However my first suggestion would be to replace the `shutdown()` hack with a `CancelIoEx` hack and get rid of the flag entirely.

**Comment by saghul** [comment]
Hey Bert, thanks for chiming in, much appreciated.

> uv_close() without uv_shutdown() is supposed to gracefully close the socket (drain the send buffer, then send a FIN packet). This is in line with *nix behavior

Is this really the case?  I don't see any code on Unix working towards this goal.  Looks like `uv_close` just tears down stuff and that's that. @bnoordhuis ?

I'll check the `SO_LINGER` stuff, but we don't set it in libuv, FWIW.

> However my first suggestion would be to replace the shutdown() hack with a CancelIoEx hack and get rid of the flag entirely.

Cool! I'll work on that for v2.

**Comment by alexhultman** [comment]
Works for me, thanks :+1:

**Comment by piscisaureus** [comment]
@saghul 

> Is this really the case? I don't see any code on Unix working towards this goal. Looks like uv_close just tears down stuff and that's that. @bnoordhuis ?

We don't need to do anything about it, because all OS do this automatically when SO_LINGER is left at it's default setting.

> I'll check the SO_LINGER stuff, but we don't set it in libuv, FWIW.

See the comment above :)

> However my first suggestion would be to replace the shutdown() hack with a CancelIoEx hack and get rid of the flag entirely.

Awesome!
