### ISSUE TITLE
Is OpenBSD a supported platform?

### ISSUE THREAD

**Issue by vext01** [libuv/libuv#1225]
Should we add OpenBSD to the list of supported platforms?:
https://github.com/libuv/libuv/blob/master/SUPPORTED_PLATFORMS.md

FWIW, I just imported libuv into OpenBSD ports (as a neovim dependency), meaning that starting with OpenBSD-6.1 there will be binary packages available.

Thanks for libuv

**Comment by bnoordhuis** [comment]
When you say "supported" I assume you mean tier 1 status?  We don't test OpenBSD in our CI so I don't think we can credibly claim to support it.

Even tier 2 status is somewhat questionable because, contrary to what SUPPORTED_PLATFORMS.md says, most tier 2 systems are actually part of our CI.  z/OS is the only exception at the moment and I expect that is only temporary.

**Comment by jbergstroem** [comment]
I'd love to get it up there and part of CI; sponsors welcome (@vultr, looking at you!)

**Comment by saghul** [comment]
Closing since there is nothing actionable on our side at the moment.
