### ISSUE TITLE
The way libuv does inheritance violates strict aliasing

### ISSUE THREAD

**Issue by pskocik** [libuv/libuv#1230]
With strict aliasing (since C99, AFAIK) and something like:
```
struct base{
    BASE_FIELDS
};
struct derived{
    BASE_FIELDS
    DERIVED_FIELDS
};
```
reading `struct derived` through `struct base*` results in undefined behavior. The whole inheritance emulation libuv uses is broken with strict aliasing on.

Making those bases into named members would fix the problem.

I tentatively fixed it for Linux here https://github.com/pskocik/libuv/tree/inh .
An unfortunate consequence is that it changes the API by changing how the variables are accessed.

**Comment by bnoordhuis** [comment]
> An unfortunate consequence is that it changes the API by changing how the variables are accessed.

That might make it acceptable for v2.x but we couldn't land it in v1.x.

I had a discussion with a clang maintainer a few years ago about if what libuv does constitutes a strict aliasing violation.  IIRC, our conclusion was that it depends on whether you interpret the language in the standard as nominative or structural.  In the nominative interpretation it's a violation, in the structural interpretation it's not.

The language doesn't really say which one is correct but compilers all seem to take the structural approach.

**Comment by pskocik** [comment]
It'd be much safer to convert it to composition or unions. I tried asking about this for clarification: http://stackoverflow.com/questions/42352681/strict-aliasing-and-overlay-inheritance . Check it out. It turns out modern compilers don't really seem to handle overlay inheritance well.

Anyway, what I did in the linked tree was convert it to members and fixed up the code to make sure it compiled on Linux (I don't have access to Windows or MacOs).

Within the confines of standard C, this pattern would be viable too www.deleveld.dds.nl/inherit.htm, and it has the advantage that with it, you can access a member with the same macro regardless of where you are in the inheritance tree. It's a little more suitable to being applied through a mini DSL, but I think applying it would be a bit of an overkill for an inheritance tree as simple as what libuv has.

You can also get inheritance support  (and I really like this one) on gcc and clang with -fms-extension or -fplan9-extensions (superset of the former), and I would hope it handles strict aliasing well, but it's non-standard too, and again, probably not worth the trouble for an inheritance tree as simple as libuv's.

**Comment by vcunat** [comment]
You don't need to touch API or ABI to make it standard-conforming.  It should enough to create a type that's a union of everything and use pointer to that type for casting (as intermediate type).  That would satisfy the [wording of the C standard](https://stackoverflow.com/a/7005988/587396), and it shouldn't be hard to implement.  (IMHO relying on `-fstrict-aliasing` is slightly risky.)

**Comment by bnoordhuis** [comment]
@vcunat That might be well-defined behavior with some compilers but is still UB in general ([quickest link I could find](https://stackoverflow.com/questions/2906365/gcc-strict-aliasing-and-casting-through-a-union)).

**Comment by vcunat** [comment]
Oh, right, I believe this is about the fact that to strictly conform to the standard you have to *access* through a union pointer, not use the union to convert one pointer type to another.  (Presumably because it's difficult to know if a parameter passed to a function went through such a conversion somewhere long before the call.)  In the referenced gcc docs there's also an example of this, directly above the example about that "pointer type conversion through a union" being UB, and it has been there since [gcc-4.4.0 docs](https://gcc.gnu.org/onlinedocs/gcc-4.4.0/gcc/Optimize-Options.html#Optimize-Options).

Consequently, the type signatures in ABI would have to be these unions, unfortunately, if I understand it correctly.  That might be considered an API/ABI change.

**Comment by vtjnash** [comment]
Should we add this to the v2 label? There's a branch above showing the necessary changes to make the compiler not complain, but it seems like it'd also make further v1.x maintenance very difficult. Since (afaik), libuv does the type-casts at file boundaries, there isn't a current risk here of a mis-compile.

> you have to access through a union pointer

That was thought to be correct and recommended in the past (it even got a note in the standard!), but was subsequently found to be flawed and is now considered to still violate strict aliasing rules. The current standards-compliant approach would be to do `{ int flags; memcpy(&flags, &stream->flags, sizeof(flags)); flags }`, but this would be pretty terrible.

**Comment by vcunat** [comment]
Can you provide a reference to this still violating the rules (even though conforming to published C standards)?  What libuv does here is basically C++ -style inheritance, i.e. nothing really special, so compilers just have to support such semantics anyway.

**Comment by vtjnash** [comment]
Yeah, but this issue seems to be about the "letter of the law", not necessarily what we think they should have to support (or appear to be doing OK with currently).

I agree that this seems like it should be covered by "common initial sequence" in the standard (6.5.2.3) and in theory https://github.com/libuv/libuv/blob/8ed9112f50cfa1cb857070460f842a93dfd6753e/include/uv.h#L1672-L1678 might cause the compiler to do something for that. I also don't know of any code here that would get mis-compiled by a reasonable compiler. But note that the rules that I assume you're referencing is only something that implementations _ought_ to support, but are not required to do (missing "SHALL", so it's a normative statement). See also https://stackoverflow.com/questions/34616086/union-punning-structs-w-common-initial-sequence-why-does-c-99-but-not/34641113. So implementation _should_ support this, as it is described in the standard, but it could still be _conforming_ to the standard if it did not. And yeah, [The Strict Aliasing Situation is Pretty Bad](https://news.ycombinator.com/item?id=11288665).

**Comment by vtjnash** [comment]
Just to circle back, apparently most compilers actually don't care about the "common initial sequence" statement and just ignore the union in computing TBAA violations: https://news.ycombinator.com/item?id=11759245 (https://gcc.godbolt.org/z/i8Rvre)

**Comment by bnoordhuis** [comment]
@vtjnash Is your conclusion that what libuv does is UB in a non-theoretical sense? That'd be unfortunate because it's not something we can really change at this point.

**Comment by vcunat** [comment]
The last link suggests to me there might be a real risk.  If you want more concrete example try compiling e.g.
```c
#include <uv.h>
void * f(uv_tcp_t *tcp, uv_handle_t *h)
{
	h->data = NULL;
	tcp->data = &f;
	return h->data;
}
```
with gcc 9 this always returns zero to me, but the compiler "can't know" whether these two point to the exact same memory.  Of course, such examples are minimalistic and seem unlikely to happen as-is in real life, but I would really like to avoid similar risks.  One problem I see is that libuv API in practice _does_ force people to cast to/from `uv_handle_t *` a lot.

Anyway, I personally wouldn't be so sure that there's no reasonable way to fix or at least improve this.  For example, what do you think about this approach?  bc8171e25  ([another link](https://github.com/vcunat/libuv/commits/v/strict-aliasing))  For real-compiler testing I used that nice tool: https://gcc.godbolt.org/z/M_Wxzt (again, watch for `%eax` &ndash; the return value)

**Comment by vtjnash** [comment]
Right, that makes it a bit of a complex question to answer. In https://github.com/libuv/libuv/pull/1457, `-fstrict-aliasing` was removed from the build flags, partly in response to this issue (although I'm not sure it had the exact intended effect, since it appears the autoconf build defaults to -O2 and the gyp build to -O3, both of with have `-fstrict-aliasing` enabled by default).

In practice, libuv does not appear to trigger compiler errors due to TBAA. So in that respect, it is strictly theoretical. There's perhaps a slightly higher risk for libuv users, who may need to be aware of where and when they're casting the type _and_ doing a write through the libuv pointer without invoking the libuv API (all three conditions would generally be necessary to potentially be able to trigger a miscompile).

It also possibly means you should not compile libuv with the LTO flag in the client build (e.g. when building nodejs) without also setting the `-fno-strict-aliasing` flag.

Hm, that seems clever. For historical context, there's some precedence for changing this API (keeping the ABI) in the v1.x series: https://github.com/libuv/libuv/pull/239 which went in the other direction (composition over unions). But also differed from this in that those were considered to be a private API, while this would affect the naming access to the primary public fields (->type and ->data). I guess I should also note that the original author of this thread already noted pretty much everything I'm saying (https://github.com/libuv/libuv/issues/1230#issuecomment-281183666) and listed the several possible options for resolving it (union, composition, `-fno-strict-aliasing`, `fms-extension`, and the inheritance design in that comment).

I don't have any personal recommendation for any of these options—each seems to have its own pros and cons, and I'm not personally invested in any of them.

**Comment by vcunat** [comment]
To be clear, I do prefer composition, but that by itself requires an incompatible API change, which is why I proposed trying that hybrid of union and composition.  (I did test some normal programs against the changed libuv.)

**Comment by bnoordhuis** [comment]
I thought libuv was already being built with `-fno-strict-aliasing` but looks like I was mistaken. I've opened #2588.
