### ISSUE TITLE
On Windows, if uv_fs_event_start() fails, it leaves its handle active with the loop

### ISSUE THREAD

**Issue by ptlomholt** [libuv/libuv#1253]
We noticed that, on Windows, when uv_fs_event_start() is passed a bad or nonexistent path name and fails, it still leaves its handle active with the loop. The following test (notice the bad file name) reproduces the issue:

TEST_IMPL(fs_event_watch_invalid_path_fail) {
#if defined(__MVS__)
  RETURN_SKIP("Filesystem watching not supported on this platform.");
#endif

  uv_loop_t* loop = uv_default_loop();
  int r;

  r = uv_fs_event_init(loop, &fs_event);
  ASSERT(r == 0);
  r = uv_fs_event_start(&fs_event, fs_event_cb_dir_multi_file, "<:;", 0);
  ASSERT(r);
  
  ASSERT(0 == uv_has_ref( (uv_handle_t*) &fs_event));

  MAKE_VALGRIND_HAPPY();
  return 0;
}

**Comment by cjihrig** [comment]
I believe the handle gets ref'ed in [`uv_fs_event_init()`](https://github.com/libuv/libuv/blob/02dcde08386441d5a89dbcb602a1ad367a506cc0/src/win/fs-event.c#L126) from [here](https://github.com/libuv/libuv/blob/45616f542da523b3d87a8d379bb116ffc3a97845/src/uv-common.h#L215). So, I think that test should fail without `uv_fs_event_start()`. I noticed that the handle is not stopped on error on Windows. See https://github.com/libuv/libuv/pull/1257 for a proposed fix. I modified your test to check if the handle was active instead of ref'ed.

**Comment by ptlomholt** [comment]
Yes, you are probably right - I was noticing the issue because it kept the loop busy and prevented it from terminating. Thanks for proposing the fix and for changing the test.

**Comment by saghul** [comment]
Note that even if we fix that, the handle still needs to be closed in order to properly dispose it.
