### ISSUE TITLE
some thing in uv_write

### ISSUE THREAD

**Issue by lonerwolf** [libuv/libuv#126]
uv_write(tcp,buff,10);
uv_write(tcp,buff + 10,20);

what will happen when first write uv_write(tcp,buff,10); only write 5 bytes?,uv_write can ensure all 10 bytes are send?
how can i know hou many bytes send in write_cb?

**Comment by lonerwolf** [comment]
and when 
uv_write(tcp,buff,10,cb); 
uv_close(tcp);
the cb will be call?

**Comment by lonerwolf** [comment]
@saghul

**Comment by txdv** [comment]
```c
and when 
uv_write(tcp,buff,10,cb); 
uv_close(tcp);
the cb will be call?
if no, uv_wirte_t req =malloc(xxx);
i can't free the req
```

If you close it before libuv can write, the callback will be called with UV_ECANCELED.

**Comment by saghul** [comment]
> uv_write(tcp,buff,10);
> uv_write(tcp,buff + 10,20);
> 
> what will happen when first write uv_write(tcp,buff,10); only write 5 bytes?,uv_write can ensure all 10 bytes are send?

libuv ensures all bytes are written. However, I'm afraid you might be using the API wrong: you need to pass an array of `uv_buf_t` (ech of which contains the length) and the number of buffers, not the total number of bytes.

> how can i know hou many bytes send in write_cb?

All of them. If the callback is called all the bytes have been written (unless there was an error, (status != 0), that is).

I'm going to close this, since it's not an actual issue. Please next time use the mailing list for questions :-)
