### ISSUE TITLE
Add CMake support 

### ISSUE THREAD

**Issue by roxlu** [libuv/libuv#1362]
Building libuv on multiple platform is kind of a time waster atm. E.g. you need to install the right python version; deal with multiple python versions when you have them installed. All this extra work can be fixed by adding support for CMake.  

I created this cmake file that allows you to use the current build system of libuv inside a cmake project using the ExternalProject feature of CMake. This might be helpfull for other people who want to use libuv in a cmake project: https://gist.github.com/roxlu/f21214d1c64c6d2701fb2dc1a33ae091

**Comment by saghul** [comment]
Sorry, but I'm afraid the answer to this is still no. It keeps coming up every so often, and the stance hasn't changed, AFAICT: we already support 2 build systems and are not willing to support more of them.

I'm sorry, but we'll never please everyone, I'm afraid.

**Comment by bnoordhuis** [comment]
FWIW, I'm investigating switching the node.js build system to cmake for $reasons, with the preliminary work available in https://github.com/bnoordhuis/io.js/commits/cmake.

Maybe in the fullness of time libuv can make the switch as well and dump the GYP build.  Almost certainly no sooner than v2, though.

**Comment by roxlu** [comment]
@bnoordhuis that's really good news. I'm sure you'll manage but if you have questions regarding cmake let me know, I've got quite some experience with more complex setups.  

@saghul, @bnoordhuis some other open source projects seem to be somewhat resilient to support cmake too (although most projects are switching to cmake). Biggest argument of not using cmake is "we don't want to add another build system", but truth is, that once you've setup cmake it won't take much time to keep it updated; especially compared to the amount of actual coding you do. 
I also think that it would be perfectly valid to add CMake but communicate that the gyp solution is still the official way to go and cmake is only there for people who want to use cmake. Because as long as there is no cmake file in the libuv repository nobody can actually help maintaining it.

**Comment by saghul** [comment]
@bnoordhuis That's interesting! :-) So, I've used a bit of CMake myself, but I've seen a bunch of libuv CMake scripts which are pretty complex, if we can have something simple we can give it a try.

@roxlu Do you volunteer to write / maintain that? (once written it shouldn't require much maintenance...)

**Comment by roxlu** [comment]
@saghul yes I'm up for that for sure.

**Comment by saghul** [comment]
@roxlu kewl! I see @bnoordhuis wrote some cmake file already, but that doesn't include tests nor static / shared builds AFAIK, feel free to open a PR and let's see!

**Comment by jebej** [comment]
What about this repo: https://github.com/jen20/libuv-cmake

**Comment by saghul** [comment]
Looks pretty complete, thanks for the pointer!

**Comment by skypjack** [comment]
I've just got out of `uvw` (that is a `cmake` based project) the stuff used to import `libuv`.
[This](https://github.com/skypjack/libuv_cmake) is the repository where I put a self contained example.
It shouldn't be difficult to maintain, it's not invasive and... well, it just works.
I'm not sure this is the best way to do that, but I found it pretty easy to use and with a few pros I like definitely.
For the topic is _Add CMake support_, I'd say it matches the requirements and it's worth mentioning it.

**Comment by tay10r** [comment]
Thank you @roxlu for bringing this up! It blows my mind this project doesn't have a CMake build system. I'd also volunteer to maintain this build system, I love CMake!

**Comment by tbms** [comment]
@saghul - we....means everyone?. I guess the support for CMake has been provided ie the work has been done. This is opensource right?

**Comment by saghul** [comment]
@tbms we === the maintainers. It's one thing to write the code, it's a different thing to have to maintain it. The stance on this, however, seems to have changed, so if there is a PR adding support for CMake, which provides equivalent support to gyp / autotools, it will be reviewed!

**Comment by bnoordhuis** [comment]
Let me qualify that a little.  I'm porting node's build system to cmake, porting libuv in the process.  That means not just any CMakeList.txt will do because it needs to play nice with the way node is built.

Then again, I might just maintain libuv's cmake files downstream if it's too much hassle to keep them in sync across two projects.

**Comment by saghul** [comment]
@bnoordhuis That sounds great! Since many have for cmake support over the years, adding it to libuv would "will 2 birds with a single stone" :-)

**Comment by photex** [comment]
o/ Is anyone actively working on this? I might have some bandwidth to help out.

**Comment by justinmk** [comment]
@saghul @bnoordhuis Probably doesn't address the constraints mentioned above, but I'll mention that Neovim now maintains a CMakeLists.txt for libuv, to remove the python dependency.  https://github.com/neovim/neovim/pull/8128/commits/46433f1178878e9264ad71f6c379c12755e39e26

If there's interest in this we will send a proper PR, but I'm also wondering about  @bnoordhuis progress in this regard.

**Comment by bnoordhuis** [comment]
I'm stuck shaving yaks at the moment so I probably won't get around to it until after Node.js 10 has been released (April or May.)

If you want to open a pull request, go ahead.

**Comment by whiteh8** [comment]
Has anyone here ever compiled CMake from source instead of just installing through your OS package manager?

Has anyone ever grep'd through the CMake source?

I find this thread pretty funny to propose that libuv use CMake, because CMake itself has libuv as a dependency!

If you look at how CMake is using libuv, it's pretty awful. There are many issues filed on the CMake project
page on Gitlab related to re-re-re-factoring how they're using libuv. In fact, CMake HEAD is currently broken
due to a libuv compile time error.

This exemplifies the "package-manager-itis" syndrome as well as what Feynmann called "The Computer Disease"

https://benjaminjcousins.wordpress.com/2014/04/01/richard-feynmans-computer-disease/

What me worry about circular dependencies when it's package managers all the way down?
Ain't nobody got time for that. We gotta crush code Bro, move fast and break things, Real Artists Ship, just install a VM, then install Docker, then compile CMake package, which curls and compiles its own libuv, so that you can call CMake to build libuv.

Perhaps I have been in the software game for too many decades and my increased pattern recognition of seeing the same dumb problems re-discovered and "solved" with needless complexity over and over has made me bitter.

Is this progress?

**Comment by skypjack** [comment]
@whiteh8 Well, git uses git and the world is still there despite each pull after all. And you cannot even imagine what the damned GCC does when we are not looking at it...

**Comment by justinmk** [comment]
@whiteh8 Wait until you hear about self-hosting compilers.

**Comment by bnoordhuis** [comment]
@whiteh8 No off-topic ramblings, please.  This is a bug tracker, not your personal blog.

**Comment by bnoordhuis** [comment]
Anyone interested in a cmake build, please check out #1850.  I'm leaving it open for a day or two to solicit feedback.

**Comment by tay10r** [comment]
@bnoordhuis Thanks for tackling this issue! I like the patch you submitted. I added some feedback, but I'm not a contributor or maintainer of libuv so take it with a grain of salt.
