### ISSUE TITLE
Threads implementation

### ISSUE THREAD

**Issue by almosnow** [libuv/libuv#145]
This is more like a question.

(I have UV_THREADPOOL_SIZE set to 128 because reasons...)

As soon as I queue something using uv_queue_work, Activity Monitor on OSX shows that my application is using 129 threads; I guess is because you preallocate UV_THREADPOOL_SIZE threads plus one for the main thread. This happens even if I only queue one thread with uv_queue_work and then, when all threads are complete, they stay "open"; I can continue running the program for a long time doing other stuff and never queueing another job, and the whole time the program will show that is using 129 threads.

I don't see this much of an issue as I'm pretty sure that it doesn't incur on a performance/memory hit (well, there's a 1024K object somewhere that never gets released whenever I use threads, but I don't care). But still I'd like to know, why did you choose to implement threads this way? Is there any way to "release" them when you don't need them?

Regards.

**Comment by bnoordhuis** [comment]
Right now, there isn't.  The reason for the fixed size is that it's fairly expensive to spin up and tear down threads.

I have some old work sitting in a branch that implements a dynamic thread pool but performance was never really satisfactory.  To make a dynamic thread pool perform as well as a static one, you need what is essentially perfect foresight - knowing when to spin up a new thread before it's actually needed - but the best you can attain in the real world is an adaptive approach that gets it right just some of the time.

Having said that, I will probably revisit the current implementation someday because it clearly isn't ideal.  Hope that helps!

**Comment by almosnow** [comment]
Thanks @bnoordhuis. Over and out :smile:

**Comment by saghul** [comment]
Also, FWIW, you may want to monitor this discussion: https://github.com/libuv/leps/pull/4
