### ISSUE TITLE
test: condvar tests look problematic

### ISSUE THREAD

**Issue by davisjam** [libuv/libuv#1714]
I just opened PR #1713 to improve the testing of `uv_cond_timedwait` (`test/test-condvar.c`).
While I was in there, I became somewhat confused about how the condvar tests work.

It looks like the intended behavior is as follows:

1. Spawn a worker to signal `c->cond` and then wait on `c->cond`.
2. In the main thread, wait on `c->cond` and then signal on `c->cond`.

However, to prevent a possible deadlock due to missed signals:
- `condvar_signal` sets a flag as a permanent record.
- `condvar_wait` checks a flag for missed signals before waiting.

The use of these flags mean that the condvar tests could pass *without `uv_cond_wait` (or `uv_cond_timedwait`) ever being invoked*. This strikes me as problematic.

If I understand the current behavior correctly, here is an example schedule in which `uv_cond_wait`/`uv_cond_timedwait` are never called.

| worker | main |
|---------|--------|
| signal and set flag | |
|                               | wait, see flag, and return |
|                               | signal and set flag |
| wait, see flag, and return | |

If my description looks accurate, I would be happy to try a fix.

**Comment by bnoordhuis** [comment]
> The use of these flags mean that the condvar tests could pass without uv_cond_wait (or uv_cond_timedwait) ever being invoked.

That sounds about right.  The logic in the test looks correct to me - acquire mutex, check predicate, enter wait state - but yes, the wait call is skipped when the predicate is satisfied.

I suspect from a quick glance at the code that this mostly affects the condvar_1 test.  condvar_2 and condvar_3 still exercise the wait calls because they pause .1s before they start signalling.
