### ISSUE TITLE
Use vfork for creating new processes

### ISSUE THREAD

**Issue by DemiMarie** [libuv/libuv#1715]
To avoid blocking the event loop when spawning a process from a parent with a big RSS, it is necessary to call `vfork()` instead of `fork()`.

**Comment by saghul** [comment]
We discussed this a couple of years ago: https://github.com/libuv/libuv/pull/141

I guess the door still might be open for adding a new flag, but the default behavior should continue to be `fork()`.

**Comment by bnoordhuis** [comment]
Yes, `vfork()` isn't an option, except as an opt-in flag.  If you're worried about https://github.com/nodejs/node/issues/14917, mark memory with `madvise(MADV_DONTFORK)`.

**Comment by vtjnash** [comment]
I have a patch for this (well, essentially for it's equivalent `clone CLONE_VM | CLONE_VFORK | SIGCHLD`), since it is much faster and seems to work well on linux. I plan to make a PR for https://github.com/vtjnash/libuv/commit/a759d4023cd1379f045548db1a3432d842e6fa85 once some of my other PRs get out of my queue.

**Comment by bnoordhuis** [comment]
https://github.com/nodejs/node/issues/14917#issuecomment-361001709 - patches still welcome but I'm closing this out because I'm convinced by now that `madvise(MADV_DONTFORK)` is a better fix than vfork/clone, but it needs to be done by the application, not libuv.
