### ISSUE TITLE
failing test (tcp_writealot)

### ISSUE THREAD

**Issue by crusader-mike** [libuv/libuv#1744]
* **Version**: 1.19.1
* **Platform**: CentOS 7

I've downloaded and built libuv according to instructions (with extra `git reset --hard v1.19.1` call) -- in `make check` one test (tcp_writealot) has failed. I ran `make check` about 5 times after that -- they all succeeded.

**Comment by bnoordhuis** [comment]
Some tests are timing-sensitive by nature.  If you run them on a slow or busy system, they can be flaky.  Not much we can do about that.

**Comment by crusader-mike** [comment]
No probs. I thought you may want to be aware of this.

**Comment by dod38fr** [comment]
Hi

I've run on a [similar issue](https://buildd.debian.org/status/fetch.php?pkg=libuv1&arch=mipsel&ver=1.34.2-1&stamp=1581089155&file=log) on Debian mipsel build system where `tcp_writealot` test fails on timeout.

Could you setup a test option (or an environment variable) to disable time-sensitive tests ? So that only (more) robust tests would be run on Debian (or other) build systems ? 

All the best

Dod (for Debian)

**Comment by saghul** [comment]
This issue is 2 years old, please open a new one since many things have changed and it’s better to start fresh :-)
