### ISSUE TITLE
Windows single core 100% cpu lockup on electron, libuv related?

### ISSUE THREAD

**Issue by gshively11** [libuv/libuv#1757]
* **Version**: 1.13.1
* **Platform**: Windows 7 (single core)

Hey libuv, I'm investigating a bug in electron that intermittently locks up node scripts on single core windows machines when performing asynchronous actions. Could you please read [this issue](https://github.com/electron/electron/issues/12026) and maybe chime in on what impact my tweak to libuv might have? I'm basically stabbing in the dark since I don't really understand these projects all that well and would love some expert help. Thanks!

**Comment by bnoordhuis** [comment]
Your analysis looks plausible: something in the way electron integrates node.js and libuv.  If it also happened in plain node.js + libuv I'm sure we'd have received bug reports about that.

I don't know electron's code base well enough to really comment but bumping the maximum number of threads is probably harmless.

If it turns out the bug is in libuv, please comment and I'll reopen the issue.
