### ISSUE TITLE
First io.js Build Working Group meeting, invitation for involvement by libuv collaborators

### ISSUE THREAD

**Issue by rvagg** [libuv/libuv#186]
Issue with details is here: https://github.com/iojs/build/issues/43

While we're mainly io.js focused, we're also supporting libuv in parallel with our CI infrastructure and are keen to make sure this project is first-class in everything we do. libuv has separate concerns and a different list of platforms it wants to be able to support. If there's anyone who's already involved in libuv and is interested in joining the efforts to improve and better integrate the CI infrastructure then come join us!

**Comment by bnoordhuis** [comment]
I commented on iojs/build#43 but for the record, I can represent libuv if needed.  Yours truly or @piscisaureus are probably the most obvious choices but if you want to get involved, @saghul, I'm more than happy to pass on my seat to you. :-)

**Comment by saghul** [comment]
Hi folks, sorry for the delay, I've been sick for the past entire week :-S Since I'm not employed to work on libuv, and I'm not sure how much time I can devote to a build WG, I think either @bnoordhuis or @piscisaureus are better suited to be there. I'd like to be in the first meeting, however, just to see where things are headed and maybe reevaulate :-)

Thanks for the offer, Ben, much appreciated.
