### ISSUE TITLE
PR #1843 broke IPC with older versions on Windows

### ISSUE THREAD

**Issue by bzoz** [libuv/libuv#1922]
* **Version**: 1.20 vs 1.21
* **Platform**: win

https://github.com/libuv/libuv/pull/1843 IPC communication is not backwards compatible with previous libuv versions, as seen in https://github.com/nodejs/node/issues/21671. For example, in frame header [1.21 uses 32bits for length](https://github.com/libuv/libuv/blob/v1.21.0/src/win/pipe.c#L66) and [1.20 uses 64bits](https://github.com/libuv/libuv/blob/v1.20.0/src/win/pipe.c#L73), raw data flag was changed [from 1](https://github.com/libuv/libuv/blob/v1.20.0/src/win/pipe.c#L66) [to 0](https://github.com/libuv/libuv/blob/v1.21.0/src/win/pipe.c#L61). 

This looks like it can be fixed to be compatible with previous libuv versions

/cc @piscisaureus

**Comment by piscisaureus** [comment]
My bad, I didn't consider that users would use IPC to communicate between different versions of node.

I'm not sure what to do about it exactly. 
I think it's possible to revert to the old protocol, but t think it's *not* possible to fix it in a way such that a future version of libuv/node can speak either protocol, because there is no way to know/negotiate what protocol versions the peer supports.

Let me at least describe the differences precisely.
(For the old protocol, I'm using different nomenclature than the source code).

### Old protocol

```c
frame {
  header {
    // Flag bits:
    // * 0x01: FRAME_CONTAINS_DATA
    // * 0x02: FRAME_CONTAINS_SOCKET
    // * 0x04: SOCKET_IS_A_TCP_CONNECTION (otherwise it is a tcp server)
    uint32_t flags;
    uint32_t padding;
    // * `data_length` is ignored when FRAME_CONTAINS_DATA is not set.
    // * A value greater than UINT32_MAX may lead to a crash.
    uint64_t data_length;
  }
  
  // * `socket_info` is only present when FRAME_CONTAINS_SOCKET is set.
  socket_info? {
    WSAPROTOCOL_INFOW protocol_info. //   628 bytes
    uint32_t delayed_error;          //     4 bytes
  }                                  // + 632 bytes total
  
  // `data` is only present when FRAME_CONTAINS_DATA is set.
  uint8_t data?[header.data_length];
}
```

### New protocol

```c
data_frame {
  header {
    uint32_t type = 0; // DATA_FRAME
    uint32_t payload_length;
  }
  uint8_t data[payload_length];
}

xfer_frame {
  header {
    uint32_t type = 1; // XFER_FRAME
    uint32_t payload_length = 636;
  }
  payload {
    WSAPROTOCOL_INFOW protocol_info. //   628 bytes
    uint32_t delayed_error;          //     4 bytes
    uint32_t flags;                  //     4 bytes
  }                                  // + 636 bytes total
}
```

**Comment by bzoz** [comment]
I was thinking about reverting to the old protocol version. New protocol would be semver-major.
