### ISSUE TITLE
A better abort?

### ISSUE THREAD

**Issue by abrownsword** [libuv/libuv#1948]
My libuv-based program is throwing an abort from inside of the libuv run loop, and all I get is "Aborted." printed to stderr.  A quick search of the libuv source shows that there are many calls to abort().  It would be most helpful if the abort was accompanied by a message, at least in a debug build (but preferably in all builds since this is code that is outside of the normal execution flow).  Not all environments have a debugger that can readily assist in figuring this out automatically.

Each abort call site could include a text message to send to stderr, even better would be to have a formatted one that includes parameters related to the failure.  At a minimum it ought to include the __FILE__ and __LINE__ information from the abort call site to assist in determining where it is coming from.  Another alternative would be to have an abort function vector that the application can override, but this too should take parameters.

**Comment by bnoordhuis** [comment]
What you're asking is a lot of work (there are over 150 abort calls) and in most cases there isn't anything libuv can report except "the impossible happened."  Often it's memory corruption caused by the application or an unusual environment where libuv can't run.

What might be a middle road is to turn statements like this:
```c
if (f(x) == 42)
  abort();
```
Into this:
```c
CHECK(f(x) != 42);
```
Where `CHECK()` expands to something like this:
```c
do {
  if (!(f(x) != 42)) {
    fprintf(stderr, "%s:%d: CHECK(%s) failed.\n", __FILE__, __LINE__, "f(x) != 42");
    abort();
  }
} while (0);
```
Except that at some call sites it won't be safe to call fprintf() so blindly converting everything won't work.

> Another alternative would be to have an abort function vector that the application can override, but this too should take parameters.

You can always interpose abort(), you don't need libuv assistance for that.

**Comment by abrownsword** [comment]
Most projects I've worked on include at a minimum and FILE/LINE information, which needs to be done at compile time, and it is always a significant win.  Understood that it is a non-trivial effort to achieve, but it would be a worthwhile usability improvement.

**Comment by freeekanayaka** [comment]
I found a few cases where libuv calls abort() because the memory was exhausted (e.g. ```uv__realloc``` returning ```NULL``). Does libuv qualify this as  "the impossible happened"? I would have expected libuv to handle memory exhaustion fine, otherwise it's hard to use it to build programs that continue to run even in the case they run out of memory (think embedded devices).

Any opinion from upstream?

**Comment by bnoordhuis** [comment]
> Does libuv qualify this as "the impossible happened"?

@freeekanayaka Not exactly, but as unlikely enough that it equals "impossible" when you round it down. :-)

I know the abort sites you mention. If they're an issue - or if you have reasonable cause to believe they might become an issue in your project - we can look into bubbling up the allocation failures.

**Comment by freeekanayaka** [comment]
@bnoordhuis thanks, I think it's indeed just a handful of spots in the libuv code that have this behavior, so adding graceful handling logic should not be too hard. For now I noticed this while running unit tests that harden a project that uses libuv, ideally I'd like my process to be able to survive to out-of-memory errors (as they might be transient). However, that's just a wishlist, I don't think I have **yet** a real-world use case where this would matter.

**Comment by sam-github** [comment]
There's more than a handful, grep for "strdup" and see how many have failure checks.

My 2 cents:

I used to think that not checking for malloc failure or using wrappers that abort on malloc failure was just poor coding practice, I don't anymore.

When I worked on crypto toolkits that had to run on devices like Palm or Blackberry, we had to make sure they returned ENOMEM instead of leaking memory or mem faulting when malloc() failed. We did this by running all our unit tests in a mem fail harness where we would run the test after setting malloc 1 to fail. After the test, if the failing malloc was hit, we would assert ENOMEM was returned, AND that all allocated memory was released. If the failing malloc did not get hit, we would assert the test passed. Repeat again failing malloc 2, 3, ..., until we didn't fail any mallocs and asserted that the unit test passed.

What we found is that no one's code passed. Ever. Even code that was written by experienced devs knowing it would go in the malloc fail test harness, and that superficially appeared to check the return of every allocation for failure would have problems under test. Mostly it was a result of not cleaning up after intermediate operations failed, but all kinds of fun stuff happened.

So now I've switched my view, I'm convinced that code that doesn't actually test for low-memory conditions shouldn't pretend that it handles those conditions.

**Comment by freeekanayaka** [comment]
@sam-github yeah I'm using pretty much the same unit-testing strategy for the code I am writing, that's how I surfaced this behavior.

**Comment by abrownsword** [comment]
Handling memory constraints at the point of abort is simply the wrong way to handle constrained memory.  If you get to that point, your strategy has failed and you need to abort (with as much useful info as possible so the developer can figure out why and fix it).

**Comment by freeekanayaka** [comment]
@abrownsword well, it depends, the fact that you ran out of memory might not be fatal, iow the malloc failure might be "benign" and your program might still be able to do its job without aborting (for example you were malloc'ing a cache as optimization to re-use some results, but if malloc fail is not a big deal and you'll go on without that optimization).

It's just a lame example to get the point across: malloc returning NULL might not be fatal to your program.

**Comment by freeekanayaka** [comment]
I'm pretty sure SQLite tolerates malloc failures when it tries to allocate new memory for disk page caches (it has its own caching independent from the OS, like many database systems). That behavior is probably very handy in autonomous systems.

**Comment by abrownsword** [comment]
That's because SQLite has a very specific strategy for handling those situations, and it was carefully designed in from the get-go.  That's not the "point of abort" that I mentioned, that is at the point of malloc.  It is a somewhat subtle distinction, but an important one -- the caller of malloc did not throw up its hands and panic, it dealt with the failure.  As sam observed above, _most_ code is not written to gracefully handle a memory allocation failure (and even if they author thinks they did it, did they test it well enough?).  So either you've planned your response to the allocation failure, or you wrote something into your code that basically says "I give up".  My point was that trying to save the day after "I give up" is pretty much a lost cause and the further you get from that point before you crash, the harder it is to understand what failed.

I'd also wager that SQLite's memory strategy goes a lot deeper than just handling failed mallocs when trying to allocate new cache pages.  If you're that low on memory, either something else is about to go sideways or you've been _very_ careful in how you write your code so that its allocation behaviour is very good.  I've written a large amount of code like that (for decades), and it doesn't happen by accident.  Most code written for the Posix and Windows environments is _extremely_ lax in its memory discipline, especially in C++ or other higher level languages, and as a result when memory fails to allocate, the process is going sideways in a hurry and you're best off terminating immediately with a lot of useful information for the developer stuck debugging the problem.

To tie this back around to why I created this issue, it would be useful to developers if, when libuv gives up, it tells us more than "Aborted."

**Comment by freeekanayaka** [comment]
Yeah I think we are on the same board. I agree that for the vast majority of programs, the behavior of aborting as soon as malloc returns NULL is the most appropriate, because those programs are not designed to cope with the failure, so better to bail out immediately, where if you have the most useful context.

My point is that for programs that actually do have the design goal of handling failed mallocs gracefully and are tested properly, then libuv fails short. So my wish would be to have libuv to keep the current behavior of calling abort() upon malloc returning NULL, with additional information to help debugging, but also to offer optional behavior where instead UV_ENOMEM is returned and propagated up to the user code, which can choose what to do.

**Comment by abrownsword** [comment]
I would much rather have the improved abort I asked for originally.  IMO the engineering and testing effort of having a switch and returning an error isn’t worth it... if you’re program lets it get to that point, you’re toast.  Better to have an emergency callback that tries to free memory instantly so whatever was happening at that point doesn’t get left half done.  But that’s a library design decision and it’s not my library.   :)

**Comment by freeekanayaka** [comment]
IMO a library should generally leave the choice to user code. Like the OS and libc do.

**Comment by abrownsword** [comment]
Yes, just as long as they don't promise one thing and deliver another.
