### ISSUE TITLE
Inline functions

### ISSUE THREAD

**Issue by emilbayes** [libuv/libuv#1975]
Hi!

I was wondering why most of the functions in https://github.com/libuv/libuv/blob/e4087dedf837f415056a45a838f639a3d9dc3ced/src/uv-data-getter-setters.c are not inline. Is there an advantage to using these over just accessing the data member directly? (which is documented to be public)

**Comment by addaleax** [comment]
Hi! Yes, this is intentional. Some advantages are that these functions can maintain ABI stability indefinitely (or at least as long as the corresponding fields exist), and that they are easier to use from FFI libraries.

**Comment by emilbayes** [comment]
Ah ok, I don't know if this is off topic, but would making them `extern inline` keep the ABI stable? I know this is too late now, but imagine an alternate reality 😅

**Comment by addaleax** [comment]
@emilbayes I’m not sure I understand – the point of having these functions is that they don’t get inlined, since once a library user inlines these functions into their (generated) code, they are back to depending on the exact struct layout (which still stable across a single libuv major version, but that’s the situation from before).

**Comment by emilbayes** [comment]
Ah I understand now. My questions was vauge because I had my specific use-case in mind which statically links libuv. In that case ABI stability is moot, but that's where I'd have like inlining. But I guess I can just access the fields on the struct. Thank you for your replies
