### ISSUE TITLE
uv timer performance (heap vs rbtree)

### ISSUE THREAD

**Issue by heiher** [libuv/libuv#2072]
Simulation bench test (i7-7660U CPU @ 2.50GHz):
```
time ./rbtree-bench < data

real    0m1.345s
user    0m0.910s
sys     0m0.433s
time ./heap-bench < data

real    0m1.806s
user    0m1.403s
sys     0m0.399s
```

Benchmark repo: https://github.com/hevx/uv-timer-bench

**Comment by heiher** [comment]
> See commit [f17c535](https://github.com/libuv/libuv/commit/f17c535b73a888b0efca816b00361ea21cdc94be) for rationale:
> 
> > The most common operation that libuv performs on timers is looking up the first timer to expire.  With a red-black tree, that operation is O(log n).  With a heap, it's O(1).
> 
> There's a million_timers benchmark in test/ where the heap considerably outperformed the old RB tree.
> 
> No doubt there are access patterns where an RB tree comes out on top but libuv optimizes for the common case.

We can use leftmost cached rbtree, that operation is O(1) too. :)
https://github.com/hevx/uv-timer-bench/blob/master/rbtree/hev-rbtree-cached.h#L21

**Comment by heiher** [comment]
benchmark million_timers results:
**heap:**
```
1..1
ok 1 - million_timers
# 10.20 seconds total
# 0.85 seconds init
# 9.15 seconds dispatch
# 0.20 seconds cleanup
```

**rbtree linux:**
```
1..1
ok 1 - million_timers
# 10.20 seconds total
# 2.55 seconds init
# 7.45 seconds dispatch
# 0.20 seconds cleanup
```

**Comment by bnoordhuis** [comment]
Amusing they have the same running time, but split differently. Guess that's O(log n) for you.

I looked at your benchmark code but I don't know how representative it is of real-world usage. Neither is million_timers, for that matter; I won't claim it's a great benchmark.

The common case for libuv is up to a few thousand timers (and often just one or a few), with the vast majority getting canceled before they expire. Think tracking TCP connections for inactivity.

I'd argue a heap will generally perform better there because it's a "flatter" structure than a red-black tree. Better constant costs, less pointer chasing.

Also bear in mind that the current heap implementation is battle-tested. For it to be replaced, its replacement would have to be significantly better, not just a little better.

> We can use leftmost cached rbtree, that operation is O(1) too. :)

I considered doing that when I rewrote the timers implementation because it was the least amount of work. :-)

But for the reasons mentioned above and the fact that caching is slightly inelegant, I decided to just rip it out entirely and rewrite it as a heap.

**Comment by heiher** [comment]
Excellent!

benchmark million timers start/stop results:
**heap:**
```
1..1
ok 1 - million_timers
# 4.62 seconds total
# 0.82 seconds init
# 3.62 seconds cancel
# 0.18 seconds cleanup
```
**rbtree linux:**
```
1..1
ok 1 - million_timers
# 3.06 seconds total
# 2.70 seconds init
# 0.17 seconds cancel
# 0.18 seconds cleanup
```
**Patch**
```
diff --git a/test/benchmark-million-timers.c b/test/benchmark-million-timers.c
index 60a308be..1c3ec31d 100644
--- a/test/benchmark-million-timers.c
+++ b/test/benchmark-million-timers.c
@@ -24,12 +24,10 @@
 
 #define NUM_TIMERS (10 * 1000 * 1000)
 
-static int timer_cb_called;
 static int close_cb_called;
 
 
 static void timer_cb(uv_timer_t* handle) {
-  timer_cb_called++;
 }
 
 
@@ -42,8 +40,8 @@ BENCHMARK_IMPL(million_timers) {
   uv_timer_t* timers;
   uv_loop_t* loop;
   uint64_t before_all;
-  uint64_t before_run;
-  uint64_t after_run;
+  uint64_t before_cancel;
+  uint64_t after_cancel;
   uint64_t after_all;
   int timeout;
   int i;
@@ -61,9 +59,10 @@ BENCHMARK_IMPL(million_timers) {
     ASSERT(0 == uv_timer_start(timers + i, timer_cb, timeout, 0));
   }
 
-  before_run = uv_hrtime();
-  ASSERT(0 == uv_run(loop, UV_RUN_DEFAULT));
-  after_run = uv_hrtime();
+  before_cancel = uv_hrtime();
+  for (i = 0; i < NUM_TIMERS; i++)
+    ASSERT(0 == uv_timer_stop(timers + i));
+  after_cancel = uv_hrtime();
 
   for (i = 0; i < NUM_TIMERS; i++)
     uv_close((uv_handle_t*) (timers + i), close_cb);
@@ -71,14 +70,13 @@ BENCHMARK_IMPL(million_timers) {
   ASSERT(0 == uv_run(loop, UV_RUN_DEFAULT));
   after_all = uv_hrtime();
 
-  ASSERT(timer_cb_called == NUM_TIMERS);
   ASSERT(close_cb_called == NUM_TIMERS);
   free(timers);
 
   fprintf(stderr, "%.2f seconds total\n", (after_all - before_all) / 1e9);
-  fprintf(stderr, "%.2f seconds init\n", (before_run - before_all) / 1e9);
-  fprintf(stderr, "%.2f seconds dispatch\n", (after_run - before_run) / 1e9);
-  fprintf(stderr, "%.2f seconds cleanup\n", (after_all - after_run) / 1e9);
+  fprintf(stderr, "%.2f seconds init\n", (before_cancel - before_all) / 1e9);
+  fprintf(stderr, "%.2f seconds cancel\n", (after_cancel - before_cancel) / 1e9);
+  fprintf(stderr, "%.2f seconds cleanup\n", (after_all - after_cancel) / 1e9);
   fflush(stderr);
 
   MAKE_VALGRIND_HAPPY();
```
