### ISSUE TITLE
build: out-of-tree autotools build fails `make distcheck`

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#2199]
Depends on #2198, otherwise you won't get this far.

Probably related to #2099 somehow so cc @vtjnash.
```
$ mkdir -p out/auto && cd out/auto && sh ../../autogen.sh && ../../configure && make distcheck
# ...
configure: creating ./config.status
config.status: creating Makefile
config.status: creating libuv.pc
config.status: linking ../../test/fixtures/empty_file to test/fixtures/empty_file
config.status: error: ../../test/fixtures/empty_file: file not found
make: *** [distcheck] Error 1
```
(Apologies if this has been reported already. I remember discussion but I can't find it back.)

**Comment by vtjnash** [comment]
Ah, this was a confusing one to investigate since autotools tries repeatedly to do the right thing, and then would mysteriously fails when . The problem appears to be that we're telling autotools it must distribute the exact contents of the entire `test/` folder, which makes it rather confused (and order-dependent).

**Comment by vtjnash** [comment]
Pushing past that, I think this later (related to #2099) uncovers inconsistencies in the uv_fs_copyfile behaviors when the source is a link.

For UV_FS_COPYFILE_FICLONE on macos, it might copy the link instead of the target.

Also, when copying link permissions, on macos the copyfile call appears to take them from the link (permitting the fs_copyfile test to pass), while on linux, the permissions are copied from the target (as it looks like `cp -p` also does), causing the test to fail (distcheck makes the directory files read-only, so an existing file can only be replaced atomically through a tempfile copy + rename, and not by opening the file directly for re-writing, as libuv currently attempts to do).
