### ISSUE TITLE
why not use socketpair to implement async?

### ISSUE THREAD

**Issue by b-xiang** [libuv/libuv#2223]
Now uv_async_t must be initialized before uv_loop_t run. Why not use socketpair? We can new a new uv_async_t, and send to loop by socketpair.So we can post any uv_async_t  to loop.
**### Why?Thanks!**

**Comment by saghul** [comment]
There are more efficient ways than using socketpair. Look at how it's currently implemented: https://github.com/libuv/libuv/blob/v1.x/src/unix/async.c#L157 we use eventfd on Linux if possible, otherwise pipe() but saving a fd, etc.

You can initialize the async handle whenever you want, from the loop thread that is, so I'm not sure I fully understand that part of the question.

**Comment by b-xiang** [comment]
Now use async, we must init async before loop run. But sometimes, we  don't known how many asyncs do we need, so I need new a async when I need. Because QUEUE_INSERT_TAIL is not thread safe, I can't do this.
If use socketpair,I can new a async and set it to pAsync,   then I write pAsync to socketpair, in loop thread I  read this pAsync, so I post the pAsync between two threads safely.

**Comment by bnoordhuis** [comment]
You mean write the address of the handle to the write end of the socketpair and have the event loop thread read it from the read end?

The obvious problem with that approach is that socketpairs have finite (bounded) queues. When it's full, you either have to block until the other thread clears it or you lose the message.

**Comment by b-xiang** [comment]
Some os don't support SO_REUSEPORT. So I must bind in one thread, after accept client ,I put the client to other thread. In this way,how can I do?

**Comment by bnoordhuis** [comment]
I don't get how that's related... for general questions, please turn to https://github.com/libuv/help.
