### ISSUE TITLE
win: bug: A number of tests failure when run under Windows OS

### ISSUE THREAD

**Issue by fpiette** [libuv/libuv#2274]
[Test Failures FPiette.txt](https://github.com/libuv/libuv/files/3103894/Test.Failures.FPiette.txt)
Hello,

I build libuv with MSVC2010 using the source code downloaded from GitHub today.
A number of tests failed (See attache file for details):
    not ok 26 - dlerror
    not ok 37 - fs_copyfile
    not ok 54 - fs_event_watch_file_twice
    not ok 86 - fs_readdir_file
    not ok 93 - fs_scandir_file
    not ok 163 - pipe_connect_to_file
    not ok 179 - poll_bad_fdtype
As fas as I can see, the failure are caused by the file or directory paths involved in the test. There are constant defined such as:   
    const char* path = "test/fixtures/load_error.node";
Under Windows OS, the path delimiter character is not the slash but the back-slash.
In my opinion, all such constants should replace the path delimiter by a new constant, defined as "/" for Linux and the likes and "\\" for all Windows platforms.

**Comment by bnoordhuis** [comment]
Common misconception but forward slashes are legal path delimiters on Windows.

Since you're referring specifically to the dlerror test, that test checks whether `uv_dlopen()` copies the path verbatim into the error message.

Can you investigate why so many tests fail for you, e.g. by adding some printf statements right before the failing asserts?

Also, are you testing master or the v1.x branch? The v1.x branch is used for releases and is what you should normally use.

**Comment by ptlomholt** [comment]
Make sure you run the tests from the root of the libuv folder - the one that has 'test' as a subfolder. (I  get the same errors if I run them from any other folder...)

@bnoordhuis : this appears to be a common mistake, is there anything that can be done to avoid it, like using absolute path names (via some makefile magic) in the test code?
