### ISSUE TITLE
Contribution Learning Materials

### ISSUE THREAD

**Issue by poplinnilpop** [libuv/libuv#2281]
In a general since, what would be the table of contents for learning materials to be a useful contributor for libuv, e.g. things you must know about?

**Comment by saghul** [comment]
In general I'd say *wanting* to do it is the most important part. libuv is organized quite nicely so you may not need to touch many places to add a feature or fix an existing problem in a specific area.

I'd recommend taking a look at this: http://docs.libuv.org/en/v1.x/design.html and then starting the user guide: http://docs.libuv.org/en/v1.x/guide.html Now, the guide hasn't gone through a lot of scrutiny so it may contain mistakes! All the mistakes you find and problems you ran into which can be fixed in the guide would be great starting contributions.

**Comment by cjihrig** [comment]
I don't think there is anything left to do here, so I'm going to close this issue out. Feel free to follow up with any questions though.
