### ISSUE TITLE
feature request: add uv_fs_lseek()

### ISSUE THREAD

**Issue by cjihrig** [libuv/libuv#2378]
Idea: add `uv_fs_lseek()`, implemented in terms of [`lseek64()`](https://linux.die.net/man/3/lseek64) and [`_lseeki64()`](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/lseek-lseeki64?view=vs-2019).

Motivation: General purpose file system stuff. My specific use case is to implement [`__wasi_fd_seek()`](https://github.com/CraneStation/wasmtime/blob/master/docs/WASI-api.md#__wasi_fd_seek), [`__wasi_fd_tell()`](https://github.com/CraneStation/wasmtime/blob/master/docs/WASI-api.md#__wasi_fd_tell), and [`__wasi_whence_t`](https://github.com/CraneStation/wasmtime/blob/master/docs/WASI-api.md#__wasi_whence_t-uint8_t) in terms of libuv.

I volunteer to do the work.

**Comment by bnoordhuis** [comment]
An oldie but a goodie on why lseek is a bad idea: https://github.com/joyent/libuv/pull/664

It's been six years but I haven't changed my mind. :-)

**Comment by cjihrig** [comment]
That's unfortunate, but OK. Thanks for the link.

**Comment by vtjnash** [comment]
Since this function is required by the libuv test suite, I'd be in favor of adding it. Despite the reasons given that it may be a bad idea to actually use it in complicated multi-threaded code, I hypothesize that most IO code (esp. code that wants to make use of this) is very straightforward.

OT: fwiw, the last statement in that thread ("Posix operating systems won't let you seek past the end of file") is false (as is the statement it was responding to). The actual behavior is to do exactly as told and sets the position to the given value. From the top of the linux man page: "lseek() allows the file offset to be set beyond the end of the file".
