### ISSUE TITLE
Retrieve disk information

### ISSUE THREAD

**Issue by sagitsofan** [libuv/libuv#2386]
* **Version**: v1.30.1
* **Platform**: Both

Inside Node there is no api to get the disk information, for example: total, used & available storage on a specific disk.

We would like that in Libuv you will add this feature, and in Node we will expose it inside the `fs` api - https://nodejs.org/api/fs.html
Desirable implementation code on Node: 

`const diskInfo = fs.diskInfoSync("C:")`

`diskInfo.total` - disk total size.
`diskInfo.used` - how much of the drive is used.
`diskInfo.available` - how much free space have left.

https://github.com/nodejs/node/issues/10745

**Comment by cjihrig** [comment]
@libuv/collaborators what do you think? The original request from Node is for something like `statvfs(3)`. If we implement it in libuv, I believe it will be a little different because of Windows. If we want to add it to libuv, I'm OK with doing the work.

**Comment by bnoordhuis** [comment]
I'm okay with adding it. One issue I see is that `available` on file systems supporting compression might be meaningless but that's not really a libuv issue if the data comes directly from the operating system.

You probably want `statfs(2)` instead of `statvfs(3)`, the latter doesn't report all the relevant data.

**Comment by saghul** [comment]
+1. I guess we can have some `uv_statfs_t` which we fill-in as we can (on Windows specially).
