### ISSUE TITLE
Windows tty `uv_reset_tty_mode` problem

### ISSUE THREAD

**Issue by Escapingbug** [libuv/libuv#2430]
* **Version**: master (according to source code)
* **Platform**: Windows 1903

As the implementation of function `uv_tty_reset_mode` in [src/win/tty.c](https://github.com/libuv/libuv/blob/master/src/win/tty.c#L2227) implies:

```
int uv_tty_reset_mode(void) {
  /* Not necessary to do anything. */
  return 0;
}
```

This causes problem when the program assumes this will reset the mode. One instance I've found is [this issue of neovim](https://github.com/neovim/neovim/issues/10668). Neovim calls this function to reset mode. So, when I'm using powershell, after neovim's quitting, python shell or any other interaction of normal mode will not work.

However, I've found that this actually only applies to powershell, when I'm using cmd, this works without any problems. But I think we should fix this in some way so it works under powershell as well.

**Comment by bnoordhuis** [comment]
That sounds like a legitimate bug. I don't have a good way to test but can you check if this patch helps?
```diff
diff --git a/src/win/tty.c b/src/win/tty.c
index 07436dc8..d49451da 100644
--- a/src/win/tty.c
+++ b/src/win/tty.c
@@ -2253,7 +2253,13 @@ void uv_process_tty_connect_req(uv_loop_t* loop, uv_tty_t* handle,
 
 
 int uv_tty_reset_mode(void) {
-  /* Not necessary to do anything. */
+  DWORD mode;
+  int fd;
+
+  mode = ENABLE_ECHO_INPUT | ENABLE_LINE_INPUT | ENABLE_PROCESSED_INPUT;
+  for (fd = 0; fd <= 2; fd++)
+    SetConsoleMode(uv__get_osfhandle(fd), mode);
+
   return 0;
 }
 
```
cc @libuv/windows

**Comment by erw7** [comment]
Before https://github.com/libuv/libuv/commit/6ad1e81547c83f9fe7c5a806b6b282642e8d3bca, `WINDOW_BUFFER_SIZE_EVENT` was used for the `SIGWINCH` signal. But now `WINDOW_BUFFER_SIZE_EVENT` is no longer used everywhere. Therefore, it is not necessary to enable `ENABLE_WINDOW_INPUT`. I think that the code related to `SetConsoleMode()` can be removed from `uv_tty_set_mode()`.

**Comment by bzoz** [comment]
I have a PR to partially bring back the old SIGWINCH method: https://github.com/libuv/libuv/pull/2381.

As for this: Ben's patch LGTM

**Comment by erw7** [comment]
> As for this: Ben's patch LGTM

There is no guarantee that fd 0 to 2 is `CONIN$`. I think we should get the handle from `CONIN$` in the same way as src/win/tty.c:#L160-L166.

https://github.com/libuv/libuv/blob/b571851e6e3040d009a971f0bebe010426bfcf87/src/win/tty.c#L160-L166

In the first place, `ReadConsoleInputW()` is used for reading when `UV_HANDLE_TTY_RAW`. `ReadConsoleInputW()` is not affected by `ENABLE_ECHO_INPUT`, `ENABLE_LINE_INPUT`, `ENABLE_PROCESSED_INPUT`. Therefore, even if #2381 is merged, there is no need to drop `ENABLE_ECHO_INPUT`,` ENABLE_LINE_INPUT`, `ENABLE_PROCESSED_INPUT`. The root cause of this problem is that they are dropped when not needed.
