### ISSUE TITLE
uv_pipe_connect and file path truncation

### ISSUE THREAD

**Issue by mhdawson** [libuv/libuv#244]
While debugging an issue in Node I narrowed it down to a call in uv_pipe_connect where the issue was that a path was getting truncated.  I see from the docs here http://docs.libuv.org/en/latest/pipe.html that is documented to do this.

However, I wanted to ask if it would be better to have it return ENAMETOOLONG instead of simply truncating.  In my case the truncation resulted in various different errors in different tests, none of which suggested it was because the path was too deep.  Our jenkins jobs end up generating deep paths and so tests would fail there, but when we tried to recreate in our own directories everything would pass.  

I think it would have been much more useful if the method returned an ENAMETOOLONG instead of ENOENT or EADDRINUSE as we were seeing depending on what effect the truncation had.  It would also avoid un-intended behaviour were you end up using the same pipe instead of separate ones because your original paths have been truncated.

**Comment by saghul** [comment]
Hi Michael!

You make a good point, truncating the pipe name is probably not what the
user really wanted. There is a problem, however: uv_pipe_connect returns
void :-(

We cannot change it in the v1.x series because we'd break the API. We could
instead have a new API:

int uv_pipe_connect2(uv_pipe_t* pipe, char* name, size_t size)

Which would return an error and also allow us to support abstract sockets
on Linux (that's what the size argument is for).

Thoughts, @bnoordhuis? I know you're not a big fan of foo2 naming... In
master we can just replace the function! :-)

**Comment by bnoordhuis** [comment]
I think it should be possible to change the return value from void to int in a minor release.  It's not an ABI change because the return value is not a callee saved register under the SysV ABI.

That said, I don't think there is a need because the reason the return type is void, is that the error is always propagated to the callback.  In theory, it should be a simple matter of adding the following check to uv_pipe_connect:

```c
if (strlen(name) > sizeof(saddr.sun_path)) {
  err = -ENAMETOOLONG;
  goto out;
}
```

In practice, things might be a little more complicated because it's not guaranteed that `sizeof(saddr.sun_path)` is really the longest possible path.

**Comment by mdawsonibm** [comment]
Propagating the error to the callback was what I had in mind.

Even if sizeof(saddr.sun_path) is not the longest path, the existing code in uv_pipe_connect truncates to this length in this line:
    strncpy(saddr.sun_path, name, sizeof(saddr.sun_path) - 1);
so it is the effective maximum length already.

**Comment by bnoordhuis** [comment]
What I mean is that the underlying file system may not support file paths that long.  That's only an issue with the more exotic file systems, though.

**Comment by saghul** [comment]
@bnoordhuis I should have mentioned, I kind of dislike the current implementation of uv_pipe_connect. There are error cases that should just return an error, like attempting to call it on a closing handle, for example. I think it should be more like uv_tcp_connect, hence my proposal for uv_pipe_connect2.

**Comment by santigimeno** [comment]
This was fixed in master by https://github.com/libuv/libuv/commit/66319cf494d7875a6ffc8653928d31ffbd07187f
