### ISSUE TITLE
suggestion about distribution file names

### ISSUE THREAD

**Issue by playgithub** [libuv/libuv#2712]
now the default distributed file hierarchy is as this:
```
libuv_root
    include
    lib
        Debug
            uv.dll uv.lib uv_a.lib
        Release
            uv.dll uv.lib uv_a.lib
```
On Windows after adding `libuv_root/lib/Debug` and `libuv_root/lib/Release` to system environment variable path, when developing in debug / release mode, it can't automatically choose the right dll.
My suggestion:
```
libuv_root
    include
    lib
        libuv.dll uv.lib uv_a.lib libuv-d.dll uv-d.lib uv_a-d.lib
```

Thanks

**Comment by saghul** [comment]
Hey there! We are currently in the process of dumping GYP as the buildsystem, so thaat's no longer going to apply. You'll just call CMake and I believe you can customize the output artifact name from the command line.

**Comment by playgithub** [comment]
OK

**Comment by Nipheris** [comment]
@saghul Are you planning to refactor CMakeLists.txt to use only one target for both build configurations instead of the disctint ones (`uv` and `uv_a`)? It's a bit awkward and unnatural to CMake ecosystem because user usually configure [`BUILD_SHARED_LIBS`](https://cmake.org/cmake/help/v3.17/variable/BUILD_SHARED_LIBS.html) for the purpose of selection between static and shared builds.

Macro like `BUILDING_UV_SHARED` can be defined using [`DEFINE_SYMBOL`](https://cmake.org/cmake/help/v3.17/prop_tgt/DEFINE_SYMBOL.html) along with using of [`GenerateExportHeader` utility module](https://cmake.org/cmake/help/v3.17/module/GenerateExportHeader.html) to generate export/import logic you currently have [here](https://github.com/libuv/libuv/blob/v1.34.2/include/uv.h#L30).

Also it will greatly simplify logic of target defines and options, tests, etc.

**Comment by saghul** [comment]
I'm not sure if that's in the cards. Feel free to open an issue to discuss it.
