### ISSUE TITLE
Custom uv_stream_t implementations

### ISSUE THREAD

**Issue by jnicholls** [libuv/libuv#275]
libuv should add a stream interface to allow developers to add their own uv_stream_t types, in order to build pluggable steams directly on top of the friendly libuv interface.  This way, if someone wants to create a TLS stream for example, they can do so and consume that stream exactly the way they would consume a TCP stream for example.  This would greatly help the libuv ecosystem, solve the TLS gap, yet not fill that gap by relying directly on a particular TLS implementation.

Apologies if this is a dupe.

**Comment by coderkevin** [comment]
I've also been looking into using libuv in some new and interesting ways, and am staring at all the special case handling in stream.c and other places.  It looks like the stream type inheritance is implemented data-wise, but not code-wise.  I think some well-placed function pointers could really make the streams extensible.  Maintainers, would you like to chime in on something like this?  I bet it could be done incrementally, but ultimately we would be talking about some fundamental refactoring here.

**Comment by saghul** [comment]
What things would you need? Do you have any concrete proposal in mind? At a quick glance I see 2 types of possible extensions:

- extending an existing stream: TLS on top of TCP, for example
- new streams: a file i/o stream, for example

The first type is already possible, but the second not so much, is this what you have in mind?

**Comment by coderkevin** [comment]
I'm more interested in something like the second one.  I'm actually investigating this for a work project.  We need a platform abstraction layer we could use in embedded and desktop environments.  This would include Windows, Linux, QNX, and potentially RTOSes like SYS-BIOS and others.  Part of this would include streams that represent inter-processor communications for multi-core devices (e.g. from the main ARM to a DSP or auxiliary core).  On the more experimental side, we are also looking to try out async audio, and if the streams were extensible enough, we would use it.  Also, in a few cases, it could make sense to have an in-process memory stream.

At any rate, most of these streams wouldn't make much sense to code directly into libuv.  However, loading them as shared libraries would work very nicely.  We're prepared to do a good amount of work here with libuv as the basis of our platform abstraction layer, but I'm looking to work with you to see how much of this could be given back to benefit libuv.

I've been looking at this the last few days and have the beginnings of a proposal.  Please let me know your thoughts:
1. Add ability in libuv to load stream modules from shared libraries.
2. Each custom stream type would need to somehow append to the UV_HANDLE_TYPE_MAP
3. Add function pointers to the uv_stream_t structure to do the work of uv__stream_open, uv_udp_open, etc.  This could also help break up some of the stream-dependent code that exists in stream.c.  This may be able to be done incrementally.

I am willing to whip up a prototype for this to see what it would look like.

There's only one thing I'm still not sure of.  For certain stream types, the fd and flag parameters may not apply.  I wonder if that could be fully encapsulated in the separate functions for each stream or if there are pitfalls I'm not aware of.

**Comment by jnicholls** [comment]
Both of those use cases.

You say the first is possible, but that's not really true.  For example
with TLS on top of TCP, I would expect to be able to use uv_write to write
plaintext data to a uv_tls_t stream type, and under the hood the data is
encrypted and written to the TCP stream.

To achieve that, we would need deeper integration into libuv.  The idea
here is to create new stream types (whether they ride on top of existing
types or not) and use the standard read/write stream APIs directly.  In
other words, no wrappers.

On Friday, March 20, 2015, Saúl Ibarra Corretgé <notifications@github.com>
wrote:

> What things would you need? Do you have any concrete proposal in mind? At
> a quick glance I see 2 types of possible extensions:
>
>    - extending an existing stream: TLS on top of TCP, for example
>    - new streams: a file i/o stream, for example
>
> The first type is already possible, but the second not so much, is this
> what you have in mind?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/libuv/libuv/issues/275#issuecomment-84167563>.
>


-- 
Sent from Gmail Mobile

**Comment by deleisha** [comment]
Tend to have the same feeling as @jnicholls.

Though we can write wrappers like uv_tls_write, which is done at [libuv-tls](https://github.com/deleisha/libuv-tls) . Having uv_write to handle a pluggable handle will be great.
Last time when I tried, It asserted somewhere on the type of stream, 

Currently, in case of OpenSSL, Intergrating it with libuv is easy with BIO pair. 
But other SSL engine which does not have BIO like facility will not be easy. 

If we have a pluggable stream type, which module writer to take care of uv_read_start and uv_write
might help.

**Comment by saghul** [comment]
> I've been looking at this the last few days and have the beginnings of a proposal. Please let me know your thoughts:
> 1. Add ability in libuv to load stream modules from shared libraries.
> 2. Each custom stream type would need to somehow append to the UV_HANDLE_TYPE_MAP
> 3. Add function pointers to the uv_stream_t structure to do the work of uv__stream_open, uv_udp_open, etc. This could also help break up some of the stream-dependent code that exists in stream.c. This may be able to be done incrementally.

At a first glance that sounds like a lot of internal changes. Here is a counter proposal:

1. Add a new "custom" stream type, which takes a few function pointers to fo the reading and writing.
2. Make uv_read_start and uv_write dispatch to the right place based on the stream type. 
3. Profit?

This is at a back-of-a-napkin-design-level. If you want to pursue this you'll need to write a LEP (https://github.com/libuv/leps) and be ready to provide an implementation with tests.

**Comment by jnicholls** [comment]
I think that proposal is fine and the appropriate step to take that doesn't affect current streams.  If it's implemented correctly, it would be the basis for migrating existing streams over to it.  Having that in place is half the work.

**Comment by txdv** [comment]
saghuls approach sounds easier to implement, is anyone up for writing a lep?

**Comment by coderkevin** [comment]
@saghul , I like your proposal, it would definitely be less intrusive that my original proposal.  I also agree with @jnicholls , that this could the the basis for a larger internal refactoring if so desired later on.  I'm all for incremental steps.

I'm willing to start the process here and write a LEP, although I've never done this and probably don't know what I'm in for.  However, I've been wanting to get more involved in open-source--looks like this could be a good opportunity.

**Comment by saghul** [comment]
@coderkevin great! You can check the example LEP and the ones sent as pull-requests.

**Comment by deleisha** [comment]
@coderkevin, If you need a hand. Please let me know. Would be happy to dirty my hand with this.

**Comment by coderkevin** [comment]
Thanks @deleisha.  I'll get started and let you know when I have something to review.

**Comment by coderkevin** [comment]
I have submitted a PR for the Custom UV Streams LEP.  It's the first draft, so please look it over and let me know what is missing or wrong.  Thanks!
https://github.com/libuv/leps/pull/7

**Comment by coderkevin** [comment]
Hello, I was hoping to bump this a bit, as I've written and updated the LEP for it a few times here:  

https://github.com/coderkevin/leps/blob/custom_uv_streams/XXX-custom-uv-streams.md

Also, I've been working a bit with the implementation I mention in the LEP.  So far, I've got a custom stream implemented in a test using a socketpair where one socket is the custom stream and the other is external to libuv.  I feel this is a fairly accurate model for a socket-type stream integration.  Please feel free to look over what I've done in the fork here:

https://github.com/coderkevin/libuv/tree/custom-streams

So far, I haven't really gotten any feedback on the LEP or the fork, and I'd like to get this feedback earlier rather than later.  That's the whole point of the LEP process, right?  So I'd appreciate any feedback that folks have time to provide.  Thanks!

**Comment by jnicholls** [comment]
@coderkevin I'll take a look at this early next week, thanks for working on it!

**Comment by deleisha** [comment]
Sorry for being late. @coderkevin, is the custom-stream branch still still available?

**Comment by coderkevin** [comment]
Yes, but this is the current branch I'm looking at right now.  I've been trying a couple of different approaches for non-epollable streams, but I could probably use some guidance in this area.

https://github.com/coderkevin/libuv/tree/custom-streams-non-epoll

For the epollable streams, it was fairly easy to get working in tests with a socketpair, but I'm sure I'm missing something.  Also, I didn't bother to implement any listen/accept functionality, but here's the finished proof-of-concept branch for epollable streams:

https://github.com/coderkevin/libuv/tree/custom-streams-orig

Thanks for taking a look!  Any feedback is appreciated.  I'm no advanced C expert, so I probably have missed some things.

**Comment by deleisha** [comment]
Thanks @coderkevin, I am also not a extensive C programmer. 

A quick glance shows that We are having a concrete ```uv_custom_t```. Will having a macro like 
```C
#define UV_HTTP_FIELDS                  \
     //data are defined here

/* takes two argument so as to get away from upper casing in macros
#define UV_CUSTOM_TYPE(type, TYPE)    \
   struct uv_##type##_s {             \
             //DATA macros here       \
             UV_##TYPE##_FIELDS       \
   } 
typedef UV_CUSTOM_TYPE(http, HTTP) uv_http_t;
```
improve extensibility.
But not sure if this is doable without much aggression to  libuv. May be larger libuv community can
give better approach.

**Comment by coderkevin** [comment]
I was also thinking about this.  However, I have been thinking if it would be better to ditch the `void* context` to use the existing libuv pattern of extending structs with extra type fields.  The existing concrete `uv_custom_t` would be the base struct that would be extended, just like `uv_stream_s` extends `uv_handle_s`.  So an example custom stream of "myowncustom" type would look as follows:

```C
typedef struct uv_myowncustom_s uv_myowncustom_t;

#define UV_MYOWNCUSTOM_FIELDS
  int first_data_member;                           \
  unsigned long second_data_member;                \
  char* third_data_member;                         \

struct uv_myowncustom_s {
  UV_HANDLE_FIELDS
  UV_STREAM_FIELDS
  UV_CUSTOM_FIELDS
  UV_CUSTOM_PRIVATE_FIELDS
  UV_MYOWNCUSTOM_FIELDS
};
```

Then you can implement your own functions to init, open, etc, that call uv_custom_init or uv_custom_open.  And you can provide function pointers in the UV_CUSTOM_FIELDS for things that are called internally within libuv.

So, internally, libuv knows what a custom stream is and handles it accordingly, but outside of libuv, nothing ever touches a uv_custom_t handle except for the custom stream implementation itself.  When using your own stream implementation, you'd be using your own datatype that you created.

**Comment by deleisha** [comment]
Yep, I did tried exploring a little bit more on extensiblity so that We can write a TLS stream and http/https. But unfortunately will not work as ```UV_STREAM_FILEDS``` private fileds are not accessible 
from outside of libuv( there is #undef at uv.h). So this seems to imply that if we follow this route and a user want to write its extension, user have to write within libuv. Again, TLS and http might not be in scope of libuv. 

@saghul Any thought will be apperciated.

**Comment by coderkevin** [comment]
That's a tough one.  In a general sense, I don't know that it would make sense to give access to uv internals via the custom stream base class, and I don't know that we'd want to expose any more of the stream internals either, as it makes being cross-platform even more difficult.

For something like TLS, maybe it would make more sense to have it reimplement what it would have used from the internals.  There would be duplicate code, but I don't see any cleaner way--especially when the code might span across repos.

Also, with the advent of custom streams, one could implement one TLS stream for Linux, another one for Windows, and another one for OSX, and them just map them with a macro.  That might allow for more clean, optimized implementations of these streams.

Furthermore, maybe the custom TLS stream could be based on a more general-purpose custom stream and extend it from there.

**Comment by deleisha** [comment]
With the current state of libuv extensibility is quite difficult. It seems to me that libuv is more or less designed for developing other functionality on top it. 
We will prefer code reuse from libuv. But this will not be possible until libuv opens up some of its internal function. 
Also we understand TLS and other higher level protocol will be out of scope of libuv.

But usability can be improved a lot by opening up.

**Comment by coderkevin** [comment]
I can agree with that as a good overall end goal.  I just wonder on the best way to get there incrementally.  In the time I've spent in the code so far, there are a ton of assumptions that libuv is in control directly...the read/write fd code, for example makes a lot of these assumptions.  Not only that, but the internals are different based on each platform.

In the spirit of backward compatibility, I wonder if it might be best to copy a lot of this code and separate it out into smaller chunks that can be integrated easier with other code.  During this time, there will be duplicate code; however, if the owners of libuv desire, the original internal implementations could be phased out after the separated-out code has proven itself.

**Comment by deleisha** [comment]
Any plan or thought on this @saghul and @bnoordhuis.

**Comment by saghul** [comment]
Sorry folks, been quite swamped lately. I hope to look at this next week.

**Comment by bnoordhuis** [comment]
I'm personally not really on board with taking libuv in that direction.  It probably means a lot of internal implementation details become _de facto_ public API.  It's a maintenance drag and increases the friction of future changes.

Also, composition > inheritance.  A TLS stream is a bad example IMO because TCP and TLS live at different levels in the stack.

**Comment by coderkevin** [comment]
@bnoordhuis, how would you recommend implementing a TLS stream in this scenario then?  It would either have to have some platform-specific info about the underlying TCP stream, or it would have to implement a TCP stream itself, right?

**Comment by TomCrypto** [comment]
I'm not seeing why you couldn't implement a TLS stream by simply composing a normal libuv TCP stream and a (custom) TLS state structure, and wrap the recv/send logic using said state according to the TLS spec (roughly: encrypt user bytes in send, decrypt user bytes in recv). No need to know any implementation details about the underlying TCP stream as long as it can connect to something, send and receive bytes, ... same with HTTP, or really any protocol above TCP.

Or am I missing something?

**Comment by bnoordhuis** [comment]
What @TomCrypto said.  Taking OpenSSL as an example, your TCP handle reads data into a BIO that in turn is fed into OpenSSL's state machine.  Likewise for output; OpenSSL will tell you when there is data to write.  io.js and node.js both take that approach and it works fine for them.

**Comment by deleisha** [comment]
We undestand that having TLS and https is out of scope of libuv as it is a IO abstraction layer. The current approach seems to be writing wrappers on top of it. The current approach forces to write wrapper functions like `uv_tls_accept` and `uv_tls_write` which is the approach taken in [libuv-tls](https://github.com/deleisha/libuv-tls)

The intent of this, if I undestood correctly from @jnicholls original description, is to provide a handle to developers to extend it so that we can use `uv_accept` and `uv_write` for TLS and http etc. One benifit We can see is that instead of going by memory BIO/BIO pair approach, we can directly use the socket for SSL. That way we can reduce a lot of hacking on little known SSL engine like PolarSSL.

and Yes @bnoordhuis correctly pointed out correctly, This need to open up  some internal functions 
as API increasing the maintenance friction for libuv maintainer OR we have to do it in our code modifyng the libuv code, which again add maintenance effort. So the request
`Will it be worthful to openup some internal API?`
I guess yes, as this will add lot of flexibility and hence improves libuv usability.

A use case under trial now is implementing [redfish] (http://www.dmtf.org/standards/redfish) which will be run on a BMC(service processor). As BMCs are very resource constrained, we would like to use PolarSSL. The WIP is at [deleisha/sagol] (https://github.com/deleisha/sagol) but I am not happy yet :)

Correct me if I miss something.

**Comment by saghul** [comment]
Ok, after reading the pending messages, re-reading the LEP and checking out some of @coderkevin's code, here are my thoughts:

As I initially said, I see 2 types of integration, once which kind-of replaces stream operations with custom ones, and one which tried to layer itself on top of an existing stream. A "file stream" and a "TLS stream" are respective examples of each.

Now, my idea of replacing some functions can work quite nicely for both at a first glance, but the devil is probably in the details. In a nutshell, a uv_stream_t would have some _vtable_ of operations. The stream functions that (potentially) need replacing are:

* uv_listen
* uv_shutdown
* uv_accept
* uv_read_start
* uv_read_stop
* uv_try_write
* uv_write / uv_write2
* uv_is_{readable|writable}
* uv_stream_set_blocking

We'd need a story for each.

Many of them would not apply for a file stream, for example, so should they be used, ENOTSUP would result.

For a TLS stream, however, those functions would do the TLS dance and then call the same function for the underlying stream, a TCP stream, for example.

The difference between these 2 approaches is that one handles i/o in a completely separate way and the other one uses an existing stream to do the i/o. I don't think considering other options is The Right Thing To Do, I did stop @coderkevin's shm example, but I don't think that's a widely enough required example to go overboard with the API, since it would require exposing significant parts of the internal API, as @bnoordhuis pointed out.

@coderkevin you also have a socketpair example, but that can be easily done today by passing each end to a pipe stream with `uv_pipe_open`.

The idea of adding a protocol such as HTTP at this level is totally out of the quetion, as far as I'm concerned.

Now, I'm not saying having a variant of this is a bad idea, but I see more drawbacks than I see upsides here, at the moment. One thing I'd like to try is to get some uv-tls implementation land in uv-extras, which would be this collection of community contributed reusable modules, and see how that plays out. Yes, we'll need uv_tls_write and uv_tls_read_start, but decomposing uv_stream_t is not justified enough at the moment, IMHO.

So, I move for closing this, rejecting the LEP (though a variant might reappear inthe future, who knows!) and those interested in the TLS part can work in getting uv-tls in shape, so we try this "blessed components outside of libuv" thing.

We all know more than we did when this discussion started, so thanks everyone for contributing!

**Comment by coderkevin** [comment]
@saghul thank you for your comments.

I've kicked this around with sample code in a few ways and had basically come up with the same conclusion as @saghul, that a "vtable" of function pointers in the struct would be needed in order to replace the normal calls for accept(), listen(), write(), etc.  This does seem like a fairly serious architectural change, so I would understand some trepidation to include it.

For my needs, I will see if it's possible to utilize a pipe.  The streams I want to read/write are basically byte buffers, so it might work well enough.  I can keep people posted if they're interested.

**Comment by saghul** [comment]
Closing as discussed, thanks everyone.

> So, what's the plan for file streams then? Just keep files as they are for now?

There are currently no plans for that. Now, if we'd eventually add them, they would probably be builtin, not as an addon.
