### ISSUE TITLE
Callback won't fire on async handle if unref'd and primed before uv_run()

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#276]
``` c
#include <assert.h>
#include "uv.h"

static void async_cb(uv_async_t* handle) {
  *(unsigned*) handle->data += 1;
}

int main(void) {
  uv_loop_t loop;
  uv_async_t handle;
  unsigned numcalls;

  assert(0 == uv_loop_init(&loop));
  assert(0 == uv_async_init(&loop, &handle, async_cb));
  handle.data = &numcalls;
  numcalls = 0;

  uv_unref((uv_handle_t*) &handle);
  assert(0 == uv_async_send(&handle));
  assert(0 == uv_run(&loop, UV_RUN_DEFAULT));
  assert(1 == numcalls);  /* Fails because numcalls == 0. */

  return 0;
}
```

It's arguably a bug.  At the very least, it's unexpected.

/cc @petkaantonov

**Comment by petkaantonov** [comment]
I also assume it's not just before `uv_run` is called but anytime the callback registerer ("receiver") happens to be outside `uv_run` e.g.

```cpp
do {
    more = uv_run(loop, UV_RUN_ONCE);
    // If the other thread happens to use `send` while we're here
    // then it will just be ignored
}  while(more);
```

**Comment by bnoordhuis** [comment]
The problem is that libuv doesn't poll for I/O when there are no handles with a ref.  Because of that, the receiving thread doesn't know that the async handle is ready; it gets primed by a write() from the other thread.

**Comment by saghul** [comment]
I'm not sure I'd consider this a bug. The loop exists because there are no ref'd handles, so nothing gets run at all.

This sequence would also be "unexpected, but still not a bug IMHO:

- create a timer for 10 seconds, start it and unref it
- sleep 15 seconds
- run the loop

The timer callback won't run, should it? I'd say no.

**Comment by petkaantonov** [comment]
Sure but async_send is completely different because you are supposed to be able to use it to notify another thread, which could momentarily be outside uv_run (unless using RUN_DEFAULT) as you notify it. So this means it's unsuitable for what appears to be its only purpose...

**Comment by bnoordhuis** [comment]
Actually, I think I would expect the timer callback to fire...

**Comment by saghul** [comment]
@petkaantonov well, since the callback is called by the loop, I argue it's expected that nothing happens if the loop is not running.

**Comment by saghul** [comment]
@bnoordhuis I'm not sure we can solve this with current design, because the loop doesn't know there is stuff pending, without actually making an iteration :-S

**Comment by petkaantonov** [comment]
The loop is running in the receiving thread but there is very small chance that the receiving thread happens to be outside `uv_run` at the same time the notifier thread calls `async_send`. See my code comment https://github.com/libuv/libuv/issues/276#issuecomment-83749656

**Comment by saghul** [comment]
@petkaantonov Sorry, but I still don't get it. You have multipple threads, and if the receiving thread is not running uv_run, what do you expect?

IMHO, the code in your comment is incorrect. What should happen if you call uv_async_send 5 minutes after uv_run stopped running? If you reply on the sender thread sending stuff to the receiving one, you need to ensure the receiving thread is still there, running the loop. One way to do it is by using a uv_async_t handle (ref'd) dedicated to stopping the loop. Once you call uv_run in default mode, it will never exit because of your async handle, but you're done, you can trigger that handle, and it's callback call uv_stop.

Or maybe you need to give me a better example :-)

**Comment by petkaantonov** [comment]
@saghul Yeah sorry the example doesn't make sense and not the real code.

The real code is:

```cpp
    do {
      more = uv_run(env->event_loop(), UV_RUN_ONCE);
      if (more == false) {
        EmitBeforeExit(env);

        // Emit `beforeExit` if the loop became alive either after emitting
        // event, or after running some callbacks.
        more = uv_loop_alive(env->event_loop());
        if (uv_run(env->event_loop(), UV_RUN_NOWAIT) != 0)
          more = true;
      }
    } while (more == true);
```

And if the other thread tries to notify this thread while this thread is running code in-between the `uv_run`s, then the callback is not called at all when one of the `uv_run`s is ran again.

However, FWIW, this isn't critical, the work-around seems to work just fine, checking for notifications manually between every `uv_run`:

```cpp
env->ProcessNotifications();
```

**Comment by bnoordhuis** [comment]
See discussion in #2370, it's been decided to keep the current behavior.
