### ISSUE TITLE
dns/bind 9.16.2 crashes with libuv v1.36.0

### ISSUE THREAD

**Issue by thierry-FreeBSD** [libuv/libuv#2791]
Yesterday I upgraded the FreeBSD port of libuv to 1.36.0.
Since then, several users reported crashes of Bind: see https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=245653
An experimental patch has been proposed by  Tatsuki Makino: see https://bz-attachments.freebsd.org/attachment.cgi?id=213441&action=diff&format=raw&headers=1

**Comment by bnoordhuis** [comment]
#2736 looks like the most likely culprit, cc @saghul.

That PR was a fix for #2532 but looking at it again, I think that feature may be backwards incompatible. The idea is that `UV_UDP_MMSG_CHUNK` signifies the callback shouldn't free the buffer but existing code isn't aware of that flag.

**Comment by bnoordhuis** [comment]
I've opened a revert: #2792

**Comment by saghul** [comment]
👋  The original feature was. backwards-incompatible...ish.  As in, if you passwd a huge buffer nothing special happend.

How about adding a flag to `uv_uddp_init_ex` to turn the behavior on (it being off by default)?

**Comment by bnoordhuis** [comment]
A flag is a good way forward but if it takes you some time to come up with a patch, I'd like to land the revert first and release it. You can then revert the revert. :-)

**Comment by saghul** [comment]
I'll try to get to it tonight!

**Comment by SoLoR1** [comment]
Can confirm this same issue on Gentoo Linux as well.

`15-Apr-2020 23:05:57.838 general: critical: netmgr.c:1000: REQUIRE(worker->recvbuf_inuse) failed, back trace
15-Apr-2020 23:05:57.838 general: critical: #0 0x5629318abbaf in ??
15-Apr-2020 23:05:57.838 general: critical: #1 0x7fc037259d0c in ??
15-Apr-2020 23:05:57.838 general: critical: #2 0x7fc037271eda in ??
15-Apr-2020 23:05:57.838 general: critical: #3 0x7fc0372768fb in ??
15-Apr-2020 23:05:57.838 general: critical: #4 0x7fc03615beea in ??
15-Apr-2020 23:05:57.838 general: critical: #5 0x7fc03615c4eb in ??
15-Apr-2020 23:05:57.838 general: critical: #6 0x7fc03615edd0 in ??
15-Apr-2020 23:05:57.838 general: critical: #7 0x7fc03614e0ca in ??
15-Apr-2020 23:05:57.838 general: critical: #8 0x7fc0372740e9 in ??
15-Apr-2020 23:05:57.838 general: critical: #9 0x7fc03646cea7 in ??
15-Apr-2020 23:05:57.838 general: critical: #10 0x7fc03639ee8f in ??
15-Apr-2020 23:05:57.838 general: critical: exiting (due to assertion failure)
`

**Comment by thierry-FreeBSD** [comment]
Yesterday I pushed this commit to the FreeBSD port of libuv, and everything seems OK.
=> closing.
Thanks for your reactivity!

**Comment by namarrgon** [comment]
I think this should have been left open until a release is available so that other people don't start filing duplicates.
