### ISSUE TITLE
uv_pipe_open(uv_fs_open()) Aborts on first uv_read_start() on Linux

### ISSUE THREAD

**Issue by brimworks** [libuv/libuv#281]
I found this bug, that I originally reported on "luv" (Lua binding to libuv):

https://github.com/luvit/luv/issues/126

Basically, if you pass the fd returned from uv_fs_open() to uv_pipe_open(), then the first call to uv_read_start() will cause an abort(). Specifically, in linux-core.c the first call to uv__epoll_ctl() returns non-zero and errno is set to EPERM (currently there is code that only ignores EEXIST).

Based on epoll_ctl(2) man page:

http://man7.org/linux/man-pages/man2/epoll_ctl.2.html

It says:

```
       EPERM  The target file fd does not support epoll.  This error can
              occur if fd refers to, for example, a regular file or a
              directory.
```

So, it sounds like I'm trying to do something unsupported? However, this works on Mac (not sure about Windows)... and it looks like there is code out in the wild that assumes that this is possible:

https://github.com/thlorenz/libuv-dox/blob/master/examples/static-web-server/pipe-file.c

At a minimum, it would be much nicer to not get an Abort the moment that uv_read_start() is called.

**Comment by saghul** [comment]
Indeed, that is incorrect. uv_pipe_open is an API to open an existing fiel descriptor as a pipe. But a file is not a pipe. Checking for this in the function itself would require doing `stat`, but I'm not sure we want to go there. It may work on OSX because we do have some fallback code because some fds (TTYs IIRC) don't work well with kqueue so we use select on a thread.

I can add a note clarifying this on the docs. WDYT, @bnoordhuis ?

**Comment by bnoordhuis** [comment]
I recently added a check to uv_tty_init (see #255 and commit fc9e66e) so I suppose it's not out of the question to add similar checks elsewhere.

I'm kind of worried about the performance impact though.  The cost of calling uv_guess_handle() is acceptable for uv_tty_init() because it's called only twice or thrice over the lifetime of a program, but uv_pipe_open(), uv_tcp_open() and uv_udp_open() can get called thousands or even millions of times.

Maybe a note in the documentation is best.

> It may work on OSX because we do have some fallback code because some fds (TTYs IIRC) don't work well with kqueue so we use select on a thread.

The fallback code is for special devices, yes.  kqueue accepts regular files but they're always immediately readable and writable (i.e. the polling aspect doesn't really work.)

**Comment by brimworks** [comment]
I suspected this might be the answer I would get. A clarifying note in the documentation would certainly be helpful... and perhaps an issue should be filed on the libuv-dox project so they don't mislead others into believing that a file can be used as a pipe fd:

https://github.com/thlorenz/libuv-dox/issues

Regarding code changes, I think it would be best to check if EPERM == errno after epoll_ctl(), which would have a negligible effect on performance. When this condition is met, then I could see several alternatives:

 [a] uv_read_ready()'s callback is ran with an appropriate error condition so programs can recover from this error.

 [b] Simulate a pipe by creating a uv_idle_t which performs uv_fs_read() and uv_fs_write() calls and keeps track of the current file offset (this is basically what I've ended up doing in my code... although it is written in Lua and would therefore not be helpful for libuv project).

If I had time I wouldn't mind helping with [b], but I wouldn't want to spend effort on this if a change such as this would simply be rejected... it also would be misleading to implement [b] if it is also not supported in Windows.

Thanks,
-Brian

**Comment by bnoordhuis** [comment]
/cc @thlorenz

> [a] uv_read_ready()'s callback is ran with an appropriate error condition so programs can recover from this error.

I considered that but it would make libuv's behavior diverge across platforms.  That's the case now too but that's more accident than intent.  Perhaps a better error message than just a hard abort is called for.

> [b] Simulate a pipe by creating a uv_idle_t which performs uv_fs_read() and uv_fs_write() calls and keeps track of the current file offset (this is basically what I've ended up doing in my code... although it is written in Lua and would therefore not be helpful for libuv project).

I don't think that can be implemented without breaking the API or the ABI and that would make it a non-starter for the v1.x branch.

**Comment by saghul** [comment]
@brimworks added a note to the documentation here: https://github.com/libuv/libuv/pull/284

**Comment by franknj** [comment]
@saghul , hope you don't mind I ask a different question here ( not an issue ).  

I am looking for a way to use Linux pipe under libuv. I studied uv_pipe_* related API a bit but unfortunately, still feeling in the dark. 

When programming with Linux pipe system call, things are very straightforward and easy. pipe() returns an array of two file descriptors: sd[0] and sd[1] . So one thread can read sd[1] and another thread can write to sd[0]. 

With libuv, how could I achieve the same goal of inter thread communication via linux pipe ?

Thanks in advance,
Frank

**Comment by saghul** [comment]
Hi Frank,

You could still use the pipe() and the use uv_pipe_open to open each end on a different loop.

**Comment by franknj** [comment]
@saghul ,
Thanks a lot for the prompt response. 
Frank
