### ISSUE TITLE
In what situation libuv will poll more events.

### ISSUE THREAD

**Issue by EasyHard** [libuv/libuv#282]
Hi guys, I am looking into the source code to debug a NodeJS problem. And I found this piece of code in  `linux-core.c`
```c
   if (nevents != 0) {
      if (nfds == ARRAY_SIZE(events) && --count != 0) {
        /* Poll for more events but don't block this time. */
        timeout = 0;
        continue;
      }
      return;
    }
```

Does it mean that we will poll more events when every events that we are watching is triggered?

Thanks for your replies!

**Comment by saghul** [comment]
On every loop iteration Linux might poll (as in call epoll_wait/pwait) at most 48 times. We wait for 1024 events and it all came back with something, we try again, this time without blocking.

This is something very specific to the Linux backend, though others implement a similar behavior.

Closing since it's not an issue. Please use the mailing list for questions.
