### ISSUE TITLE
Call statx through glibc

### ISSUE THREAD

**Issue by hinshun** [libuv/libuv#2824]
> We can't easily change `uv_fs_t` in v1.x without breaking ABI so birthtime would be the most compelling reason to switch.
>
> It's probably less hassle to make the system call directly than go through glibc because the run-time and compile-time baseline for libuv is glibc 2.12.
>
> _Originally posted by @bnoordhuis in https://github.com/libuv/libuv/issues/2152#issuecomment-456032335_

I have a use case where I'd like to run `nodejs` using [fakechroot](https://github.com/dex4er/fakechroot/issues/67), but since libuv makes the system call directly for `statx`, fakechroot isn't able shim the call in glibc.

I worked around this issue by patching libuv and compiling my own nodejs for now: https://gist.github.com/hinshun/ba1a8a7d32e8e974dcd60cbce64438d6/

But I'm curious if I can help land a correct patch to libuv to fix this properly. Is it possible we can change the run-time and compile-time baseline for libuv to glibc `2.28`?

**Comment by bnoordhuis** [comment]
> Is it possible we can change the run-time and compile-time baseline for libuv to glibc 2.28?

Not for the foreseeable future. The reason it's 2.12 is RHEL/CentOS 6.

Libuv can't move away from using the system call because e.g. musl libc doesn't have a statx() wrapper. I sent a patch but I need to dust it off again, thanks for reminding me. :-)

A middle ground could be to try looking up the libc symbol with `dlsym(RTLD_DEFAULT, "statx")` first but I feel a better solution is to teach fakechroot about `syscall(__NR_statx, ...)`. `syscall()` is a libc function, fakechroot can DL_PRELOAD that.

**Comment by bnoordhuis** [comment]
After thinking this over, I came to the conclusion that trying to work around it in libuv is the wrong approach. I left a comment over at the fakechroot project: https://github.com/dex4er/fakechroot/issues/67#issuecomment-621724887
