### ISSUE TITLE
IBM i CI job

### ISSUE THREAD

**Issue by richardlau** [libuv/libuv#2851]
As a heads up we've been working on adding IBM i machines to the Node.js CI infrastructure (https://github.com/nodejs/build/pull/1923). To test them I've created a [libuv-test-commit-ibmi](https://ci.nodejs.org/view/libuv/job/libuv-test-commit-ibmi/) job.

Thanks to the good work put in by @libuv/ibmi we're in fairly good shape, with only a small number of test failures: 
https://ci.nodejs.org/view/libuv/job/libuv-test-commit-ibmi/7/nodes=ibmi72-ppc64/console
```
not ok 47 - fs_chown
# exit code 393350
# Output from process `fs_chown`:
# Assertion failed in test/test-fs.c on line 318: req->result == 0
...
not ok 233 - spawn_reads_child_path
# exit code 393350
# Output from process `spawn_reads_child_path`:
# exit_cb
# Assertion failed in test/test-spawn.c on line 72: exit_status == 1
not ok 234 - spawn_setgid_fails
# exit code 393350
# Output from process `spawn_setgid_fails`:
# Assertion failed in test/test-spawn.c on line 1501: r == UV_EINVAL
not ok 235 - spawn_setuid_fails
# exit code 393350
# Output from process `spawn_setuid_fails`:
# Assertion failed in test/test-spawn.c on line 1456: r == UV_EINVAL
```

Curiously some of these are failing in `#if defined(__PASE__)` blocks, 
e.g.
> ```# Assertion failed in test/test-fs.c on line 318: req->result == 0```
https://github.com/libuv/libuv/blob/36549815eed297c74448ff580b5c84713245ec5d/test/test-fs.c#L313-L319

> ```# Assertion failed in test/test-spawn.c on line 1501: r == UV_EINVAL```
https://github.com/libuv/libuv/blob/36549815eed297c74448ff580b5c84713245ec5d/test/test-spawn.c#L1500-L1502

cc @dmabupt 

I've held off adding the job to the main libuv-test-commit job for now until we clear these remaining test failures. Please speak up if there are any objections/concerns about adding IBM i to the main job.

**Comment by dmabupt** [comment]
I believe they are caused by the different user authority design on IBM i. 

In my test, I used my **root like** user profile and all these tests passed. But the **ci user** may not have sufficient authorities.

But it is not that easy to detect if the current user have sufficient authorities to do specific operations like changing files' ownerships. 

For example, If current user's id is not 0 (not root user), he can still acquire the authority like root user. 

So [the test](https://github.com/libuv/libuv/blob/v1.x/test/test-fs.c#L313-L319) may be meaningless on IBM i.

I may need the details of the ci user profile to recreate the failures.

**Comment by dmabupt** [comment]
Hello @richardlau , 
I have submitted the PR #2852 to fix these failures. Would you verify it please?

**Comment by richardlau** [comment]
I've added the IBM i job into the main libuv-test-commit job so it is run with all the other platforms in the CI. Any existing open PR's may fail on IBM i if they haven't rebased to include https://github.com/libuv/libuv/pull/2852.
