### ISSUE TITLE
udp: callbacks are effectively synchronous

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#301]
From https://github.com/iojs/io.js/pull/1313#issuecomment-89425847:

1. Libuv loops over the write requests in the completed queue.
2. For every request, it hands it off to io.js
3. io.js calls into JS land
4. JS land calls uv_udp_send() again (dgram.send())
5. The write succeed immediately and uv_udp_send() pushes the request onto the completed queue, _the same queue it's currently iterating over_.

Commit 4189122 introduced this.  The (very lightly tested) patch below fixes it:

```diff
diff --git a/deps/uv/src/unix/udp.c b/deps/uv/src/unix/udp.c
index 941c0ae..177ad43 100644
--- a/deps/uv/src/unix/udp.c
+++ b/deps/uv/src/unix/udp.c
@@ -133,10 +133,8 @@ static void uv__udp_io(uv_loop_t* loop, uv__io_t* w, unsigned int revents) {
   if (revents & UV__POLLIN)
     uv__udp_recvmsg(handle);
 
-  if (revents & UV__POLLOUT) {
+  if (revents & UV__POLLOUT)
     uv__udp_sendmsg(handle);
-    uv__udp_run_completed(handle);
-  }
 }
 
 
```

Running QUEUE_SPLIT on handle->write_completed_queue before dispatching the callbacks in uv__udp_run_completed does not have the desired effect.

I'm not sure if a better fix that maintains the throughput benefits of calling uv__udp_run_completed() repeatedly is possible.
 
Refs: https://github.com/iojs/io.js/pull/486
Refs: https://github.com/iojs/io.js/pull/1258
Refs: https://github.com/iojs/io.js/pull/1313

/cc @saghul

**Comment by saghul** [comment]
@bnoordhuis I've been looking at this a bit, and I can't see how the diff you pasted fixes it, because we'd never call `uv__udp_run_completed` then (on close aside).

Why do you think splitting the queue doesn't solve it? We could do that at the top of `uv__udp_run_completed` and at the end, check if `write_completed_queue` is empty. If so, we don't stop the io handle for POLLOUT, because there are pending callbacks for next iteration. Or is there any other problem?

Alternatively, we could decrement send_queue_size and send_queue_count *after* calling the send callback, but that would prevent the write to be attempted synchronously, so there would probably be a throughput penalty.

I can try to experiment a bit, is there an easy way to test this?

**Comment by bnoordhuis** [comment]
I don't recall the details but I remember that QUEUE_SPLIT didn't have any effect.  If you revert https://github.com/nodejs/io.js/commit/18d457bd3408557a48b453f13b2b99e1ab5e7159, benchmark/net/dgram.js should start busy-looping again.

**Comment by saghul** [comment]
I'll give it a shot, thanks!

**Comment by saghul** [comment]
Fixed by https://github.com/libuv/libuv/pull/371.
