### ISSUE TITLE
Closing a socket with a pending read makes Windows send a TCP RST packet

### ISSUE THREAD

**Issue by mmomtchev** [libuv/libuv#3034]
* **Version**: 1.40.0 (node-master)
* **Platform**: Windows 10

https://github.com/libuv/libuv/blob/11dd3b467fef2188334b925a0a89643eee892a25/src/win/tcp.c#L1450

On Windows, according to this comment, shutting down the transmit side of a socket should allow for an immediate graceful shutdown with `closesocket` - however this is not what I am observing. What I am observing is a TCP RST packet that goes away if I delay the shutdown to `uv_tcp_endgame` with `close_socket = 0`.

This can be easily reproduced with `res.end()` from Node - `test/parallel/test-https-truncate.js` is a very good example. The connection gets closed by a TCP RST by the server.

I wonder if Node should work around this issue or if it should be fixed in libuv. Normally, it is up to libuv to ensure that the socket is gracefully closed? Or is Node that should ensure that no reads are pending?

https://github.com/nodejs/node/pull/35946
https://github.com/nodejs/node/issues/35904

There is also a very similar issue on OSX for which I will create another issue when I am done digging, it looks like it is related to the default lingering.

**Comment by mmomtchev** [comment]
On UNIX, `uv__stream_close` calls `uv_read_stop`

**Comment by vtjnash** [comment]
I agree, this doesn't seem right. If there's pending read data in flight, I'd expect an RST packet should be sent. It was added in 5aa8c005ec28de2aa66d4cb457b596fdf37f5e44, but on unix, it seems like it immediately, and unconditionally, calls `close`, so I'd expect Win32 to be implemented the same way.

**Comment by mmomtchev** [comment]
Does this solve the RST issue for `test/parallel/test-https-truncate.js`? I still get a RST on Windows
In my case the only solution that works is tearing down the socket in `uv_tcp_endgame()` - calling immediately `closesocket` after `shutdown` will provoke a RST

**Comment by mmomtchev** [comment]
@vtjnash in fact, in my particular case, there is in flight data when the socket is closed
I get (it is an HTTP connection: close connection)

server -> FIN -> client
server <- ACK <- client
server <- data <- client
server -> RST -> client

so in this case, this is not a libuv bug

**Comment by vtjnash** [comment]
IIRC, that's the trivial case where you should see an RST packet on the wire on all platforms, since data has arrived at a non-existent socket (IIUC, there might be some platforms that ignore this error silently, to save resources and/or possibly to limit DoS damage I'd guess). There's also a strong dependence of this behavior on the kernel latencies (watching in wireshark), and NT tends to be a bit higher latency here in my experience with the patterns that libuv uses.

The behavior on Windows is certainly odd—my current understanding (after testing this today), is that if there's any pending overlapped `WSARecv` call when we call `closesocket`, then that call will fail with EABORT, but then the subsystem will mistakenly also send a RST packet (oops). This can be somewhat avoided by calling `CancelIo(tcp->socket)` unconditionally (which is what the comment says, but then doesn't quite do). I think there appears to also be another, better API, but it was hard to use before Windows Vista. Since libuv no longer supports XP, I'm attempting to see if it'll do what we want.

**Comment by mmomtchev** [comment]
I wonder if the RST packet is not simply a response to the last data packet of the client - by the time it is received, `closesocket` has destroyed the socket. Or is it caused by the `WSARecv` aborting? I am very bad with Windows sockets, but on a POSIX system you have two choices for a clean close:
* simply use `close()` with lingering and leave everything to the OS
* or do it manually, by calling `shutdown()` and then `read()` until you get EOF and the call `close()` - in this case you can completely disable linger()
IIRC, a `close()`d socket without lingering should stay in the `FINWAIT1` state?

**Comment by mmomtchev** [comment]
Yes, this is the full exchange:
server calls `shutdown(SD_SEND)`
server > `FIN` > client
socket goes into `FIN_WAIT1` state
server calls `closesocket()`
socket goes into `TIME_WAIT` state
server < `ACK` < client
server < `data` < client
data in `TIME_WAIT` state triggers a RST - this wouldn't have happened in `FIN_WAIT1` state
server > `RST` > client

If lingering is disabled (I think it is?), one should wait for a `FD_CLOSE` in non-blocking mode after a `shutdown(SD_SEND)` and, ideally, call `WSARecv()` is there is more data to be received before calling `closesocket()`
This is from the Microsoft `shutdown()` documentation: <https://docs.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-shutdown>

**Comment by mmomtchev** [comment]
@vtjnash with that last commit I am down to about 20% probability of a `RST` (down from 100%) :smile:

**Comment by vtjnash** [comment]
Yeah, but in wireshark, I am see Win32 meet that exchange expectation, then afterwards send the EOF. So even though there was no data left in flight, since libuv called both recv and closesocket, in addition to getting an EOF in the recv call, it synthesized a RST message too.

Which commit is "last commit"? Do you mean https://github.com/libuv/libuv/pull/3036?

**Comment by mmomtchev** [comment]
I meant <https://github.com/vtjnash/libuv/commit/38e29784c49b30a0e1a35224f058061923a9c88c>

**Comment by mmomtchev** [comment]
I have an absolutely identical issue on OSX - a `shutdown()` is followed by an immediate `close()` - all this is triggered by a JS ```js res.end(data)``` from Node - that destroys the socket causing the last data packet of the client to trigger a `RST`
By now, I am confident that I can make it happen on Linux too - the only platform where this is not systematic
I think this needs discussion and a generic solution?

**Comment by mmomtchev** [comment]
In fact, I think there are a number of issues in the Node tracker that are all related to this problem. For some reasons (probably kernel latency as you said it), it is much more common on OSX and Windows and on Linux, but if you try hard enough, I will get it on Linux too.

**Comment by mmomtchev** [comment]
https://github.com/nodejs/node/issues/23169

**Comment by mmomtchev** [comment]
@jasnell @mcollina @ronag
All of these, it is the same problem, I think this needs discussion
It has been in Node for quite some time now, it is very rare on Linux and it has been partially masked by @ronag 's kludge in `stream_base_commons.js` - it causes Node clients to ignore most of the time server resets at the end of the stream
<https://github.com/nodejs/node/blob/1fd7d8e90387a83fe3a2566bdac147c1b33cdbcc/lib/internal/stream_base_commons.js#L225>
But in fact, the real culprit is the way the connections are closed on the server

* Either the teardown in libuv needs to be completely reworked
* Either some maybe implement some workarounds - that revolve mostly around accepting that an `ECONNRESET` is a normal close - a false assumption that is, alas, quite common in the TCP/IP world

**Comment by mmomtchev** [comment]
Or maybe - a connection reset is simply a warning, not an error?

**Comment by mcollina** [comment]
(unfortunately I do not have time to dig into this right now, I'm sitting this out. I trust @jasnell and @ronag).

**Comment by ronag** [comment]
I’ll try to help out in the next few days

**Comment by vtjnash** [comment]
> a shutdown() is followed by an immediate close() - all this is triggered by a JS js res.end(data) from Node - that destroys the socket causing the last data packet of the client to trigger a RST

Unless I'm misunderstanding, this sounds like a mistake. Since libuv/nodejs is asynchronous, calling `s.shutdown(); s.close()` is identical to just calling `s.close()` and destroys the socket immediately, before waiting for the shutdown to transmit. If there's an error handler for shutdown, it should get reported as ECANCELED, otherwise, I don't know where that error would go. The `close` call should happen inside the `shutdown` callback, if it's intended for this operation to occur first, and not possibly trigger an RST packet to be sent.

**Comment by mmomtchev** [comment]
Here is the full exchange with all the layers:

| Client JS | Client Node/libuv | Client Kernel | Remote Server |
|--------|--------------|-------------|-----------|
| res.end() |
|| shutdown(SD_SEND) |
|||TCP FIN -> |
|||kernel socket goes into FIN_WAIT1 state |
|| closesocket() |
|||kernel socket goes into TIME_WAIT state |
||||<- TCP ACK |
||||<- data |
|||because the kernel socket is in TIME_WAIT TCP RST -> |

And it should be

| Client JS | Client Node/libuv | Client Kernel | Remote Server |
|--------|--------------|-------------|-----------|
| res.end() |
|| shutdown(SD_SEND) |
|||TCP FIN -> |
|||kernel socket goes into FIN_WAIT1 state |
||||<- TCP ACK |
||||<- data |
|| recv() |
||| TCP ACK -> |
||||<- TCP FIN|
|| recv() |
||| TCP ACK -> |
|| closesocket() |
|||kernel socket goes into TIME_WAIT state |

**Comment by mmomtchev** [comment]
The last recv() should return an error, the one before it - either some data (if there was data), either a 0 as in our case

**Comment by vtjnash** [comment]
A quick glance at the nodejs documentation looks like that this is intended behavior. The first seems to be their default behavior, while the second is configurable with `allowHalfOpen: true` https://nodejs.org/api/net.html#net_server_close_callback

**Comment by mmomtchev** [comment]
After a quick glance of the code, it seems that `allowHalfOpen` applies only to the passive side of the connection close. I don't have an idea if this was intended or is an omission. @ronag or @jasnell maybe have something to add?
But in both cases, correctly implementing such an option will require support from libuv, and I think that this is currently not possible for the active side?
Once again from looking at the code, I think the JS `res.end()` is probably the only common case of an active close of a TCP connection, which explains why this was left out for so long - most of the time we do a simultaneous close.

**Comment by ronag** [comment]
Not sure but maybe this is relevant? https://github.com/nodejs/node/issues/31916

**Comment by mmomtchev** [comment]
I think this is the inverse issue - where we actually want to send a RST - something that Node currently does not do - even if the support in libuv is present

**Comment by ronag** [comment]
@mmomtchev You might want to ping some of the people involved with that discussion.

**Comment by mmomtchev** [comment]
@sam-github @addaleax @santigimeno , sorry for the mass ping, we have a this long discussion here, and as we are slowly realizing that it revolves around the root cause of several long-running `ECONNRESET` issues, we would just like to hear from your
To get everyone up to speed:
There was a temporary kludge by @ronag for what he suspected that was a libuv problem - then there was that issue which was caused by the kludge - <https://github.com/nodejs/node/issues/35904>
After investigation, this turned to be a generic server-side problem which is in fact very common on OSX and Windows and very rare on Linux, there are a number of issues which mention it
Because of that kludge, which made Node clients to ignore a `ECONNRESET` at the end of the connection, that issue has stayed hidden for quite some time now
Look at my table above for what happens
Basically, `res.end()` is one of the very few, if not the only common case where the server does a so called active TCP close
This means that the connection will stay half-open (half-closed?) for some time before the client has finished sending data
So, first of all, it seems that libuv doesn't really handle this
And then there is our own `halfOpen` option - which by looking at the code - I guess applies only to the passive end of the connection - the one that is supposed to write after `FIN`

 * So, is this intended or an omission?
 * Should we try to officially ignore `ECONNRESET` (maybe print some warning) when it is received at the end of the connection? This is bad TCP/IP behavior, but it is very common, lots of commercial software does it
 * And finally, what shall we do with libuv, supporting an active close needs lots of work in it

**Comment by jasnell** [comment]
Hmmm interesting. I had suspected this before but got sidetracked on other things and never got back to investigating. The analysis makes sense to me but I'm not yet quite sure what the right approach should be. I've seen a lot of code that ignores the ECONNRESET and I've never liked any of it ;-) ....

@indutny @bnoordhuis @saghul ... any thoughts on the libuv side of this?

**Comment by vtjnash** [comment]
Both `net.createConnection` and `net.createServer` are stated as supporting `allowHalfOpen`, though you have to dig through several layers of functions to confirm that. Additionally, `res.end()` states that it always only closes the write half of the stream (https://nodejs.org/api/net.html#net_socket_end_data_encoding_callback). So that should cover both usage options? Thus if `res.end()` is calling `uv_close` inside the `uv_shutdown` callback (as shown in your diagram), then that's seems to be a deviation from the documentation in nodejs (which says it only halfCloses the stream, and then waits for EOF to arrive to finish closing). But that doesn't seem particularly like libuv's fault if it's being misused, unless you're also seeing libuv somehow doing something strange and synthesizing early closesocket events any or everywhere?

Note that your observation in the original issue does appear to be real (I observe that the code on Win32 does generate RST events in situations that the same code on unix would never cause to generate), but it is unrelated to title description, subsequent analysis, and current discussion.

**Comment by mmomtchev** [comment]
Part of the discussion is here #3036

**Comment by mmomtchev** [comment]
@vtjnash In fact, I think that libuv does support active close - I just found a public API function called `uv_shutdown` which is supposed to do exactly this
But Node doesn't use it (except one obscure case for handling thestdio pipes to its child processes)
Can you confirm this? I mean, that this is the way to properly do it?

**Comment by mmomtchev** [comment]
This has been found to be due to a problem in Node, <https://github.com/nodejs/node/issues/36180>

**Comment by ronag** [comment]
@vtjnash @mmomtchev Should this still be open and if so what's remaining?

**Comment by vtjnash** [comment]
It has been stalled for a long time waiting for nodejs to merge my bug fix (linked just above by GitHub), but I expect to get back to libuv soon and do a bunch of work (including closing this).
