### ISSUE TITLE
Windows installation layout

### ISSUE THREAD

**Issue by SylvainCorlay** [libuv/libuv#3074]
Odly, the cmake installation on windows seems to place libraries (dll, static lib, import lib) into

`INSTALLATION_PREFIX/lib/Release` or `INSTALLATION_PREFIX/lib/Debug` (depending on the build type)

instead of

`INSTALLATION_PREFIX/lib/`.

Is this intended?

**Comment by mbargull** [comment]
For reference, this was introduced with https://github.com/libuv/libuv/pull/2113 and from what it looks like for one special use case. It probably makes more sense to have a more general/common layout by default and let the user change `CMAKE_INSTALL_LIBDIR`/`CMAKE_INSTALL_BINDIR` as needed.

**Comment by bnoordhuis** [comment]
cc @XeCycle - this is presumably relevant to your interests. I don't have a strong opinion myself.

**Comment by XeCycle** [comment]
Thanks for the ping.

Over time I have seen different projects following different conventions, and I’m not really sure which one is preferred on Windows; basically the goal is to allow Release and Debug builds coexist, either placed into different subtrees, or named differently.  (IIRC protobuf uses a name suffix “d” on Debug builds.)  I hope I’ve caught up your context — looks like you are packaging binaries for a python-centric repository?  In that case your situation is actually easier since you probably don’t need to ship Debug builds.  On C/C++ side the background is that MSVCRT has ABI-incompatible Debug and Release libs; libraries built as Release cannot be linked to exe/libs built as Debug.  In the python case it means a Debug build of python will fail to load Release builds of libraries, but I’m afraid very few users will ever do that.

My suggestion is that if your target audience probably has no interest in debugging C, you can remove Debug from your package, but if you’d like to propose changes to upstream C lib, it may be better to allow Debug and Release builds installed together.  I don’t really have a personal preference on exact layout, anyway; the convention used by protobuf is as simple as setting a CMake target property, which IIRC may be named like `DEBUG_SUFFIX`.  Just be careful not to break other platforms, because that property is effective on all platforms.

**Comment by SylvainCorlay** [comment]
Conda is a general-purpose package manager akin to e.g. apt or yum (and really has nothing to do with Python specifically). There are tens of thousands of non-python packages. At the moment, ~30 packages depend on libuv at the moment, from node (except on windows) to r-httpuv.

As I am working on the packaging on uWebsockets for conda-forge, this requires us to include a build of libuv on windows.

The policy for conda-forge is to only include Release builds naturally. I have never seen a package that would create subdirectories of the library dir for Release and Debug builds (and I maintain over a hundred packages for conda-forge). Libuv is a low-level package that most people will install as a dependency of other packages, and it would be natural for the installation layout to be standard.

**Comment by XeCycle** [comment]
OK allow me to add more background on C side.

Building third-party libs together with main application is actually a common way to do "vendor"ing in C/C++ apps; CMake has two built-in modules for that, ExternalProject (since at least 3.0) and FetchContent (added 3.11, usually used together with `add_subdirectory`).  FetchContent encourages library authors to name targets with namespace prefixes to avoid clashes, like "uv::uv", which is NOT done yet on current uv master.  ExternalProject usually builds the lib as a completely separate creature and is thus not picky about CMake target names (it does not even care whether the lib uses CMake), but needs a predictable directory layout.

And before #2113: we have no `install` step on Windows, means ExternalProject needs to rely on layout of build tree, but unfortunately, it differs between generators Visual Studio vs Makefile-and-Ninja.  After my PR it gets this step, but with a (maybe) confusing layout.  (I did see commercial projects using this layout, perhaps because this is the layout of build trees in Visual Studio generator; but I don't state I'm in favor of this layout.)

Now some directions:

- Change to blindly install into `CMAKE_INSTALL_LIBDIR`, with no `DEBUG_POSTFIX`: this will cause problems for users of Visual Studio generator + ExternalProject, because it is multi-config; if a user previously built Debug and want to change to Release, he/she will have to delete the old output, and link uv from objects a second time.
- Change to install to `CMAKE_INSTALL_LIBDIR`, with a `DEBUG_POSTFIX`: this may be an easy way, since the Release lib is at `lib/uv.dll`, and the whole thing aligns better with other open-source projects.  If we add the postfix only on windows we can also avoid breaking *nix users, but well, usually *nix users can simply link their own code built as Debug to uv built as Release.
- Either one of previous changes + rename to `uv::uv`: better integration with FetchContent, but breaks current uses of FetchContent.

All these will break current uses of ExternalProject, for sure; personally I'm okay because I get informed ahead of time.  If we keep the current layout then at least it avoids the problem in Visual Studio generator, but creates more hassle on downstream packagers of release-binary-only packages.

**Comment by XeCycle** [comment]
Put more simply: I would vote down on [your patch](https://github.com/conda-forge/libuv-feedstock/pull/47/files#diff-47fb9002f1cd30ecc93cab221007ee478336ec07f2f80400395d081611b76ecb) as it is, but okay if you add a `DEBUG_POSTFIX`.

**Comment by SylvainCorlay** [comment]
@XeCycle FYI I opened #3084 implementing your suggestion.

**Comment by SylvainCorlay** [comment]
Ping @XeCycle would you be ok to merge the attached PR.

**Comment by SylvainCorlay** [comment]
This should not be closed.
