### ISSUE TITLE
Unable to get info about the null device on Windows

### ISSUE THREAD

**Issue by RaisinTen** [libuv/libuv#3169]
See: https://github.com/nodejs/node/issues/38580

cc @lpinca @MrJithil

**Comment by vtjnash** [comment]
Duplicate of https://github.com/libuv/libuv/issues/1980

**Comment by RaisinTen** [comment]
@vtjnash Is `pagefile.sys` a device file like the `NULL` device is? The resultant error codes seem to be different in the two reports.

I also noticed that the same error happens with `uv_fs_access`.

If I'm not wrong, it calls two functions that interact with the file system:
* `fs__capture_path`: https://github.com/libuv/libuv/blob/af1a79cf490dc805be8b91d719a6aef4dc8fcf0d/src/win/fs.c#L3330
* `GetFileAttributesW`: https://github.com/libuv/libuv/blob/af1a79cf490dc805be8b91d719a6aef4dc8fcf0d/src/win/fs.c#L2137

I don't think the bug lies in `fs__capture_path` because `uv_fs_open` also calls it and there is no error. However, I'm not quite sure [`GetFileAttributesW`](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfileattributesa) is supposed to work with device files. Could it be that this needs [`QueryDosDeviceW`](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-querydosdevicew) to be incorporated into the mix?

**Comment by huseyinacacak-janea** [comment]
I've investigated this issue and below are my findings:
* Tested this in the current `v1.x` branch and saw that it worked as expected. 
* Tested this in Node v18.20.2, v20.16.0 and v22.7.0. Both v20 and v22 worked as expected. I guess v18 doesn't have the latest libuv release because it still has this issue.

@RaisinTen Do you think this can be closed as this issue is now fixed in the current version of libuv?

**Comment by RaisinTen** [comment]
That sounds great, closing!
