### ISSUE TITLE
Release proposal: v1.44.2

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#3586]
v1.44.1 has two regressions that block the libuv upgrade in node so I propose doing a new release once the fixes have landed:

- [x] #3597
- ~#3585~
- [x] https://github.com/libuv/libuv/pull/3598
- [x] https://github.com/libuv/libuv/pull/3540
- [x] https://github.com/libuv/libuv/pull/3554
- [x] https://github.com/libuv/libuv-release-tool/pull/17
- [x] #3563 
- [x] https://github.com/libuv/libuv/pull/3611
- [x] https://github.com/libuv/libuv/pull/3629
- [x] https://github.com/libuv/libuv/pull/3625
- [x] https://github.com/libuv/libuv/pull/3634

optional:
- https://github.com/libuv/libuv/pull/3526
- https://github.com/libuv/libuv/pull/3570
- https://github.com/libuv/libuv/pull/3571
- https://github.com/libuv/libuv/pull/3462
- https://github.com/libuv/libuv/pull/3679
- [x] https://github.com/libuv/libuv/issues/3601

There are also a number of other bug fixes that have made their way into this release already.

**Comment by richardlau** [comment]
There was also a third, fixed by https://github.com/libuv/libuv/pull/3565.

**Comment by twose** [comment]
Maybe #3584 ?

**Comment by drfloob** [comment]
Please include https://github.com/libuv/libuv/issues/3563

**Comment by drfloob** [comment]
Hello! It looks like https://github.com/libuv/libuv/pull/3598 was approved a week ago. Is this patch release waiting on anything else?

Otherwise, is there anything I can do to help move this forward? I am waiting on a release with the iOS fixes included here, as well as the patches I landed already in 1.44.1.

**Comment by vtjnash** [comment]
It is waiting on https://github.com/libuv/libuv/pull/3611 review

**Comment by vtjnash** [comment]
Still waiting on #3611 review

**Comment by vtjnash** [comment]
https://ci.nodejs.org/view/libuv/job/libuv-in-node/215/

**Comment by bnoordhuis** [comment]
@vtjnash Do I summarize correctly that the release is blocked on (potential?) regressions in Node's test suite on Windows?

**Comment by vtjnash** [comment]
I admittedly looked at that one the least. But I commented about that a little bit here: https://github.com/libuv/libuv/pull/3598#issuecomment-1112567954 and then was waiting for someone who works on nodejs to pick it up. From looking at the original PR description, it sounds like part of the implementation there is making invalid assumptions about the ordering of when various async events might fire. In particular, there seems to be a rather high use of `process.nextTick` in nodejs's lib folder to randomly delay some random events. This seems like a design smell to me, as this doesn't provide much guarantee about what order events may eventually get processed. It seems that in half of these CI failures, the events don't always get delayed "enough" and the other half of them, the events get delayed "too much". That doesn't seem like it should be possibly if the nodejs state-machines were correctly operating based on actual events rather than relying on exact counting of event loop ticks.

**Comment by bnoordhuis** [comment]
`process.nextTick()` callbacks actually have fairly stringent ordering. Around every call into the VM, basically.

That does mean when a libuv callback is delayed, nexttick callbacks are likewise delayed.

**Comment by vtjnash** [comment]
It is assuming they fire immediately, such that libuv has no time to continue interacting with the stream handle which it has left open to close on the nextTick. But libuv has never promised to only call the read callbacks once per loop. That would be a radical redesign here to batch up all of the alloc_cb and then do a single read_cb for a given stream object.

**Comment by bnoordhuis** [comment]
I've been looking at [the failing check](https://github.com/nodejs/node/blob/85f8821f4dc0f492394edc1a4a99ba150994dbbf/test/async-hooks/test-tcpwrap.js#L131-L132) but it doesn't seem like it ought to be failing.

`onserverClosed()` is called as the completion callback for `server.close()`. Its destroy hook should have run by the time the close callback is called.

A destroy hook is called from  a `uv_check_t` callback. I suspect a change in libuv swapped the order of events with respect to `uv_close()` callbacks.

Cross-thread synchronization can also kick off destroy hooks, through a `uv_async_t`, but I'm >50% sure that doesn't apply here. Grep node's src directory for `SetImmediateThreadsafe`, it's not used a lot.

**Comment by vtjnash** [comment]
nodejs assumes that libuv can't send a message and read the reply in the same iteration of the event loop. This has always been false, but previously it was much less likely (around 1-in-32k), so would have required more effort for nodejs to test this edge case properly. libuv probably could always arbitrarily delay errors to prohibit them from being reported in the same loop iteration as data, but this seems like something nodejs could handle better instead.

**Comment by vtjnash** [comment]
a typical order of operations in the libuv loop for this case previously was:
```
loop poll step
read some data, conclude socket is done
send shutdown message
schedule destroy callback to be run with `check`
with IOCP, libuv receives the shutdown message here, but defers delivery
calls check callbacks
calls callbacks delayed from the last loop iteration
loop poll
 - on unix, the shutdown message is usually received here
call close callbacks
```
now it is
```
loop poll step
read some data, conclude socket is done
send shutdown message
schedule destroy callback to be run with `check`
libuv receives the shutdown message here with IOCP
libuv calls the callback to handle the shutdown message, causing nodejs assumptions to fail (it assumes it is impossible to receive more callbacks before `check` runs), and nodejs closes the object
call close callbacks, leading to test failure
calls check callbacks
loop poll
```

**Comment by bnoordhuis** [comment]
I don't think that's the right reading. Node calls `uv_close()` from a I/O callback and expects the `uv_check_t` callback to run before the close callback. Reasonable assumption because that's what libuv is supposed to implement.

In pseudo code:

1. run close callbacks
2. poll for i/o
3. run check callbacks
4. goto 1

(Aside: if you use 10., 20., etc. as the line numbers, GH-flavorerd markdown will obstinately renumber them to 10., 11., etc.!)

**Comment by vtjnash** [comment]
I would have said close comes last before the goto, but it is the same overall order. I see that is right about check (I was thinking it used `idle`. So perhaps nodejs is handling the `shutdown` (EOF) message immediately (to fire the event hook for onserverClosed), rather than deferring that?

For TLS, I know there is a bug where it uses `check` to pretend that a `try_write` call was a real `write`, so then any `destroy` calls it tries to make pending using `check` for "later in the loop" to run, will actually be delayed until the next iteration of the loop.

So alternatively, perhaps there is a similar issue here, if it is waiting for the `write` callback to schedule the `destroy` callback. But we expect to sometimes get the `read` callback IOCP processed in the event loop one cycle earlier than we get the write-completion if it is using IOCP.

**Comment by vtjnash** [comment]
This design is asinine. We can turn this into a 100% failure rate with this trivial (nonfunctional) change. The order of events is we get can look like this:

```
poll for i/o
do i/o
run socket closed callbacks, schedule check callbacks
sometimes run server closed callbacks, schedule check callbacks

poll for i/o
do i/o
maybe run some server closed callbacks <-- this is asinine!!
run check callbacks <-- asserts here that this has run before the the server closed callbacks
run socket closed callbacks, schedule check callbacks
run some server closed callbacks, schedule check callbacks

poll for i/o
do i/o
run check callbacks <-- expects here that this has run before the the socket closed callbacks that scheduled it
```

> `onserverClosed()` is called as the completion callback for `server.close()`

Actually, it is the completion callback for when `close` has been called for the last client and the server is closed, so does not get run here. This is a bad design, because it means the callback gets arbitrarily delayed until an entirely unrelated event.

> A destroy hook is called from a uv_check_t callback.

This is true, but the `uv_check_t` is scheduled by the `close_cb`, so it should always happen after `onserverClosed`, except that `onServerClosed` is randomly delayed while waiting for network activity on an unrelated socket object.

Except it looks like it isn't always true, since the destroy hooks might be converted into a microtask being scheduled by an `async` (env->RequestInterrupt) to be run at `process.nextTick` (more on that later).

> Cross-thread synchronization can also kick off destroy hooks, through a uv_async_t, but I'm >50% sure that doesn't apply here. Grep node's src directory for SetImmediateThreadsafe, it's not used a lot.

SetImmediateThreadsafe is not used much, but from reading the code, it looks like that `async` object also calls the SetImmediateNative hooks (e.g. destroy hook) that were not supposed to be run until the `check` phase. It looks like it thus might run the check hooks at two points per loop iteration, so that additionally looks rather bad too.

> process.nextTick() callbacks actually have fairly stringent ordering. Around every call into the VM, basically.

Actually, they have no ordering whatsoever (https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/#process-nexttick-vs-setimmediate), they run at the earliest opportunity possible. You are thinking of `setImmediate`. As it says in the docs, the naming is misleading.

```diff
diff --git a/deps/uv/src/unix/stream.c b/deps/uv/src/unix/stream.c
index 5858258d28..7d2daea98c 100644
--- a/deps/uv/src/unix/stream.c
+++ b/deps/uv/src/unix/stream.c
@@ -1286,8 +1286,9 @@ int uv_shutdown(uv_shutdown_t* req, uv_stream_t* stream, uv_shutdown_cb cb) {
   stream->flags |= UV_HANDLE_SHUTTING;
   stream->flags &= ~UV_HANDLE_WRITABLE;
 
-  uv__io_start(stream->loop, &stream->io_watcher, POLLOUT);
-  uv__stream_osx_interrupt_select(stream);
+  if (QUEUE_EMPTY(&stream->write_queue)) {
+    uv__io_feed(stream->loop, &stream->io_watcher);
+  }
 
   return 0;
 }
diff --git a/test/async-hooks/test-tcpwrap.js b/test/async-hooks/test-tcpwrap.js
index 3256a1598b..88aa3c2367 100644
--- a/test/async-hooks/test-tcpwrap.js
+++ b/test/async-hooks/test-tcpwrap.js
@@ -123,8 +123,9 @@ function onconnection(c) {
   checkInvocations(tcp1, { init: 1 }, 'tcp1 when server receives connection');
   checkInvocations(tcp2, { init: 1 }, 'tcp2 when server receives connection');
 
-  c.end();
-  this.close(common.mustCall(onserverClosed));
+  c.end(() => {
+    this.close(common.mustCall(onserverClosed));
+  });
 }
 
 function onserverClosed() {
```

**Comment by vtjnash** [comment]
I need some reviews on recent PRs to get this release finished, please

**Comment by vtjnash** [comment]
3 shutdown-related issues:
#3646 (makes it easier to trigger the nodejs tcpwrap bug on unix)
#3648 (minor bugfix / DRY cleanup)
#3649 (significant rearrangement of the event loop / shutdown handling, so that it does not run in the `close` phase, but in the pending phase like unix)

**Comment by bnoordhuis** [comment]
I reviewed the first two. That last one is a bit out of my comfort zone.

**Comment by vtjnash** [comment]
Reviewing with whitespace hidden may help slightly with that one, since indentation changed, and that doubled the number of lines touched. If it helps also, the 2 unix changes you reviewed already are the same changes I did on windows, then ported to unix, so the intent is partly just to review that the code now uses the same structure and order of events.

**Comment by bnoordhuis** [comment]
I looked at it again just now but... let's say still out of my comfort zone.

I'd like to move forward with the release. It's been three months since opening the issue.

**Comment by bnoordhuis** [comment]
@vtjnash We're good to do a release now?

**Comment by vtjnash** [comment]
I believe so. I opened https://github.com/libuv/libuv/pull/3679 for discussion, but I don't think it needs to be blocking

**Comment by lpinca** [comment]
See also https://github.com/libuv/libuv/issues/3671, not sure if it has been already investigated.

**Comment by vtjnash** [comment]
Looks like CI+node is broken, so I guess I will proceed without that

**Comment by wa-Nadoo** [comment]
CI fails because the default git branch setting in node.js repo has been switched from master to main

**Comment by richardlau** [comment]
> Looks like CI+node is broken, so I guess I will proceed without that

Should be fixed now. (Was an overlooked reference to the old `master` branch in nodejs/node (which has now been renamed) that was hidden behind an advanced button in the job configuration.)

**Comment by richardlau** [comment]
> > Looks like CI+node is broken, so I guess I will proceed without that
> 
> Should be fixed now. (Was an overlooked reference to the old `master` branch in nodejs/node (which has now been renamed) that was hidden behind an advanced button in the job configuration.)

FWIW https://ci.nodejs.org/view/libuv/job/libuv-in-node/217/ is failing because the Node.js gyp files would need updating to pick up `src/strtok.c`.
