### ISSUE TITLE
Missing uv_sem_timedwait

### ISSUE THREAD

**Issue by joy4eg** [libuv/libuv#3628]
Version: current master

Currently we do have [uv_cond_timedwait](http://docs.libuv.org/en/v1.x/threading.html#c.uv_cond_timedwait), but the implementation of portable
```c
int sem_timedwait(sem_t *sem, const struct timespec *abs_timeout);
```
Which (I guess) should be called `uv_sem_timedwait` is missing.

**Comment by bnoordhuis** [comment]
You're welcome to open a pull request but one problem I see off the bat is this:

`sem_timedwait()` uses a real-time clock (i.e., can move back in time) but `uv_sem_t` on macOS is implemented in terms of Mach semaphores and those use a monotonic clock. `WaitForSingleObject()` on Windows may have the same issue.

<hr>

The reason libuv uses Mach instead of POSIX semaphores is because the latter used to be broken/missing.

 I think they're there and working okay now but switching over won't help this feature request because macOS _still_ lacks `sem_timedwait()`.

**Comment by bnoordhuis** [comment]
I'm going to close this for lack of movement but if anyone still wants to work on this, by all means go ahead and open a pull request.

**Comment by vtjnash** [comment]
In case anyone does decide to pick this up later, inside the mach kernel it is called `semaphore_wait_deadline` (with uint64_t deadline, using clock monotonic nanoseconds) since 10.6 (https://developer.apple.com/documentation/kernel/1585829-semaphore_wait_deadline), and is exported as `semaphore_timedwait[_signal]` (with mach_timespec_t wait_time)
