### ISSUE TITLE
test_pipe_get_getsockname_blocking broken on windows

### ISSUE THREAD

**Issue by piscisaureus** [libuv/libuv#376]
There are two issues, one of them is arguably a problem with the API.

* The test creates a pipe with `CreatePipe()`. Pipes created that way don't have a name, but the test tries to verify that the pipe does have one.
* `uv_pipe_getsockname` returns an empty string because the pipe has no name. However the string is not null-terminated! See https://github.com/libuv/libuv/blob/v1.x/src/win/pipe.c#L2044.

**Comment by saghul** [comment]
> uv_pipe_getsockname returns an empty string because the pipe has no name. However the string is not null-terminated! See https://github.com/libuv/libuv/blob/v1.x/src/win/pipe.c#L2044.

IIRC this is intentional. On Linux you could have an abstract socket, whose name is \0foo, so the API doen't null-terminate the strings on purpose, the user must use the size out argument.

See the note here: http://docs.libuv.org/en/v1.x/pipe.html?highlight=uv_pipe_getsockname#c.uv_pipe_getsockname
