### ISSUE TITLE
uv_barrier_wait does not always drain waiting threads

### ISSUE THREAD

**Issue by marka63** [libuv/libuv#3872]
Rapid calls of `uv_barrier_wait` with the same barrier can deadlock a process if not all threads have resumed before `uv_barrier_wait` is called on a just released thread as `in` becomes non zero.   This does not appear to be an issue with the `pthead_barrier_wait` based Linux implementation.
* **Version**: 1.44.2
* **Platform**: Darwin ant-6773.local 20.6.0 Darwin Kernel Version 20.6.0: Sun Nov  6 23:16:58 PST 2022; root:xnu-7195.141.46~1/RELEASE_ARM64_T8101 arm64

**Comment by bnoordhuis** [comment]
I'm not 100% sure I follow your explanation. What do you mean by "a just released thread"?

Can you perhaps post sample code that shows the hang?

**Comment by marka63** [comment]
Call uv_barrier_wait multiple times on the same barrier.  We where doing this is BIND where we where using the same barrier to start and stop the listeners.  The mock code in the unit tests just called `uv_barrier_wait` fast enough on the error path to trigger deadlock.  The issue shows the unit test deadlocked and the uv_barrier state when this happens.  We have worked around the issue by using multiple barrier structures.  https://gitlab.isc.org/isc-projects/bind9/-/issues/3770

The fix should be easy.  Add a new unsigned integer structure element `gen`.  Initialise it to any value (0 is a good choice).
capture that value when you enter the lock. Increment the value when you release the lock.  Wait for the value to change before releasing the other threads.

```
  unsigned int gen;
  ...
  uv_mutex_lock(&b->mutex);

  gen = b->gen;                                                  <<<<

  if (++b->in == b->threshold) {
    b->in = 0;
    b->out = b->threshold;
    b->gen++;                                                      <<<<
    uv_cond_signal(&b->cond);
  } else {
    do
      uv_cond_wait(&b->cond, &b->mutex);
    while (b->gen == gen);                                 <<<<
  }
  ...
```

```
uv_barrier_wait(&barrier);
uv_barrier_wait(&barrier);
```

**Comment by bnoordhuis** [comment]
Okay, after seeing https://gitlab.isc.org/isc-projects/bind9/-/commit/7a677e45d1d074bcb02e7b7b6abaf49058e1e3ec I think I understand what you mean.

Correct me if I'm wrong but you were calling `uv_barrier_destroy()` when other threads were still blocked on it, right? E.g., something closer to this:
```c
uv_barrier_wait(&b);
// ...
uv_barrier_destroy(&b);
```
Than this:
```c
if (uv_barrier_wait(&b)) // if last waiter
  uv_barrier_destroy(&b);
```

**Comment by vtjnash** [comment]
If I understand correctly, the question is whether this code runs correctly on multiple threads:
```
uv_barrier_wait(&b);
if (uv_barrier_wait(&b)) // if last waiter
  uv_barrier_destroy(&b);
```

**Comment by bnoordhuis** [comment]
I realize the `if (uv_barrier_wait(b)) uv_barrier_destroy(b);` pattern we recommend in our docs is defective.

[POSIX says this](https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_barrier_wait.html):

> [..] shall return PTHREAD_BARRIER_SERIAL_THREAD for a single (arbitrary) thread synchronized at the barrier and zero for each of the other threads

Note it doesn't say "last thread". When you run libuv's `barrier_serial_thread` test (which uses that pattern) on linux+glibc, ThreadSanitizer in fact complains about a data race in `pthread_barrier_wait()` vis-a-vis `pthread_barrier_destroy()`.

Our fallback code is actually a bit better in that respect because it only returns the magic "you're the last one" value to the final waiter (no tsan complaints); we probably ought to move away from the libc implementation.

**Comment by vtjnash** [comment]
Assume all threads are executing that same code block, so it should exit the first barrier

**Comment by bnoordhuis** [comment]
Not sure I follow what you're saying. Let me explain what I mean:
```c
if (pthread_barrier_wait(b)) pthread_barrier_destroy(b); // thread A
if (pthread_barrier_wait(b)) pthread_barrier_destroy(b); // thread B
```
Thread A can wake up and proceed to call `pthread_barrier_destroy()` while thread B is still sleeping in `pthread_barrier_wait()`.

As a quality-of-implementation issue both glibc and musl seem to deal with that by blocking in `pthread_barrier_destroy()` until the other waiters are gone but POSIX doesn't mandate. It's in fact UB:

> The results are undefined if pthread_barrier_destroy() is called when any thread is blocked on the barrier

glibc has a real (if seemingly benign) data race caused by an unsynchronized read of the barrier's `count` field. Our homegrown barrier has none of these issues.

Anyway, that's something of a digression. The original bug report still needs clarification from @marka63.

**Comment by vtjnash** [comment]
This is supposed to work, according to POSIX, but OP may be saying it is broken in our implementation (and instead deadlock in the second wait).
```
barrier_wait(b); barrier_wait(b); // thread A
barrier_wait(b); barrier_wait(b); // thread B
```
with `barrier_init(2)`

**Comment by marka63** [comment]
Configure a barrier to wait for  n threads where n > number of cores available.  This is to make it highly probable that a deadlock will occur with the old implementation.   Run n threads with just the 2 uv_barrier_wait calls being executed in each thread. The process should lock up. If you add sleep(1); between the calls it should succeed as you introduce enough delay for all the threads to have been released before the next round of waits start. 

The fixed code should succeed  with or without the sleep.

**Comment by bnoordhuis** [comment]
I can't find anything in POSIX that mandates that behavior. On the other hand, I can't find anything to the contrary either.

We can implement it in libuv's fallback and it'd probably even simplify the implementation a little (don't have to malloc state anymore, can stack-allocate it in `uv_barrier_wait()`) but if POSIX leaves the behavior open, that means libuv's pthread wrapper isn't portable.

**Comment by bnoordhuis** [comment]
Thoughts anyone? My current thinking is to switch to libuv's own barrier on all platforms so we can make stronger guarantees about what it does and doesn't do. It might be a little slower but I doubt it's going to be very noticeable or that anyone cares.

**Comment by vtjnash** [comment]
Seems fine to me to use our own. But does seem to be mandated by posix to me:

https://pubs.opengroup.org/onlinepubs/009695399/functions/pthread_barrier_wait.html

> At this point, the barrier shall be reset to the state it had as a result of the most recent [pthread_barrier_init()](https://pubs.opengroup.org/onlinepubs/009695399/functions/pthread_barrier_init.html) function that referenced it.
