### ISSUE TITLE
Drop Windows 8.1 compatibility, on Jan 1, 2024

### ISSUE THREAD

**Issue by vtjnash** [libuv/libuv#3889]
Windows 8.1 extended security update support ended more than a week ago (on January 10, 2023)[^1]. We have not been able to test this configuration on CI in a few years either. I propose that we drop officially support entirely as well.

[^1]: https://support.microsoft.com/en-us/windows/windows-8-1-support-ended-on-january-10-2023-3cfd4cde-f611-496a-8057-923fba401e93

Refs: https://github.com/nodejs/node/pull/31954 when this policy was established

**Comment by bnoordhuis** [comment]
Seems fine to me although I fully expect another round of wailing and gnashing of teeth from people who refuse to update their OS.

**Comment by vtjnash** [comment]
There are likely substantially more users on Windows 7 still, than on Windows 8 currently (https://gs.statcounter.com/os-version-market-share/windows/desktop/worldwide)

**Comment by madwax** [comment]
Also please keep in mind a lot of places/people in developing world (hate the term) still use Windows7, hell even XP.  Some of the west's e-waste does end up there and given a second life. Just something to think about

**Comment by cctips** [comment]
windows 7 as of now is still one of the more popular operating systems in the world so this topic is debatable and should be considered carefully.

**Comment by vtjnash** [comment]
The estimated Windows 8 users have plummeted from 2.6% to 0.6% since I opened this issue. The Windows 7 users have dropped equally dramatically from 11% to 3%. If they want to keep using old hardware, they possibly should consider being on linux where they can get still get support and updates.

**Comment by bnoordhuis** [comment]
A year has passed. Is it safe to say Windows 8 usage is a rounding error by now? Time to drop support and unblock #2537?

**Comment by Streamlet** [comment]
I think you can stop official test for pre-Win10, only fix bugs when there is a user feedback.
But please do not use Win10-Only API, so that forkers can be easier to make a pre-Win10 version.

**Comment by Streamlet** [comment]
I consider Chromium's abandonment of pre-Windows 10 systems to be unethical—similar to how Wintel alliance manufacturers refuse to provide drivers for pre-Windows 10. There are no essential new APIs in Windows 10 that must be relied upon (and if there were, the old APIs could be emulated). Chromium's abandonment of pre-Windows 10 indirectly leads to a series of software, such as Node, Electron, and VSCode, also abandoning pre-Windows 10. For example, while we can still use VSCode 1.79 on Windows 8.1, its Copilot plugin has started to malfunction due to changes in HTTP API parameters. The newer version of the Copilot plugin could support it, but it requires a newer version of VSCode, which in turn requires newer versions of Node and Electron, and thus Windows 10. These dependencies are unnecessarily heavy. Windows 10 is an unethical system, filled with telemetry and leaving users with no real control over it. Every Windows 10 machine could be considered a zombie computer. Many people have already awakened to this, and Supermium is an excellent project in this regard. Chromium is influenced by Google, and commercial companies have their own interests, which is understandable. However, I believe community-driven projects like Node (including libuv) and Electron could make some small efforts, similar to Supermium, to maintain compatibility with pre-Windows 10 and help improve this ecosystem.

**Comment by bnoordhuis** [comment]
Locked, and deleted an off-topic comment.

**Comment by vtjnash** [comment]
Thanks for your opinion @Streamlet, but please know that Windows 10/11 kernels have added some very important APIs to fix bugs and drastically improve performance, which is why we dropped support for old versions. We are not going to regress the quality for people on supported versions of Windows. We will continue to suggest people use and contribute towards linux (or BSDs) if they want something with support for older hardware and control over their telemetry.
