### ISSUE TITLE
uv_tcp_connect() usage question

### ISSUE THREAD

**Issue by dtoubelis** [libuv/libuv#391]
I have question in regards to uv_tcp_connect():

1. allocate connection request
2. I allocate tcp handler
3. I call uv_tcp_connect()

However it is not clear from the documentation how this function behaves. In particular:For instance, what happens when uv_tcp_connect() return non-zero value?

- in what situations an error is returned
- what error values are returned
- will callback be called anyway if  uv_tcp_connect() returns non-zero value
- in what place to free request memory on success and failure

This is important information as I need to know where to free the memory of tcp handler on error - in the callback or in the main routine.

As a general note I would suggest to improve API documentation and provide these details for every function call (i.e. what error values are returned, what they mean, how to handle these errors, is callback called if function call fails, who is responsible for allocating/deallocating memory on success and on error, etc). So far I'm learning this by trial and error and looking at the source code. It takes forever and it does not speak in favor of the library.

**Comment by saghul** [comment]
> However it is not clear from the documentation how this function behaves. In particular:For instance, what happens when uv_tcp_connect() return non-zero value?
> 
>     in what situations an error is returned

This shoudln't really matter, but (on Unix), it can fail because:

* you're already trying to connect
* libuv fails to create a new socket
* we get an unexpected error from connect(2)

>     what error values are returned

UV_EALREADY if you're trying to connect already, or whatever socket(2) or connect(2) return in casethey give an error.

>     will callback be called anyway if uv_tcp_connect() returns non-zero value
>     in what place to free request memory on success and failure
> 

No, when any libuv API function which takes a callback fails, it will never call such a callback.

> This is important information as I need to know where to free the memory of tcp handler on error - in the callback or in the main routine.
> 

As a rule of thumb, if a function call succeeds, the callback will always be called, either with success or failure, so the memory needs to stay valid. In your case, even if uv_tcp_conect fails you cannot free the memory of the handle, you always need to do that in the callback passed to uv_close (unless uv_tcp_init failed, of course). You can free the memeory for the connect request right away.

> As a general note I would suggest to improve API documentation and provide these details for every function call (i.e. what error values are returned, what they mean, how to handle these errors, is callback called if function call fails, who is responsible for allocating/deallocating memory on success and on error, etc). So far I'm learning this by trial and error and looking at the source code. It takes forever and it does not speak in favor of the library.

We try to have the best documentation we can , but time is limited and there are just too many things to address, sorry about that :-( Specially, documenting all possible return codes is nearly impossible, given platform differences, but as I mentioned above, the actual error usually doesn't matter, it's an error.

Since you're starting up with libuv, feel free to send us PRs fixing the documentation where it's lacking, they will be more than welcome.

PS: for questions, the mailing list (https://groups.google.com/forum/#!forum/libuv) is the right place to go to.

**Comment by dtoubelis** [comment]
@saghul, thank you for the quick reply. This is really helpful. I could not find info about callback being called or not anywhere in the documentation and you just confirmed what I suspected :-) Thanks.
