### ISSUE TITLE
linux: UV_METRICS_IDLE_TIME adds overhead?

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#3937]
https://github.com/nodejs/node/issues/41435#issuecomment-1011094231 remarks that UV_METRICS_IDLE_TIME seems to result in an extra epoll_wait() call.

Reading src/unix/linux.c that seems plausible. Likely applies to other platforms too but I didn't check.

@mmomtchev @trevnorris

**Comment by vtjnash** [comment]
I think that was intentional, in the case where the epoll does not return any events immediately. Is that what you see?

**Comment by bnoordhuis** [comment]
I believe so. I assume it records something but it's unclear what it is.

**Comment by trevnorris** [comment]
@bnoordhuis Reason for the extra poll call is two-fold:

First is the event loop utilization metric (ELU) measures the amount of time the event loop spends idle. Unfortunately, there is no API to check if an event was waiting in the kernel's event queue when poll is called.

To check if an event was waiting, we first call poll with a timeout of 0. If an event is received then we know that the idle time should not be increased. If no event was received then we call poll again with the actual timeout and increment the idle time after it returns.

This is outlined in the commit message in e8effd45, discussed in further detail at https://github.com/libuv/libuv/pull/2725#issuecomment-594752268 and I wrote an in-depth article on it in https://nodesource.com/blog/event-loop-utilization-nodejs.

The rational for allowing this is that it doesn't affect performance as the process is under load. Because as load increases then events will be waiting in the event queue, and no second call to poll will be necessary. Benchmarking agrees with this.

The second reason is for metrics that will be released in v1.45.0. Specifically measuring the number of events waiting when poll is called. I did a lot of research, and a really good measurement of application health is to compare the number of events waiting to be processed against total number of events processed. It also allows us to roughly measure how long events were waiting in the kernel's event queue before they could be processed.

At NodeSource I've created statistical models of how this can be used for more reliable scaling, and I plan on writing these up in another post along with an additional PR for Node.js that exposes these additional metrics.

**Comment by bnoordhuis** [comment]
I'm okay with closing this out if it's expected/desirable behavior.

**Comment by trevnorris** [comment]
Sounds good. I'll look into what we can do to help with performance when reading large files asynchronously.

**Comment by JiaHuann** [comment]
> Sounds good. I'll look into what we can do to help with performance when reading large files asynchronously.

How about monitoring with ebpf?Can we avoid the extra epoll_wait overhead？

**Comment by JiaHuann** [comment]
> @bnoordhuis额外轮询的原因有两个：
> 
> 首先是事件循环利用率指标 (ELU)，用于衡量事件循环闲置的时间。不幸的是，没有 API 可以检查调用 poll 时内核的事件队列中是否有事件在等待。
> 
> 要检查事件是否正在等待，我们首先调用超时为 0 的轮询。如果接收到事件，那么我们知道不应增加空闲时间。如果没有收到任何事件，那么我们将使用实际超时再次调用 poll 并在它返回后增加空闲时间。
> 
> 这在[e8effd4](https://github.com/libuv/libuv/commit/e8effd45569aaefc803d2e95f8a3a626383fab9d)[的提交消息中有概述，在#2725（评论）](https://github.com/libuv/libuv/pull/2725#issuecomment-594752268)中有更详细的讨论，我在https://nodesource.com/blog/event-loop-utilization-nodejs中写了一篇关于它的深入文章。
> 
> 允许这样做的原因是它不会影响性能，因为进程处于负载状态。因为随着负载的增加，事件将在事件队列中等待，并且不需要第二次调用轮询。基准测试同意这一点。
> 
> 第二个原因是将在 v1.45.0 中发布的指标。专门测量调用 poll 时等待的事件数。我做了很多研究，应用程序运行状况的一个真正好的衡量标准是将等待处理的事件数与已处理的事件总数进行比较。它还允许我们粗略测量事件在处理之前在内核事件队列中等待的时间。
> 
> 在 NodeSource，我已经创建了关于如何将其用于更可靠扩展的统计模型，我计划在另一篇文章中写下这些模型，并为 Node.js 公开这些额外指标的额外 PR。

我们可以使用 ebpf 来监控并避免额外的开销吗？
