### ISSUE TITLE
get linux interface altname

### ISSUE THREAD

**Issue by calvin2021y** [libuv/libuv#3976]
* **Version**:  v1.44.2
* **Platform**:  linux

add `altname` into uv_interface_address_t, can avoid mismatch for interface find.

maybe this also can beneficial to other platform.  (for example maybe windows NIC has 2 kind name)

**Comment by bnoordhuis** [comment]
You're welcome to open a pull request but I can think of at least three reasons why it's less than straightforward:

1. Changing uv_interface_address_t breaks ABI
2. Alternative names are relatively new. Libuv supports older kernels
3. No way to obtain the name through getifaddrs()

Let me know if you want to pursue this and we'll discuss details. Otherwise please close this.

**Comment by calvin2021y** [comment]
uv_interface_address_t is alloc from libuv and free by libuv.

if we put `altname` at the end of struct, then I guess no breaks ABI?

Libuv can handle this like `io-uring`,  if the kernel not supported then leave it as `NULL`

**Comment by bnoordhuis** [comment]
Yes, exactly. An ABI break isn't on the table but adding a new type + concomitant API functions is conceivable.

The new API should be considerably better than the old one, though. #829 is relevant.

**Comment by bnoordhuis** [comment]
No follow-up from @calvin2021y so I'll go ahead and close this. Pull request still welcome but see my previous comment.
