### ISSUE TITLE
windows build leads to error

### ISSUE THREAD

**Issue by sl1200mk2** [libuv/libuv#3985]
Version: trunk
Platform: Windows10 with msys2

Hi,
these changes have broken my windows build:
https://github.com/libuv/libuv/commit/17ea56ee737b66b434f31c7731b6629a3b7c83ab

especially the if(CYGWIN OR MSYS)

I'm using msys2 which is up to date and cmake to build libUV. my cmake line is :
cmake -G "MSYS Makefiles" .. -DCMAKE_C_COMPILER=gcc -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/opt/local -DCMAKE_INSTALL_PREFIX=/opt/local -DCMAKE_C_FLAGS="-O2" -DLIBUV_BUILD_TESTS:BOOL=OFF

best regards,
Nicolas

**Comment by vtjnash** [comment]
I thought @erw7 already responded to you about this, but I can't find his comment text anymore. I don't think there is any interest from libuv's team in maintaining the MSYS target, though it may often work, since it is the same as the Cygwin target, and fully distinct from the Windows and Mingw targets.

**Comment by sl1200mk2** [comment]
you mean that : cmake -G "MSYS Makefiles"?

**Comment by sl1200mk2** [comment]
you're absolutely right... cmake -G "Unix Makefiles", leads to no error.
thank you.
I'm closing the ticket

++
