### ISSUE TITLE
Android: src/unix/core.c:1044: error: undefined reference to 'getpwuid_r'

### ISSUE THREAD

**Issue by flyover** [libuv/libuv#406]
Only when building 32bit arch's (armeabi, armeabi-v7a, x86 and mips).

**Comment by saghul** [comment]
Apparently you need API level 21: http://stackoverflow.com/questions/29289381/alternative-getpwuid-r-during-compile-throught-android-ndk and https://groups.google.com/forum/#!topic/android-ndk/UMfhibeuwoI

**Comment by saghul** [comment]
The API level in our build script was recently raised to 21, closing. If you need support for an API level < 21, a patch would be welcome :-)

**Comment by amitg2291632** [comment]
how to change this API version ?

**Comment by saghul** [comment]
No idea, you need to do that in your Android project's settings somewhere...

**Comment by flyover** [comment]
In android-21, armeabi no longer builds because support for __ARM_ARCH__ < 6 has been removed from in platforms/android-21/arch-arm/usr/include/machine/cpu-features.h.

@amitg2291632 In Application.mk, change APP_PLATFORM to android-21.

**Comment by camz** [comment]
I ran into this problem as well, trying to build for android-18 instead of 21.  As it turns out, there is only a single instance of getpwuid_r, and it is easily replaced with getpwuid, which is available in earlier versions of the android API.

I commented out lines 1041 - 1089 and then replaced them with the following code:

    uid = getuid();
    result = getpwuid( uid );

    if( NULL != result ) {
      len = strlen( result->pw_dir );
      if( len >= *size ) {
        *size = len;
        return -ENOBUFS;
      }
      memcpy( buffer, result->pw_dir, len + 1 );
      *size = len;
    } else return -errno;

After making this one small change, I was able to successfully compile and run node.js v4.2.2 on an android-18 based device.

**Comment by saghul** [comment]
The non *_r functions are not reentrant, that's why we use the _r versions, IIRC. So I'm afraid I'm -1 on this one.

@bnoordhuis WDYT?

**Comment by bnoordhuis** [comment]
Agreed.  Too much of a minefield.

**Comment by saghul** [comment]
Ok then. Sorry @camz I'm afraid we just don't support Android API < 21.

**Comment by sickle2** [comment]
Just comment out lines related to "getpwuid" and set HOME environment variable
