### ISSUE TITLE
Consider not including "termios.h" from public headers

### ISSUE THREAD

**Issue by mizvekov** [libuv/libuv#4149]
"termios.h" is not well behaved, and does things like:
```C
#define  B0     0000000
```
Which will break other user libraries quite easily.

Right now it's being included from `uv/unix.h`.

How palatable would it be to add some sort of indirection to avoid it?

**Comment by bnoordhuis** [comment]
I don't see how that could work. Libuv needs it for the definition of `struct termios`, which is part of `uv_tty_t`.

**Comment by mizvekov** [comment]
Non-exhaustive list of examples of how to avoid it:

* Change that field to a pointer, allocate it during initialization.
* Change it to a char buffer big enough to hold it. Static_assert in one of implementation files that this buffer is big enough.

My personal opinion is that either one of those schemes would be a fair price to pay.

**Comment by bnoordhuis** [comment]
One of libuv's guiding principles is to avoid dynamic allocations whenever possible but I'll grant there won't be many uv_tty_t handles in most programs.

However, `sizeof(uv_tty_t)` is under no condition allowed to change because that breaks ABI.

`struct termios` is pretty finicky. Replacing it with a char array or pointer + padding is likely to turn into a maintenance hassle because it needs to stay the exact same size on every combination of platform and architecture that libuv currently runs on.

I really don't want to spend time on chasing down the inevitable bugs. No one else brought up problems with `<termios.h>` in the ~12 years libuv has been around so I'm strongly inclined to leave well enough alone.

**Comment by mizvekov** [comment]
The implicit bringing up of `termios` by libuv has brought me up problems about three times in the past, but it was usually conflicts with my own code that I could quickly change, so I never brought it up.

I suspect I might not be alone here, the fact that no one brought an issue in so many years proves nothing :)

I only bothered to submit an issue about it this last time when now I found an external library that gets broken by termios.

**Comment by vtjnash** [comment]
It is something we might fix in v2 (by hiding all struct definitions, to make them resizable), but that is not established yet as a design change.
