### ISSUE TITLE
Discussion: openat support

### ISSUE THREAD

**Issue by guybedford** [libuv/libuv#4167]
I couldn't find any past discussion on this one so thought I would raise the topic - has `openat` support for libuv been discussed at all?

Apparently, this can be somewhat supported in Windows using `NtCreateFile` with a directory handle.

Having a primitive for directory-descriptor-relative loading even just for a single path segment would provide the useful primitive for building proper filesystem sandboxing. See https://github.com/WebAssembly/wasi-filesystem/blob/main/path-resolution.md#host-implementation for the WASI-filesystem description of this process.

**Comment by bnoordhuis** [comment]
It would be a pretty big overhaul. Not for openat specifically but there's a whole zoo of actionat() functions, not all of them well supported everywhere.

I suspect you're asking in the context of node's hopelessly broken file permissions model. The configurable symlink handling from [`openat2()`](https://man7.org/linux/man-pages/man2/openat2.2.html) is likely very useful for that but it's also decidedly non-portable.

**Comment by guybedford** [comment]
@bnoordhuis yes this is specifically for the relative open filesystem case, not the other functions. So perhaps there's a way to do it as a singular addition and not an overhaul? In terms of non-portability, I thought the `NtCreateFile` approach gave us something close to a portable subset? Are there remaining issues here?

**Comment by bnoordhuis** [comment]
NtCreateFile is Windows-only. What about macOS? The BSDs?

**Comment by guybedford** [comment]
> What about macOS? The BSDs?

These environments have `openat` support.

**Comment by guybedford** [comment]
That is, the technique is to use `NtCreateFile` with a directory handle to behave like openat on Windows, providing some kind of subset of openat across platforms.

**Comment by bnoordhuis** [comment]
> These environments have openat support.

Yes, but not openat2, which is what I'm talking about.

Naive sandboxing with openat is vulnerable to symlink escapes. It  _can_ work provided you're okay with:

1. resolving each path component separately (ex. opening foo/bar/baz translates to three openat operations), and

2. disallowing "interior" symlinks in the sandbox as there's no portable way of making those race free (no O_PATH, no readlinkat)

You're welcome to send a pull request if that's workable for you but node is probably better off doing that directly (and dipping into platform-specific functionality where possible) instead of going through libuv.

The algorithm in https://github.com/WebAssembly/wasi-filesystem/blob/main/path-resolution.md#host-implementation is defective, by the way. It talks about O_NOFOLLOW but not O_DIRECTORY or O_PATH. Without those you're still vulnerable to TOCTOU races.

**Comment by guybedford** [comment]
Ah, yes I'm talking about `openat` not `openat2` here, primarily to get the primitive via the per-segment approach you describe, then to consider optimizations like `openat2` as secondary.

If that sounds like it might be a possibility, I'd like to leave this issue open to track that support here. I think as these security questions come up this is likely the only way to achieve it currently that I know of.

**Comment by guybedford** [comment]
> The algorithm in https://github.com/WebAssembly/wasi-filesystem/blob/main/path-resolution.md#host-implementation is defective, by the way. It talks about O_NOFOLLOW but not O_DIRECTORY or O_PATH. Without those you're still vulnerable to TOCTOU races.

I wasn't aware of this. If you have any further info on a defective scenario here given the tiered `openat` approach that is checking each segment level individually, with symlink following, it would be very interesting to hear.

**Comment by sunfishcode** [comment]
> The algorithm in https://github.com/WebAssembly/wasi-filesystem/blob/main/path-resolution.md#host-implementation is defective, by the way. It talks about O_NOFOLLOW but not O_DIRECTORY or O_PATH. Without those you're still vulnerable to TOCTOU races.

Could you say more about this? `O_DIRECTORY` is nice to use in this algorithm because it detects errors earlier, but I'm not aware of any TOCTOU hazard it protects against, because if an intermediate path component turns out to be a file, the next `openat` will fail with `ENOTDIR` due to the base not being a directory. Similarly, `O_PATH` is nice to use because it supports opening paths inside directories the user only has search permissions on, but I'm not aware of any TOCTOU hazards it protects against.

**Comment by bnoordhuis** [comment]
They're probably not very serious TOCTOU issues but they result in observable changes in behavior vis-a-vis no sandboxing.

Example: `foo/../bar` where foo is a file and bar adjacent to foo. `open("foo/../bar")` fails with ENOTDIR (expected) but the piecemeal openat algorithm finds and opens bar (unexpected.)

Maybe harmless in isolation but a potential stepping stone in environments where concurrent file system mutations are possible, like node.

**Comment by yagehu** [comment]
@bnoordhuis I can start a PR. Can you reopen this issue?
