### ISSUE TITLE
Windows builds are incredibly noisy

### ISSUE THREAD

**Issue by dundargoc** [libuv/libuv#4235]
* **Version**: latest
* **Platform**: Windows, x86-64

Here are the compiler warnings that are generated when building locally: https://gist.github.com/dundargoc/74b7896976653b7f4e9f654ce11ccfc1.

These are shown to any downstream user of libuv by default. Of course I can just disable these myself and call it a day, but I wanted to first check if you were interested in getting these silenced yourself. This way all downstream users would get the benefit of cleaner log builds on Windows. I don't mind sending a PR for this if you're interested.

If so, then we could either fix each instance of warnings or silence the conversion warning if you're not interested in it (since it's overwhelmingly the most common warning). Afterwards we could treat compiler warnings as errors in the CI to prevent regressions.

**Comment by bnoordhuis** [comment]
>  if you were interested in getting these silenced yourself

On a case-by-case basis yes, in general no.

The "potentially uninitialized local variable" warnings are probably false positives but it'd be good to check them anyway.

A lot of the other warnings however are bogus and I plan to encumber the code with things like pointless casts in order to pacify a compiler. To pick two examples from src/idna.c:

> C:\Users\gocdu\programs\libuv\src\idna.c(80): warning C4245: 'return': conversion from 'int' to 'unsigned int', signed/unsigned mismatch

That's the perfectly legal and well-defined idiom of `return -1` in a function that returns `unsigned int`.

Now, you _could_ change that to `return ~0u` but that's definitely less robust. It quietly starts doing the wrong thing when the return type is changed to e.g. `unsigned long` (because then it needs to be `return ~0ul`)

> C:\Users\gocdu\programs\libuv\src\idna.c(500): warning C4244: '=': conversion from 'int32_t' to 'char', possible loss of data

Libuv literally checks on the previous line that the value is in range but the compiler isn't smart enough to realize that.

**Comment by dundargoc** [comment]
I understand the warnings are of questionable quality. However, the fact of the matter is that libuv still *chooses* to enable these warnings by default despite this fact.

> On a case-by-case basis yes, in general no.

Do you also mean that you're not interested in silencing only the warnings that are prone to be false with `/wd4100` or something?

**Comment by dundargoc** [comment]
Yes, I understand. Thank you for your time.
