### ISSUE TITLE
uv_timer_start behavior with `timeout == 0` does not match documentation and can lead to starvation

### ISSUE THREAD

**Issue by mizvekov** [libuv/libuv#4245]
When calling `uv_timer_start` from the a timer callback, while passing a timeout of 0, the timer callback is executed in the current event loop iteration, as opposed to the next loop iteration, as documented in: https://github.com/libuv/libuv/blob/5e302730cd29cfeb15d32369dd2edfd9d3c82c11/docs/src/timer.rst?plain=1#L41C1-L41C79

The current behavior can lead to starvation, such that nothing else is running besides the timer loop, and it can prevent the loop from quitting.

I think this is thorny and we can present a more reasonable behavior to the users, without significant added cost on libuv side.

**Comment by vtjnash** [comment]
Sounds like a documentation update was missed as part of https://github.com/libuv/libuv/commit/66009549067cab59d697cd8df8091a179d1a15fc

**Comment by trevnorris** [comment]
I think it's more like we don't want to process any new timer callbacks that are placed in the queue while timer callbacks are running. IMO that would be optimal, and all those queued callbacks would be run in the next iteration.

The problem here is that it would require doing something like tracking when the timer cb queue is being processed, then adding all calls to `uv_timer_start` to a different queue and swapping it out once all timer callbacks are complete.

Or we could just update the documentation stating that calling `uv_timer_start()` with `0` within the timer callback can cause it to starve. Thoughts?

**Comment by vtjnash** [comment]
Ah, right. I thought we used to do a queue-swap, so that it could iterate it without seeing new entires

**Comment by mizvekov** [comment]
We could, instead of running the timer callbacks immediately in the existing timer loop, add the timer handles to a separate ready list, and then iterate that list calling the callbacks and possibly add it again to the heap, in case of repetition.

The list head could simply be allocated on the stack, and we can reuse the timer handle node area for the list node, since the handle should not be inserted in the timer heap by this point.

**Comment by bnoordhuis** [comment]
Just so we're all on the same page:
```c++
static uv_timer_t a, b;
static void cb_b(uv_timer_t* h);
static void cb_a(uv_timer_t* h) { uv_timer_start(&b, cb_b, 0, 0); }
static void cb_b(uv_timer_t* h) { uv_timer_start(&a, cb_a, 0, 0); }
int main(void) {
  uv_loop_t* loop = uv_default_loop();
  uv_timer_init(loop, &a);
  uv_timer_init(loop, &b);
  uv_timer_start(&a, cb_a, 0, 0);
  uv_run(loop, UV_RUN_DEFAULT);
  return 0;
}
````
`uv__run_timers()` loops indefinitely because `uv_timer_start()` keeps inserting the timer at the front of the timer heap?

We could work around that with an internal queue but IMO it's all around easier to add `if (timeout == 0) timeout = 1;` to `uv_timer_start()` and update the documentation.

**Comment by mizvekov** [comment]
@bnoordhuis I think a `timeout == 0` should mean "calll me back as fast as possible", within reason, but 1 millisecond is a really long time on modern systems. This would be painful on real-time applications for example.

**Comment by bnoordhuis** [comment]
That use case is covered by `uv_idle_t` handles though.

I'm undecided yet about the best approach here. I'll think about it some more.

**Comment by bnoordhuis** [comment]
After thinking about it some more, I'm still inclined to go with the `if (timeout == 0) timeout = 1;` solution. It's simply the simplest fix.

Keeping timers in a side list won't work, that breaks `uv_timer_start(h, cb, 0, 0); uv_timer_stop(h);` because uv_timer_stop() expects the handle to be inside a heap structure.

Maintaining and then merging a side heap is inefficient. Setting a flag on the handle that tells `uv_timer_stop()` the handle isn't actually part of a heap is icky; such hacks usually only lead to more bugs down the road.

I've opened #4246 with a fix + test. If anyone feels strongly a different approach is better, you're welcome to take the test and open a competing pull request.

**Comment by bnoordhuis** [comment]
It's undeniably a change in behavior because it broke some tests that expected zero timers run before everything else but OTOH they were all easy to fix by switching to `uv_idle_start()`.

I'm still disinclined to write a bunch of crufty hacks to handle this special case but don't let that stop (generic) you.

**Comment by vtjnash** [comment]
I am not a particular fan of rounding it up

**Comment by mizvekov** [comment]
I have posted alternative PR here, which is more of a point fix for the starting-a-expired-timer case, preserving as much of the rest of the existing behavior as possible.

No changes to existing tests.
No change in sizes, or offsets of any handles, which means this change should be safe to backport to existing releases, at least wrt to C.
Though it does change the definition of `uv_timer_s`, which strictly speaking is an ODR visible change wrt C++.
We could avoid this, at the cost of some ugliness, but I don't think it's worth it.
