### ISSUE TITLE
MinGW autotools build no longer outputs a DLL

### ISSUE THREAD

**Issue by aantron** [libuv/libuv#4259]
* **Version**: 1.45.0, 1.46.0, 1.47.0
* **Platform**: Windows x86_64, MinGW

Thank you for libuv!

I maintain [Luv](https://github.com/aantron/luv), an OCaml binding to libuv.

Luv vendors libuv and, by default, uses autotools to build libuv internally when Luv is installed. Our Windows builds have started to fail since 748d894e because the autotools build no longer generates `libuv.dll` in `../bin`, or, as far as I can tell, any `.dll` file in any directory. This affects libuv 1.45.0, 1.46.0, 1.47.0 and current v1.x head (1479b76310a38d98eda94db2b7f8a40e04b3ff32).

To reproduce our build,

```
git clone https://github.com/libuv/libuv.git
cd libuv
git checkout 748d894e
./autogen.sh
sh configure --host x86_64-w64-mingw32 CC=x86_64-w64-mingw32-gcc CFLAGS=-DNDEBUG --enable-shared
make -j 4 -o aclocal.m4 -o Makefile.in -o configure -o configure.status -o Makefile libuv.la
sh libtool --mode install cp libuv.la `pwd`
```

This creates, among other output, `../bin/libuv.dll` on `748d894e~`, but appears to no longer do so on 748d894e and all subsequent commits that I have tested (during `git bisect` + v1.x head).

Looking at 748d894e, I can't immediately tell what the problem might be. I wonder if it's due to some autotools interaction with the [additional libraries](https://github.com/libuv/libuv/commit/748d894e82abcdfff7429cf745003e182c47f163#diff-49473dca262eeab3b4a43002adb08b4db31020d190caaad1594b47f1d5daa810R76) listed there.

**Comment by aantron** [comment]
Continuing to look into it. I will either have more information or this may be invalid.

**Comment by aantron** [comment]
Confirmed that this is broken with MinGW 11.0.1.

I think this is all the information I am able to immediately provide. Thank you!

**Comment by bnoordhuis** [comment]
It sounds like this is at its core a mingw issue in that it doesn't provide a (working?) uuid.lib / uuid.dll? What happens when you drop `-luuid` from configure.ac?

A possible workaround is to define `FOLDERID_LocalAppData` directly because that's the only thing we pull from uuid.dll, as far as I'm aware. Its GUID is `{F1B32785-6FBA-4FCF-9D55-7B8E7F157091}` if I'm not mistaken. See the `uv_msafd_provider_ids` array in src/win/poll.c for another example where we define GUIDs directly.

If that fixes the issue for you, please send a pull request!
