### ISSUE TITLE
System freeze after suspending two instances of Neovim

### ISSUE THREAD

**Issue by pajlada** [libuv/libuv#4377]
* **Version**: v1.48.0
* **Platforms**:
  - `Linux billy 6.6.23-1-lts #1 SMP PREEMPT_DYNAMIC Wed, 27 Mar 2024 07:47:20 +0000 x86_64 GNU/Linux` running Arch Linux
  - `Linux yolen 6.8.2-arch2-1 #1 SMP PREEMPT_DYNAMIC Thu, 28 Mar 2024 17:06:35 +0000 x86_64 GNU/Linux` running Arch Linux
  - `Linux localhost 6.9.0-0.rc1.20240329git317c7bc0ef03.20.fc41.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Mar 29 14:04:53 UTC 2024 x86_64 GNU/Linux` running Fedora Rawhide

I first noticed this when running Neovim v0.9.5, then bisecting Neovim lead me to [this commit](https://github.com/neovim/neovim/commit/eacd5ca6b8f099ab9fb24549830b316c169004f9) as the first commit with this problem. This commit updates the libuv version in Neovim to v1.46.0.
Bisecting libuv lead me to https://github.com/libuv/libuv/commit/6e073ef5daf93b708a654008959b823b58029e88 as the first commit with this problem.
So I've been able to reproduce this system freeze with Neovim built using libuv https://github.com/libuv/libuv/commit/6e073ef5daf93b708a654008959b823b58029e88 and Neovim built using v1.48.0

Cannot reproduce on macOS, Ubuntu 22.04, Debian sid, Void Linux, or openSUSE.
Cannot reproduce on Arch Linux with io_uring disabled.
Cannot reproduce on Arch Linux in Docker

### To reproduce
1. Be on Arch Linux (bug reproducible on netcup & hetzner servers) or Fedora Rawhide
2. Install Neovim (`pacman -S neovim`)
3. Run Neovim
4. Suspend Neovim (by pressing CTRL+Z)
5. Run Neovim again
6. Suspend Neovim (by pressing CTRL+Z)
7. Your system is now most likely unresponsive

The suspension can be done in separate shells too with the same results.

**Comment by bnoordhuis** [comment]
Thanks for the report. It sounds like you're hitting a kernel bug, it almost has to be. Does setting `UV_USE_IO_URING=0` in the environment fix the freeze?

**Comment by pajlada** [comment]
Setting `UV_USE_IO_URING=0` in the environment fixes the freeze
Previously testing was done with `sysctl kernel.io_uring_disabled=1` (which also fixes the freeze)

**Comment by bnoordhuis** [comment]
Right, that's what I expected. Your best bet is to report it to io-uring@vger.kernel.org or maybe over at https://github.com/axboe/liburing/issues (IIRC Jens accepted bug reports there in the past but I'm not 100% sure.)

I had a quick look at `git log io_uring/` and fs/eventpoll.c in the kernel repo but nothing immediately stood out. FWIW, the last update to io_uring/epoll.[ch] was me undeprecating it back in May last year so whatever the cause, it's probably not directly io_uring+epoll-related.

I can blacklist affected kernels in libuv but I'd have to know the affected range, and since you're testing against v6.9-rc1, it's probably still unfixed.

**Comment by pajlada** [comment]
Thank you! I'll try the GitHub page first

**Comment by pajlada** [comment]
https://github.com/axboe/liburing/issues/1113 contains a kernel patch that fixes this issue and updates for when it'll be available so I'm happy to close this issue.
Thank you for your help!
