### ISSUE TITLE
Support `conceal` ANSI escape on Windows

### ISSUE THREAD

**Issue by sindresorhus** [libuv/libuv#439]
The `conceal` ANSI escape is used to visually hide the output while it still being there.

This is important for consistency between Unix-based systems and Windows in CLI tools.
## Info

https://en.wikipedia.org/wiki/ANSI_escape_code

Unfortunately, this one isn't supported by any Windows API afaik.

I was thinking that it might be possible to emulate it setting the text color to the default background color of the console.
## Test case

```
node -e "console.log('\u001b[8municorn\u001b[28m');"
```
## OS X

<img width="490" alt="screen shot 2015-07-13 at 15 16 01" src="https://cloud.githubusercontent.com/assets/170270/8650297/1cd0ea14-2972-11e5-8164-389a74e67bd7.png">

_Node.js 0.12.5, OS X 10.10, Terminal.app_
## Windows

<img width="960" alt="screen shot 2015-07-13 at 15 16 40" src="https://cloud.githubusercontent.com/assets/170270/8650316/34349494-2972-11e5-8e80-ab26d75b7b64.png">

_Node.js 0.12.5, Windows 8.1, cmd.exe_

**Comment by saghul** [comment]
> I was thinking that it might be possible to emulate it setting the text color to the default background color of the console.

Then selecting it with the mouse would reveal it, right?

**Comment by sindresorhus** [comment]
Yes, but I don't think that matters. On OS X, you can select and copy to get the value anyways, or disable colors in a colorizer like [chalk](https://github.com/chalk/chalk). So it's definitely not intended for sensitive stuff. I would use it to hide noisy info while still being there if you copy/redirect the output.

**Comment by saghul** [comment]
I see. Then adjusting the color to match the one in the background would indeed work.

**Comment by Qix-** [comment]
Common misconception with conceal is that it has the effect that, say, typing a password into an SSH login prompt does. It doesn't. Terminals that emulate the conceal code this way are doing it incorrectly.

I'm speculating, but since the conceal escape seems to be historical, I would imagine copy/paste wasn't an issue on terminals that didn't have mice. The cursor position still advances, iirc. @sindresorhus is correct in suggesting to set it to `[30m`.

However, I'd go so far as to also include `[40m` as well (`[30;40m`). `[30m` by itself would cause issues for those that have changed the color palette on CMD to something other than a black background, and would give it a 'redacted' appearance for those users - which is essentially the intention of the escape to begin with.
