### ISSUE TITLE
about test udp_multicast_join | udp_multicast_join6 not ok | not ok 180 - metrics_pool_events

### ISSUE THREAD

**Issue by RageCPP** [libuv/libuv#4406]
on my open suse 15.5 leap, I build libuv
this is build process
```bash
 1040  mkdir -p build
 1042  (cd build && cmake .. -DBUILD_TESTING=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/rage/code/chessmeta/src/oxygen/third/libuv)
 1043  cmake --build build -- -j$(nproc)
 1045  build/uv_run_tests_a
```
run test output
```bash
not ok 180 - metrics_pool_events
# timeout
# Output from process `metrics_pool_events`: (no output)
not ok 405 - udp_multicast_join
# timeout
# Output from process `udp_multicast_join`: (no output)
not ok 406 - udp_multicast_join6
# timeout
# Output from process `udp_multicast_join6`: (no output)
```
* **Version**:  libuv-1.48.0
* **Platform**: Linux localhost 5.14.21-150500.55.59-default #1 SMP PREEMPT_DYNAMIC Thu Apr 18 12:59:33 UTC 2024 (e8ae24a) x86_64 x86_64 x86_64 GNU/Linux

**Comment by santigimeno** [comment]
Most of the time these are `firewalld` issues. Can you disable it and check whether those tests pass? Thanks

**Comment by RageCPP** [comment]
> Most of the time these are `firewalld` issues. Can you disable it and check whether those tests pass? Thanks

thank you reply, you are right. but I find new failed test item
```bash
not ok 180 - metrics_pool_events
# timeout
# Output from process `metrics_pool_events`: (no output)
```

**Comment by bnoordhuis** [comment]
That's probably because one of the things the test does, is look up a non-existing domain name. Normally that should fail in milliseconds (upstream DNS server should reply with NXDOMAIN) but in some network environments, it takes ages.

I'm going to close this as it's almost certainly a problem with your local environment and not libuv, but if you want to get to the bottom of it, add a few printf statements to test/test-metrics.c
