### ISSUE TITLE
setuid() does not drop all privileges due to io_uring (CVE-2024-22017)

### ISSUE THREAD

**Issue by felixonmars** [libuv/libuv#4416]
* **Version**: 1.48.0
* **Platform**: `Linux build.archlinux.org 6.9.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 17 May 2024 16:56:38 +0000 x86_64 GNU/Linux`

Node.js is currently patching libuv to get rid of io_uring due to this, and I find it strange that it was never mentioned here: https://github.com/nodejs/node/commit/42e659cb9d9425f76dbe9b57a437005508c0933d

As an Arch Linux packager of both libuv and node.js, I would like to find a way forward without having to use a patched libuv for node.js. I am not familiar with this specific problem, but I could imagine options like a runtime switch for io_uring, or maybe if the underlying issue could be addressed.

**Comment by felixonmars** [comment]
Found some (maybe useful) thoughts from the node.js community: https://github.com/nodejs/node/issues/52156#issuecomment-2010116128

**Comment by christian-heusel** [comment]
Should be fixed by this patch: https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?h=master&id=d13ddd9c893f0e8498526bf88c6b5fad01f0edd8

A hotfix is to disable io_uring in libuv via `UV_USE_IO_URING=0` as per https://gitlab.archlinux.org/archlinux/packaging/packages/linux/-/issues/55#note_186945

**Comment by sarandha-fashion** [comment]
After upgrading `node-gyp` to `10.1.0-3` I no longer need use `export UV_USE_IO_URING=0`  before using `yarn install` or `yarn build`.
This was an issue yesterday where I always needed to use `export UV_USE_IO_URING=0` for working with vite scripts through yarn, otherwise it would give me Text file Busy error but looks like it's fixed now?

**Comment by saghul** [comment]
For context, the original issue is being addressed here: https://github.com/libuv/libuv/pull/4421

**Comment by bnoordhuis** [comment]
@santigimeno this was fixed by #4492, right? Node.js can drop the patch (and optionally switch to uv_loop_configure) once we release a new version.

**Comment by santigimeno** [comment]
Sorry I missed this.

> @santigimeno this was fixed by #4492, right? Node.js can drop the patch (and optionally switch to uv_loop_configure) once we release a new version.

Yes, you're right
