### ISSUE TITLE
ibmi: fs_* test are failing

### ISSUE THREAD

**Issue by abmusse** [libuv/libuv#4484]
* **Version**: v1.x 
* **Platform**: IBM i

ref: https://ci.nodejs.org/job/libuv-test-commit-ibmi/nodes=ibmi73-ppc64/1463/console

```text
not ok 97 - fs_posix_delete
# exit code 393350
# Output from process `fs_posix_delete`:
# Assertion failed in test/test-fs.c on line 1087: `r == UV_ENOTEMPTY` (-17 == -87)

not ok 99 - fs_read_dir
# exit code 393350
# Output from process `fs_read_dir`:
# Assertion failed in test/test-fs.c on line 512: `req->result == 0` (-17 == 0)

not ok 104 - fs_readdir_non_empty_dir
# exit code 393350
# Output from process `fs_readdir_non_empty_dir`:
# Assertion failed in test/test-fs-readdir.c on line 356: `r == 0` (-17 == 0)

not ok 113 - fs_stat_batch_multiple
# exit code 393350
# Output from process `fs_stat_batch_multiple`:
# Assertion failed in test/test-fs.c on line 4616: `r == 0` (-17 == 0)

not ok 117 - fs_symlink_dir
# exit code 393350
# Output from process `fs_symlink_dir`:
# r == 0
# Assertion failed in test/test-fs.c on line 2459: `2 == r` (2 == 3)
```

**Comment by richardlau** [comment]
FTR these failures are due to the `fs_posix_delete` test added by https://github.com/libuv/libuv/commit/18266a69696349e9641871f55b88ad6e732a8789 not allowing for POSIX `rmdir` being allowed to return either `ENOTEMPTY` or `EEXIST` for the case where the directory is not empty and leaving the `test_dir` in a state that causes subsequent tests to fail. 

FWIW not only IBM i, but AIX and SmartOS (https://ci.nodejs.org/job/libuv-test-commit-smartos/2200/nodes=smartos20-64/console on current `v1.x`) are affected.

PR to update the test: https://github.com/libuv/libuv/pull/4494
