### ISSUE TITLE
autotools configure script repeats some checks

### ISSUE THREAD

**Issue by johnsonjh** [libuv/libuv#4579]
For v1.x branch, the following two checks are doubled:

`checking if cc supports -fno-strict-aliasing flag... yes`
`checking if cc supports -fno-strict-aliasing flag... yes`

`checking if cc supports -c -o file.o... yes`
`checking if cc supports -c -o file.o... (cached) yes`

There is obviously no ill effect besides the (very) minor inefficiency.

**Comment by bnoordhuis** [comment]
The second "checking if cc supports -fno-strict-aliasing flag" is actually checking whether the linker supports the flag, not the compiler.

I suppose we could change the message like this (literal "linker" because $LD isn't a thing inside configure scripts):
```diff
diff --git a/m4/libuv-check-flags.m4 b/m4/libuv-check-flags.m4
index 2a01308d..9c58dc1b 100644
--- a/m4/libuv-check-flags.m4
+++ b/m4/libuv-check-flags.m4
@@ -88,7 +88,7 @@ dnl Check if the flag is supported by linker (cacheable)
 dnl CC_CHECK_LDFLAGS([FLAG], [ACTION-IF-FOUND],[ACTION-IF-NOT-FOUND])
 
 AC_DEFUN([CC_CHECK_LDFLAGS], [
-  AC_CACHE_CHECK([if $CC supports $1 flag],
+  AC_CACHE_CHECK([if linker supports $1 flag],
     AS_TR_SH([cc_cv_ldflags_$1]),
     [ac_save_LDFLAGS="$LDFLAGS"
      LDFLAGS="$LDFLAGS $1"

```
That won't fix "checking if cc supports -c -o file.o" though. I'm reasonably sure that comes from autotools, not us.

I'm inclined to keep things as-is and just accept the status quo.

**Comment by johnsonjh** [comment]
Makes sense.  I don't think it's a major problem either way.  Feel free to close if you prefer.
