### ISSUE TITLE
libuv 1.49.0 breaks dnstap test in BIND 9

### ISSUE THREAD

**Issue by Mno-hime** [libuv/libuv#4584]
* **Version**: 1.49.1
* **Platform**: Fedora 40

In BIND 9, the `upforwd` system test started to [fail](https://gitlab.isc.org/isc-projects/bind9/-/jobs/4787969) with libuv 1.49.0:
```
2024-09-27 15:08:19 INFO:upforwd.test_upforwd     I:checking DNSTAP logging of UPDATE forwarded update replies (28)
2024-09-27 15:08:19 INFO:upforwd.test_upforwd     I:UQ=0 UR=1
2024-09-27 15:08:19 INFO:upforwd.test_upforwd     I:failed
```

I bisected libuv, and e5cb1d3d3d4ab3178ac567fb6a7f0f4b5eef3083 seems to be the culprit. I believe @bnoordhuis hunch in #4400 came true:

>I'm somewhat worried this change may cause hard-to-debug regressions in existing programs

For CI consumption, we [build](https://gitlab.isc.org/isc-projects/images/-/blob/main/docker/bind9/fedora-template/Dockerfile#L99) libuv 1.48.0 with TSAN enabled for the TSAN image; for non-TSAN image, we pull libuv from Fedora that just got updated to 1.49.1.

**Comment by saghul** [comment]
Ugh. Any chance you can spot a small test case that reproduces the problem? I understand if the answer is "nope" 😅

**Comment by Mno-hime** [comment]
I can work on making the [system test](https://gitlab.isc.org/isc-projects/bind9/-/blob/main/bin/tests/system/upforwd/tests.sh) shorter, so it's clearer what commands were used to trigger this in `named`, but I can't prepare a short test case based on `named` internals and libuv use. We need @oerdnj or some of his collegues. I'll file an internal issue, and we'll see if we can do anything on our side.

**Comment by oerdnj** [comment]
I'll take a look when I get back (in about week and half).

**Comment by bnoordhuis** [comment]
Maintainers, I would suggest to revert that commit and do a point release. Agree/disagree?

**Comment by santigimeno** [comment]
:+1:

**Comment by santigimeno** [comment]
Yes, I'll do it tomorrow.

**Comment by panjf2000** [comment]
This is odd, I can't imagine how that commit would break things, given that it only circumvented one system call `read(2)` and eliminated that latency. Unless, your test precisely needed that latency for some reason, I'd love to see a simple reproducer and find out the root cause in the end.

**Comment by vtjnash** [comment]
Does it access uv_backend_fd? There are some ways I could imagine an application (such as electron) might break the normal invariants depending on what they do with it?

**Comment by vtjnash** [comment]
From the code comments in bind9, there appears likely to be a synchronization error in their code occurring here:
https://gitlab.isc.org/isc-projects/bind9/-/blob/main/lib/isc/async.c#L60

The code comments mention that there is no seq-cst fence after the call to cds_wfcq_enqueue, but the implementation in bind9 assumes that there is one in uv_async_send (there never has been, but it maybe should have one because it is confusing not to have one):
 https://github.com/urcu/userspace-rcu/blob/a84350f8f14be2a8e02457ccc59844fe0815abc7/include/urcu/wfcqueue.h#L301-L312

**Comment by bnoordhuis** [comment]
But there is a seq-cst memory barrier in `uv_async_send()` - we call atomic_fetch_add, twice.

It is true that it doesn't _always_ issue that barrier - when the handle is already pending - but do you think that would explain it? Note the failure was on amd64 - strong memory model.

**Comment by santigimeno** [comment]
`v1.49.2` is released: https://github.com/libuv/libuv/releases/tag/v1.49.2

**Comment by vtjnash** [comment]
The "cheap read" here can invalidate any guarantee about the behavior of the function, since that later code may not be reached:
https://github.com/libuv/libuv/blob/7e6590f31d800b8fdd8740f6a2a0e9a04a0a1e56/src/unix/async.c#L72-L74

Without a seq-cst fence, I wouldn't necessarily assume the relaxed read in this write-read pair to form a happens-before relationship, even with TSO, since that is specifically the one case (Stores may be reordered after relaxed loads) that makes it weaker than seq-cst: https://github.com/urcu/userspace-rcu/blob/a84350f8f14be2a8e02457ccc59844fe0815abc7/include/urcu/static/wfcqueue.h#L182-L199

**Comment by bnoordhuis** [comment]
What I mean is:

1. if the handle _isn't_ pending (i.e., it's the first uv_async_send call), then a memory barrier is issued

2. if the handle _is_ pending (second or later uv_async_send call), then a memory barrier won't help because the async_cb in the other thread can run in parallel with `cds_wfcq_enqueue` (or before, or after - indeterminate, basically)

IOW, any ordering bugs should already be present. It's conceivable eliding the read() syscall in the async_cb thread changed the timings enough to make it more visible but that's conjecture at this point. :-)

**Comment by Mno-hime** [comment]
I don't know why, but libuv 1.49.0 and 1.49.1 were problematic for many FreeBSD BIND 9 users; see https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=282088. The update to 1.49.2 worked for most of them.

**Comment by bnoordhuis** [comment]
Thanks for the info, that points to 27134547ff (or rather, its revert in 18d48bc13c.) That's the only change in v1.49.2 that touches BSD.

**Comment by vtjnash** [comment]
> What I mean is:

> if the handle isn't pending (i.e., it's the first uv_async_send call), then a memory barrier is issued

> if the handle is pending (second or later uv_async_send call), then a memory barrier won't help because the async_cb in the other thread can run in parallel with cds_wfcq_enqueue (or before, or after - indeterminate, basically)

The other option is that they have a data race here, so neither of those is true. Your description assumes that they use seq_cst, but neither they nor libuv uses seq_cst. In particular, in the normal algorithm there, bind9 requires a seq_cst fence between the queue operations and the notify operation so that either of those is true. In the wfcqueue implementation, it looks like bind9 tried to use weaker atomics, which means that it appears that it can be simultaneously true that the handle is pending in the enqueue task and not pending in the dequeue task, while the reverse is true of the queue.

**Comment by oerdnj** [comment]
> > What I mean is:
> 
> > if the handle isn't pending (i.e., it's the first uv_async_send call), then a memory barrier is issued
> 
> > if the handle is pending (second or later uv_async_send call), then a memory barrier won't help because the async_cb in the other thread can run in parallel with cds_wfcq_enqueue (or before, or after - indeterminate, basically)
> 
> The other option is that they have a data race here, so neither of those is true.

I am confused what the `cds_wfcq_enqueue()` has anything to do with `uv_async_send()`. Both operate on different member of the `struct isc_loop`.

> In particular, in the normal algorithm there, bind9 requires a seq_cst fence between the queue operations and the notify operation so that either of those is true.

What do you mean?

The wfcqueue enqueue operations issues:
1. seq_cst to xchg &tail->p (new_tail <-> old_tail)
2. release to store new_tail to &old_tail->next

The seq_cst is there, so the xchg doesn't get reordered after the store.

> In the wfcqueue implementation, it looks like bind9 tried to use weaker atomics, which means that it appears that it can be simultaneously true that the handle is pending in the enqueue task and not pending in the dequeue task, while the reverse is true of the queue.

Again, what do you mean?

The `___cds_wfcq_splice()` (called from `__cds_wfcq_splice_blocking()`) uses consume memory ordering. This matches well with both the seq_cst and the release ordering above.

> Your description assumes that they use seq_cst, but neither they nor libuv uses seq_cst.

That's because `seq_cst` is almost always wrong, mostly you want acq_rel ordering.

I am pretty sure that the wfcqueue implementation is correct.

**Comment by vtjnash** [comment]
> The wfcqueue enqueue operations issues:

You forgot the important one in the list. The enqueue operations that are being issued there are:

> 1. seq_cst to xchg &tail->p (new_tail <-> old_tail)
> 2. uv_async_send (relaxed load, can reorder with release)
> 3. release to store new_tail to &old_tail->next

> That's because seq_cst is almost always wrong, mostly you want acq_rel ordering.

seq_cst is the only ordering that prevents uv_async_send from getting reordered with the release store and potentially causing lost wakeups. It might be almost always wrong to choose, except in the case where your algorithm cares about seq_cst. It is also the only ordering that is always correct. Choosing acq_rel is generally nice, when you only have one field that matters, but as you pointed out, the async and queue are different fields.

**Comment by vtjnash** [comment]
Notably, I'd also like to fix this in the next libuv release of `uv_async_t`, so that bind9's usage does become fully correct. So the important question will be whether https://github.com/libuv/libuv/compare/v1.x...vtjnash:libuv:jn/async-seq-cst plus https://github.com/libuv/libuv/pull/4589 (reland) is safe for bind9 or if something else still is broken.

**Comment by oerdnj** [comment]
> It might be almost always wrong to choose, except in the case where your algorithm cares about seq_cst.

Yes, I absolutely agree with this. It is not wrong if it is a conscious choice.

**Comment by vtjnash** [comment]
Can you test https://github.com/libuv/libuv/pull/4589? I would like to re-land that commit now, if it seems the possible seq_cst bug in bind9 is now fixed in libuv by #5149.

**Comment by Mno-hime** [comment]
@vtjnash I'll test #4589 today and get back to you.

**Comment by Mno-hime** [comment]
@vtjnash It seems to be a problem on BIND 9 end. I created an MR with a possible fix.
