### ISSUE TITLE
 deleting handle in uv_async_t leads to memory corruption in nodejs Addon.

### ISSUE THREAD

**Issue by GayathriKaliyamoorthy** [libuv/libuv#465]
I am writing a nodejs addon, where I generate events for main v8 thread, from the worker threads.
 I use uv_async handles to generate events. At the end I invoke uv_close to close handles. The close callback to uv_close deletes the handle. I observe a memory corruption when I delete the handle. If I do not delete it's a leak in the system. What is the correct way to generate async events and close handles without any memory corruption. For reference the source code is available here, 
https://github.com/aerospike/aerospike-client-nodejs/blob/master/src/main/util/async.cc. 

Any suggestion would help me to a great extent.

Gayathri

**Comment by saghul** [comment]
The problem is that you are initializing the async handle from a work callback, here: https://github.com/aerospike/aerospike-client-nodejs/blob/80d423ff00dd7010a9038b754f386d777a0ed481/src/main/client/query_foreach.cc#L450 That is *not* thread-safe. The only thread-safe function is `uv_async_send`.

PS: for further questions please use our [mailing list](https://groups.google.com/forum/#!forum/libuv), we try to use the tracker just for issues, thanks!
