### ISSUE TITLE
test udp_mmsg fails occasionally on macOS

### ISSUE THREAD

**Issue by paparodeo** [libuv/libuv#4650]
* **Version**:  libuv-1.49.2
* **Platform**: Darwin bepaw 24.2.0 Darwin Kernel Version 24.2.0: Fri Dec  6 18:51:28 PST 2024; root:xnu-11215.61.5~2/RELEASE_ARM64_T8112 arm64 arm Darwin

https://cache.nixos.org/log/m3viwg0fsyjs729cpz9yx49nlqks7d9b-libuv-1.49.2.drv

```
not ok 323 - udp_mmsg
# exit code 6
# Output from process `udp_mmsg`:
# 43 allocs for 58 recvs
# Assertion failed in test/test-udp-mmsg.c on line 143: `alloc_cb_called == (40 / 20)` (43 == 2)
```

**Comment by bnoordhuis** [comment]
> 43 allocs for 58 recvs

That's supposed to read:

> 2 allocs for 40 recvs

My best guess is the test is picking up cross traffic from other tests or another process because otherwise there's no way the receive count is 58. The UDP tests all use port 9123.

**Comment by juanarbol** [comment]
I could work on a fix for this one. With some guidance

**Comment by bnoordhuis** [comment]
The tests all use `TEST_PORT`, defined in test/task.h. Maybe we should change that to something like:
```c
#define TEST_PORT (16384 + getpid()*65537 % 16384)
```
To make it semi-random but consistent inside the same process. I'm eliding Windows compatibility (no getpid) for brevity.

**Comment by juanarbol** [comment]
Still investigating, wireshark says sender is ok, always 40 but I found something.

I've added a couple logs for debugging this mess.

```
uv__udp_recvmsg: nread=8
uv__udp_recvmsg: nread=2
uv__udp_recvmsg: nread=2
uv__udp_recvmsg: nread=2
uv__udp_recvmsg: nread=2
uv__udp_recvmsg: nread=1
uv__udp_recvmsg: nread=2
uv__udp_recvmsg: nread=2
uv__udp_recvmsg: nread=-1
uv__udp_recvmsg: nread=6
uv__udp_recvmsg: nread=4
uv__udp_recvmsg: nread=2
uv__udp_recvmsg: nread=-1
uv__udp_recvmsg: nread=4
uv__udp_recvmsg: nread=2
uv__udp_recvmsg: nread=1
16 allocs for 42 recvs
```

The extra recvs seems to be due to the negative nreads. But I don't get why is reading "partially", getting rid of the two negative nreads, we sum 40, just as expected.

And this is a clean scenario

```
uv__udp_recvmsg: nread=20
uv__udp_recvmsg: nread=20
2 allocs for 40 recvs
```

This seems to be more a kqueue delivery behaviour (and possibly a wrong assumption in the test)?

I can work on a fix for this, depeding on whatever you prefer to change, either the kqueue logic or accomodate the test itself.

I'm open to follow any suggestions.

_Note a-side, I don't think this is a port problem, I've changed the port to something else, and ran the test standalone. Same behaviour

**Comment by juanarbol** [comment]
@santigimeno  made something similiar to accomodate the test here https://github.com/libuv/libuv/commit/2bc22c40eb68f3b38d1ae3ea68ef2f180cbe9fef. I'll try something like that as a first proposal.
