### ISSUE TITLE
uv_async documentation does not mention return values

### ISSUE THREAD

**Issue by jclulow** [libuv/libuv#576]
The [documentation](http://docs.libuv.org/en/v1.x/async.html) for the suite of `uv_async_t` functions does not appear to describe what the expected return values are for successful or failed operation.

**Comment by trevnorris** [comment]
On *nix it only returns `0` but `errno` may be set (not sure how you're supposed to know, or if you're supposed to care). It will also `abort()` on an unexpected error.

On win will return `-1` if the handle isn't `UV_ASYNC, then succeed or abort on unexpected error.

So there are some inconsistencies that may need to be addressed before it can be documented.

**Comment by saghul** [comment]
> On *nix it only returns 0 but errno may be set

We never set errno, we just return a negative error code. (which on Unix it matches -errno).

**Comment by saghul** [comment]
@jclulow In general, [these rules apply](http://docs.libuv.org/en/v1.x/errors.html), but I agree we could document this better.

**Comment by jclulow** [comment]
@saghul It should really be documented on the actual page for the function in question.  The manual page for the [getline(3C)][man_3C_getline] C library routine is a reasonable example of the kind of documentation that I think makes sense for a routine like this (and probably in general for a library like `libuv`).

Note that it has a reasonably precise prose `DESCRIPTION` of the functionality and usage of the routines (somewhat absent for `uv_async()`).  It also has a `RETURN VALUES` and an `ERRORS` section, describing the return value and possible `errno` values respectively.

[man_3C_getline]: http://illumos.org/man/3C/getline

**Comment by trevnorris** [comment]
@saghul Sorry, my bad. It doesn't set `errno`. Though it also doesn't return `-errno`. In `unix/async.c` shows that `uv_async_send()` will either succeed or abort. While from `win/async.c` it may also return `-1`.

**Comment by saghul** [comment]
> It should really be documented on the actual page for the function in question. 

I don't disagree. Alas, time is a limited resource and any help is appreciated. I assume you digged into the code since the documentation wasn't clear enough, the perfect chance to submit a documentation PR! :-)

> The manual page for the getline(3C) C library routine is a reasonable example of the kind of documentation that I think makes sense for a routine like this (and probably in general for a library like libuv).

We use Sphinx for the documentation, which can generate man pages too. Changing the layout is not planned, but if someone wants to take a stab at it I'm willing to give input. That said, some sections are better commented than others, ideally I'd like all  sections looking like [this one](http://docs.libuv.org/en/v1.x/udp.html#c.uv_udp_bind), but then again, time...
