### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [libuv/libuv#594]
Would you like to add more error handling for return values from functions like the following?
- [pthread_mutex_init](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "Initialise a mutex.") ⇒ [pthread_barrier_init](https://github.com/libuv/libuv/blob/764877fd9e4ea67c0cbe27bf81b2b294ed33b0f5/src/unix/pthread-fixes.c#L62)
- [strdup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string.") ⇒ [process_start](https://github.com/libuv/libuv/blob/764877fd9e4ea67c0cbe27bf81b2b294ed33b0f5/test/runner-unix.c#L120)

**Comment by bnoordhuis** [comment]
I think the Android fallback code works on the assumption that pthread_mutex_init and pthread_cond_init always succeed because under the hood they're futexes, i.e., simple ints.  If you have reason to believe that's an erroneous assumption, please file a pull request.

I'm mostly meh about checking that strdup() failing in the test runner.  Seems unimportant.

**Comment by bnoordhuis** [comment]
Oh, it's a bot.  How annoying.  Closing.
