### ISSUE TITLE
struct uv_buf_t defined differently under libuv/uv-win.h than libuv/uv-unix.h

### ISSUE THREAD

**Issue by supamii** [libuv/libuv#647]
Noticed that uv_buf_t is not defined consistently under libuv/uv-win.h and libuv/uv-unix.h

```C
/* uv-win.h */
typedef struct uv_buf_t {
  ULONG len;
  char* base;
} uv_buf_t;
```

```C
/* uv-unix.h */
typedef struct uv_buf_t {
  char* base;
  size_t len;
} uv_buf_t;
```

Is this intentional?  Causing issues for me with cross-platform development

**Comment by saghul** [comment]
This is intentional. On Unix we need to cast it to `struct iovec` and on Windows to `WSABUF` (see the definition [here](https://msdn.microsoft.com/en-us/library/windows/desktop/ms741542%28v=vs.85%29.aspx)).

Also see the comment [here](http://docs.libuv.org/en/v1.x/misc.html?highlight=uv_buf_init#c.uv_buf_init).

What problems are you running into exactly?

**Comment by supamii** [comment]
Ok thanks for the clarification.

I dealt with the issue by using `#ifdef _WIN32` and so forth because initializing the structs vary between systems so I assumed libuv would take the burden of handling it.

**Comment by saghul** [comment]
You can also use `uv_buf_init`.
