### ISSUE TITLE
Assertion failed in test/test-tcp-write-queue-order.c (write_cancelled_callbacks)

### ISSUE THREAD

**Issue by trankkilou** [libuv/libuv#764]
on Debian jessie, fresh install
/tmp/libuv-1.4.2# uname -a
Linux webtop1 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u2 (2016-01-02) x86_64 GNU/Linux
during the make check

[%  17|+  43|-   0|T   0|S   0]: tcp_write_queue_order
tcp_write_queue_order failed: exit code 6
Output from process tcp_write_queue_order:
Assertion failed in test/test-tcp-write-queue-order.c on line 129: write_cancelled_callbacks > 0
 
[% 100|+ 249|-   1|T   0|S   0]: Done.
FAIL: test/run-tests
 
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
 
Makefile:3835: recipe for target 'check-TESTS' failed
make[1]: *** [check-TESTS] Error 1
make[1]: Leaving directory '/tmp/libuv-1.4.2'
Makefile:4091: recipe for target 'check-am' failed
make: *** [check-am] Error 2

le line 129 of the tsts is

ASSERT(write_cancelled_callbacks > 0);

same pb with last version from git

EDIT: I update for the typo

**Comment by iWuzHere** [comment]
I'll try and take a look!

**Comment by txdv** [comment]
Next time, could you put the output log in between ```(three backticks), then the whole output would be formatted in the same manner.

The line that you are talking is here: https://github.com/libuv/libuv/blob/v1.x/test/test-tcp-write-queue-order.c#L129

In the test we are creating 1000 little writes to try to force queuing, however in your case it did not work.

I think the test would succeed in you case if you further increase the REQ_COUNT to lets say 100000.

Probably your write socket buffer size is higher than usual, could you post the output of the following command:

```
cat /proc/sys/net/ipv4/tcp_wmem
```

**Comment by trankkilou** [comment]
Hello,

you're right
cat /proc/sys/net/ipv4/tcp_wmem
30000000	30000000	30000000


this value is high as I am performing benchmark.
Actually my friend and collegue (blackbelt in system and C programming) found out the problem already.
You may  check this value instead of hardcoded one in your test ?

kr,

julien

**Comment by txdv** [comment]
```
You may check this value instead of hardcoded one in your test ?
```

I don't understand what you want to say...


On my simple machine I have:

```
4096    16384   903776
```

4kb minimum, 16kb maximum per socket and ~0.86MB total for all buffers.

Now your test machine has 28MB as minimum, maximum and total. I fear that the test will not succeed nevermind how much you increase the REQ_COUNT in the test. Maybe increasing the buffer size will help.

Either way, the test failure doesn't matter much. I have written the test and as far as I remember we just agreed to this value.

This can be closed unless we want to make this test pick something more dynamic according to uv_recv_buffer_size so it succeeds on machines with beefier socket size buffer settings as well.

**Comment by ferrieux** [comment]
Hello, I work with Julien.
We agree that our settings are a bit extreme. However, please imagine being in the end-user's seat in such a situation; by "end-user" I mean the average userland developer who may not be familiar with such global settings, or even not have root credentials. The error message, from his standpoint, is cryptic (knowing nothing of libuv, I spent 10 minutes to figure it out), and without understanding the  mechanism he cannot easily decide to ignore the negative test result...

Her's a constructive suggestion: instead of hard-coding REQ_COUNT, maybe it is possible to detect the writes that don't complete immediately (equivalent of an EWOULDBLOCK in synchronous nonblocking semantics) ?

**Comment by ferrieux** [comment]
Hello, I work with Julien.
We agree that our settings are a bit extreme. However, please imagine being in the end-user's seat in such a situation; by "end-user" I mean the average userland developer who may not be familiar with such global settings, or even not have root credentials. The error message, from his standpoint, is cryptic (knowing nothing of libuv, I spent 10 minutes to figure it out), and without understanding the  mechanism he cannot easily decide to ignore the negative test result...

Here's a constructive suggestion: instead of hard-coding REQ_COUNT, maybe it is possible to detect the writes that don't complete immediately (equivalent of an EWOULDBLOCK in synchronous nonblocking semantics) ?

-Alex

**Comment by ferrieux** [comment]
Hello, I work with Julien.
We agree that our settings are a bit extreme. However, please imagine being in the end-user's seat in such a situation; by "end-user" I mean the average userland developer who may not be familiar with such global settings, or even not have root credentials. The error message, from his standpoint, is cryptic (knowing nothing of libuv, I spent 10 minutes to figure it out), and without understanding the  mechanism he cannot easily decide to ignore the negative test result...

Here's a constructive suggestion: instead of hard-coding REQ_COUNT, maybe it is possible to detect the writes that don't complete immediately (equivalent of an EWOULDBLOCK in synchronous nonblocking semantics) ?

-Alex

**Comment by ferrieux** [comment]
Hello, I work with Julien.
We agree that our settings are a bit extreme. However, please imagine being in the end-user's seat in such a situation; by "end-user" I mean the average userland developer who may not be familiar with such global settings, or even not have root credentials. The error message, from his standpoint, is cryptic (knowing nothing of libuv, I spent 10 minutes to figure it out), and without understanding the  mechanism he cannot easily decide to ignore the negative test result...

Here's a constructive suggestion: instead of hard-coding REQ_COUNT, maybe it is possible to detect the writes that don't complete immediately (equivalent of an EWOULDBLOCK in synchronous nonblocking semantics) ?

-Alex

**Comment by ferrieux** [comment]
Hello, I work with Julien.
We agree that our settings are a bit extreme. However, please imagine being in the end-user's seat in such a situation; by "end-user" I mean the average userland developer who may not be familiar with such global settings, or even not have root credentials. The error message, from his standpoint, is cryptic (knowing nothing of libuv, I spent 10 minutes to figure it out), and without understanding the  mechanism he cannot easily decide to ignore the negative test result...

Here's a constructive suggestion: instead of hard-coding REQ_COUNT, maybe it is possible to detect the writes that don't complete immediately (equivalent of an EWOULDBLOCK in synchronous nonblocking semantics) ?

-Alex

**Comment by ferrieux** [comment]
Hello, I work with Julien.
We agree that our settings are a bit extreme. However, please imagine being in the end-user's seat in such a situation; by "end-user" I mean the average userland developer who may not be familiar with such global settings, or even not have root credentials. The error message, from his standpoint, is cryptic (knowing nothing of libuv, I spent 10 minutes to figure it out), and without understanding the  mechanism he cannot easily decide to ignore the negative test result...

Here's a constructive suggestion: instead of hard-coding REQ_COUNT, maybe it is possible to detect the writes that don't complete immediately (equivalent of an EWOULDBLOCK in synchronous nonblocking semantics) ?

-Alex

**Comment by trankkilou** [comment]
For info: increasing #define REQ_COUNT to 100000 was enough to successfully pass the test

**Comment by txdv** [comment]
> Her's a constructive suggestion: instead of hard-coding REQ_COUNT, maybe it is possible to detect the writes that don't complete immediately (equivalent of an EWOULDBLOCK in synchronous nonblocking semantics) ?

Nice suggestion, I think we can check the uv_write_buffer_size until it is > 0 or the counter increases to MAX_INT.

**Comment by txdv** [comment]
I have created a pull request which ups the maximum req_count to 100k, I don't want to do more, because it already requires like a 10mb memory block just to fit the requests. Maybe it doesn't really require that much until really referenced.

Anyway, this should fix this test for 10 years or so until we all having 16TB ram is considered to be normal.

**Comment by ferrieux** [comment]
Hum not sure about the 10 years: as you suspected the memory is not committed until used, and in some workloads (like ours) only a few sockets in the system will exercise that big depths. So the 10MB value is everything but the max... I like your suggestion of checking write_queue_size btw; that sounds more robust than bumping a constant ;-)

**Comment by txdv** [comment]
>  I like your suggestion of checking write_queue_size btw

I'm doing that already [here](https://github.com/libuv/libuv/pull/767/commits/ae61da075bc3f96701826bb2cb1671b619f4548c#diff-a25ed3c428dc2dafca964739478fdb7bR89), but I can't create an infinite sized block of requests [here](https://github.com/libuv/libuv/pull/767/commits/ae61da075bc3f96701826bb2cb1671b619f4548c#diff-a25ed3c428dc2dafca964739478fdb7bR44).

I can technically do something with malloc, but that would make the code more verbose and difficult. Maybe the other guys can chip in with some ideas.

Also, the 10MB are for holding the requests, not the actual amount of data we write to the socket. The test shouldn't fail until someone runs the test with socketbuffers set to 90MB

**Comment by ferrieux** [comment]
OK. But instead of wasting resources, what about forcing the tested socket buffer size to a known value ? Something like  uv_send_buffer_size(handle,16384) ...

**Comment by txdv** [comment]
lol, probably the best idea.
