### ISSUE TITLE
uv_loop_close() reports busy if idle is used

### ISSUE THREAD

**Issue by mhahn-sighthoundlabs** [libuv/libuv#765]
Looks like on the standard example

https://gist.github.com/mhahn-sighthoundlabs/dbf2e4036b170c8aaad8

uv_loop_close() always returns -16 ("busy"), not zero. There seems to be one IDLE handle left, with the flags set to 8192. Given the API to stop or clean things up respectively this problematic because one cannot tell whether there's something else pending.

Happens with release 1.8.0

**Comment by bnoordhuis** [comment]
Not a bug, IMO.  There's an active (that is, open) handle so uv_loop_close() is right to return UV_EBUSY.  If you close instead of stop the idle handle, uv_loop_close() should succeed.

The documentation could perhaps be more explicit that.  It currently says "This function must only be called once the loop has finished its execution or it will return UV_EBUSY."  I'll file a pull request for that.

**Comment by mhahn-sighthoundlabs** [comment]
But the loop exits or uv_run() returns respectively, because uv_idle_stop() got called, i.e. nothing should be active anymore closing should succeed. So how in this sample is someone supposed to bring the system into a state so that UV_BUSY is not returned? I don't see a solution given the current API - meaning if one uses idle closing won't work. Not so much of a drama for the default loop, but certainly for dynamically created custom loops.

**Comment by saghul** [comment]
You need to `uv_close` the idle handle. Otherwise the loop still has a reference to it.
