### ISSUE TITLE
win: what is the resolution of uv_timer

### ISSUE THREAD

**Issue by dkrikun** [libuv/libuv#770]
What is the resolution of `uv_timer` on windows?

**Comment by txdv** [comment]
You should ask questions in the mailing list or stackoverflow.

Also consider looking at the documentation first: http://docs.libuv.org/en/v1.x/timer.html

**Comment by dkrikun** [comment]
No problem.

Also, the docs lack that info, so maybe it could be added?

**Comment by txdv** [comment]
I don't understand what you mean:

> If timeout is zero, the callback fires on the next event loop iteration. If repeat is non-zero, the callback fires first after timeout milliseconds and then repeatedly after repeat **milliseconds**

> Set the repeat interval value in **milliseconds**. The timer will be scheduled to run on the given interval, regardless of the callback execution duration, and will follow normal timer semantics in the case of a time-slice overrun.

**Comment by dkrikun** [comment]
Will it fire exactly after timeout milliseconds, or it might happen e.g
after timeout+1 milliseconds?

**Comment by txdv** [comment]
> For example, if a 50ms repeating timer first runs for 17ms, it will be scheduled to run again 33ms later. If other tasks consume more than the 33ms following the first timer callback, then the callback will run as soon as possible.

Depends on how much stuff you do on your in your other callbacks.

If your loop has only timers(a reasonable amount) it will pretty much always be executed immediately. If you have some callbacks which take a long time to compute (lets say 50ms) and you want your timer to fire every 25ms, then the timer will only be called after the 50ms because the computation is blocking the event loop.

**Comment by dkrikun** [comment]
Thanks, that pretty much answers the question.
