### ISSUE TITLE
Issue & milestone for 2.0?

### ISSUE THREAD

**Issue by Fishrock123** [libuv/libuv#773]
afaik there will need to be a 2.0 release at some point (soon?) could we use a github milestone to track what needs to be done and then link it to an issue like this one?

cc @saghul / @cjihrig and refs: https://github.com/nodejs/node/pull/3594#issuecomment-199179828

**Comment by cjihrig** [comment]
I think @saghul could answer this better, but I'm under the impression that the next release will be 1.9. There is currently a `v2` label and a `v1.next` milestone. I'm unaware of how up to date and accurate they each are.

**Comment by saghul** [comment]
As Colin pointed out, there is no "official" plan for 2.0 as of yet. I (with my individual hat) had many things in mind for 2.0, but now I think that was a bit too ambitious and we'll have to make changes more gradually.

That said, the current state of affairs is as follows:
* v2 label: PRs which we cannot merge onto v1.x because they break the ABI. Since we haven't made master diverge they should still apply cleanly.
* v1.next milestone: Rough list of things pending for the next release in the v1.x series.

After v1.9 comes v1.10, I'd say. But it's probably also a good time to get back to those PRs and land them in master (after 1.9 goes out).

While we do follow semver, we have worked hard to keep ABI stability, so I'd rather not bump the major with every trivial change that would break it, so we group them.

My 2 cents!

PS: Hopefully we can have 1.9.0 soon, I'll try to work on the issue tracker the upcoming days, I've had a lot going on recently :-(

**Comment by jbergstroem** [comment]
Just curious: are there any plans to coincide libuv 2.0 with Node.js 6.0?

**Comment by txdv** [comment]
What were the initial features you wanted to put into libuv 2.0?

**Comment by saghul** [comment]
@jbergstroem nope.

**Comment by saghul** [comment]
@txdv kinda everything I wrote a LEP about :cry:

**Comment by txdv** [comment]
There is only one accepted lep - create sockets early - and it is already implemented.

Or am I missing something?

**Comment by saghul** [comment]
Yes, that was an easy one. I mean the pending ones.

**Comment by txdv** [comment]
You mean these: https://github.com/libuv/leps/pulls

**Comment by cjihrig** [comment]
I think this can be closed. Check the milestone and label for updates.
