### ISSUE TITLE
Hit assert() in uv__async_io()

### ISSUE THREAD

**Issue by kevin-xu** [libuv/libuv#78]
```
124 
125 static void uv__async_io(uv_loop_t* loop, uv__io_t* w, unsigned int events) {
126   struct uv__async* wa;
127   char buf[1024];
128   unsigned n;
129   ssize_t r;
130 
131   n = 0;
132   for (;;) {
133     r = read(w->fd, buf, sizeof(buf));
134 
135     if (r > 0)
136       n += r;
137 
138     if (r == sizeof(buf))
139       continue;
140 
141     if (r != -1)
142       break;
143 
144     if (errno == EAGAIN || errno == EWOULDBLOCK)
145       break;
146 
147     if (errno == EINTR)
148       continue;
149 
150     abort();
151   }
152 
153   wa = container_of(w, struct uv__async, io_watcher);
154 
155 #if defined(__linux__)
156   if (wa->wfd == -1) {
157     uint64_t val;
158     assert(n == sizeof(val));
159     memcpy(&val, buf, sizeof(val));  /* Avoid alignment issues. */
160     wa->cb(loop, wa, val);
161     return;
162   }
163 #endif
164 
165   wa->cb(loop, wa, n);
166 }
167 
```

Our project often hit `assert()` in line 158 because `read()` in line 133 sometimes returns -1.
I think this piece of code makes a mistake when dealing with `EAGAIN` or `EWOULDBLOCK`.

Help me.

**Comment by saghul** [comment]
Are you calling uv_run from a callback? The loop is not recursive, doing
that is not supported, anything could happen if you do that.

**Comment by kevin-xu** [comment]
Yes, I've called uv_run() to implement synchronous operations. You can refer to GLib & GTK, this usage of loop is common. In fact, it's a big advantage of loop.
I think libuv can do a little work to support this feature.

**Comment by saghul** [comment]
Well, that's not supported. This feature request has come a couple of times, but so far I personally have not heard of compelling reasons to go for it other than "framework X supports it". That doesn't mean we will never look at it, but I think it would be hard to implement with the current design.

Once we have this implemented https://github.com/libuv/leps/pull/3 if should be easier to revisit / accomplish.

I'm closing this issue now since it's not an issue but a misuse of the API, as it stands. Please feel free to open a feature request or send an email to the mailing list about this, I'd be interested in knowing (in detail) why this would be useful.

**Comment by moteus** [comment]
>This feature request has come a couple of times, but so far I personally have not heard of compelling reasons to go for it other than "framework X supports it".

For example to support poll zmq socket we need recv all messages ([Edge triggered notification](http://funcptr.net/2012/09/10/zeromq---edge-triggered-notification)) 
Pseudocode to uv_poll callback
```
while <socket has message> do
  <socket recv message>
  <proceed message>
end
```
But if there many messages there no way to get a chance to other callbacks.

**Comment by bnoordhuis** [comment]
> so far I personally have not heard of compelling reasons to go for it other than "framework X supports it"

See joyent/libuv#758 for an example.  Event loop reentrancy would allow libuv to work with Chicken Scheme because calls into Scheme land never return, everything is rewritten to CPS.

It's a rather uncommon use case and I eventually made it work by collecting events on a separate thread but that's neither pretty or straightforward.

A counter-argument to reentrancy is that it could make some operations inefficient because you can never assume that a callback returns or that a callback returns before other operations take place.

@kevin-xu If you want to see this happen, https://github.com/libuv/leps is the best place to make your case for it.

**Comment by saghul** [comment]
I'm not sure how a reentrant loop would help in that case, but as Ben
pointed out the leps project is the right place to design and discuss it.
