### ISSUE TITLE
Expose uv_translate_sys_error?

### ISSUE THREAD

**Issue by glasser** [libuv/libuv#79]
It would be nice if it were possible for user code which runs posix syscalls to return `uv_err_t`.  However, that's not the case, because `uv_translate_sys_error`, despite its singly-underscored name, is not exposed publicly.  (This also makes it difficult to translate the error into a string like 'ENOENT'; you can use `strerror` but that just provides the long English string.)

I realize that the function is Unix-specific and would require some sort of Windows stub (or for users to `#ifdef _WIN32`, but it still seems useful.

**Comment by mscdex** [comment]
+100 I'd also like to see something exposed for this.

My use case is that I have a third party library that I wrap and it can set the process-level error number. So in v0.10 what I was doing was `uv_strerror(uv_last_error(uv_default_loop()))` to get a cross-platform description of the error that occurred.

However `uv_last_error()` is gone in v1.x, so I have to `#ifdef` to check platform and call `uv_strerror(-errno)` on *nix. But on Windows what do I do? I can't do `uv_strerror(GetLastError())` as far as I know.

**Comment by mscdex** [comment]
> I'm confused. That doesn't work like you expect. uv_last_error just fetched the last error stored in the loop, but if you have third party code which sets errno the function is completely unaware of it.

I wasn't even aware of this. :-\

> It's still unclear to me why you want an UV_ error code if you are running your own third-party C code, which may or may not be platform independent. Can you please clarify? Maybe a reduced example would help a bit.

The reason I'd want it is to use with `uv_strerror()` so I can get a cross-platform textual description of what went wrong. For example, I have a node addon that wraps libmagic. libmagic sets its own error string most of the time, but there are some times when it only sets `errno` and returns NULL from whatever function that failed (e.g. passing in bad library flags resulting in `errno = EINVAL`).

**Comment by saghul** [comment]
@mscdex I see. In that case we'd need something like what @piscisaureus proposed here: https://github.com/libuv/libuv/issues/79#issuecomment-68108984

Usecase might be narrow, but I won't opoose a PR :-)

**Comment by mscdex** [comment]
+100 to `uv_translate_posix_error()` and `uv_translate_win32_error()` as per Bert's suggestion.

**Comment by mnunberg** [comment]
I too have the same issue. I'd be happy to have this function exposed. Alternately the actual codes themselves could simply be defined to retain their meaning on Windows as well as Unix. My library uses libuv as an I/O implementation (thus the library uses its own I/O abstraction) and communicates status using the error codes defined on a given platform.

Previously we would do (for 0.x versions):

```c
  static int uvc_uv2syserr(int status) {
      #define X(errnum,errname,errdesc) \
        if (status == UV_##errname) { return errname; }
      UV_ERRNO_MAP(X);
      #undef X
      return 0;
  }
```

The error codes were few, and those that didn't exist were simply defined elsewhere, i.e.

```
#ifndef UNKNOWN
#define UNKNOWN -1
#endif
```
(to allow `UV_UNKNOWN` to function).

However with 1.x new error codes are constantly being added; many of them missing on one platform or another, and it's becoming a bit of a drag after fixing a build on one platform, to see it break on another.

**Comment by cjihrig** [comment]
@mscdex is this still a thing you'd like to have?

**Comment by mscdex** [comment]
Sure.

**Comment by ZyX-I** [comment]
I used `uv_translate_sys_error` because libuv lacks `read()`/`write()` and `readv()`/`writev()` syscall wrappers (or they are not listed in documentation). I am not using existing `uv_fs_read`/`uv_fs_write` because they require seek support and they require me to track position in the file what I have no reasons to do (kernel *already* tracks it). If there were these wrappers I would not need `uv_translate_sys_error`.

Note: I sometimes do `readv(fd, {small_buffer, huge_buffer}, 2)` just to reduce a number of syscalls (https://github.com/neovim/neovim/blob/67062d20ede952f0658f2418867adce381a69c64/src/nvim/os/fileio.c#L219). It would be rather inefficient to use `readv` like this if libuv will emulate `readv` on top of `read` in one way (two `read()` calls) or the other (`malloc`, `read()`*1, `memcpy`*2, `free`).

**Comment by ZyX-I** [comment]
To be more clear: `uv_translate_sys_error` was needed because I am mixing libc and libuv syscall wrappers. Current convention for the module where these wrappers are wrapped by Neovim code is “return libuv errors”, so alternatives to translating error codes are

1. Break convention and allow some functions to return system errors. Not acceptable because this will definitely lead to confusion (easy to mistake which `strerror` implementation to use in which case).
2. Return some kind of tagged errors. E.g. `struct {int errno; bool is_uv_error;}` or some bit manipulations. “Some bit manipulations” look acceptable, but are actually dangerous as neither libuv nor OS do not guarantee that they are not going to use some bits in error code, `struct{}` would require too much refactoring. And why bother if there is `uv_translate_sys_error` which looks like a public function?

**Comment by saghul** [comment]
@ZyX-I https://github.com/libuv/libuv/issues/79#issuecomment-69339518 PRs are welcome :-)

**Comment by plafer** [comment]
I'll implement the `read()/write()` and `readv()/writev()` wrappers on the unix side!

What names would we use here, considering we're already using `uv_fs_read()` and `uv_fs_write()` for `preadv()` and `pwritev()`?

**Comment by saghul** [comment]
Hi Philippe,

Is this related to the `uv_read` proposal? I think it's too early on to ge contributions on it until we have the first bits inplace. Bert will write those and if no further issues are identified we'll come up with a plan for the next steps.

I understand this can be a bit frustrating, but as someone who already worked in a `uv_read` implementation, we need to lay on some groundwork so we can take it to the finish line this time around. Stick around!

PS: Or did I get it all wrong? How is this related to what this specific issue is about?

**Comment by plafer** [comment]
My apologies, I misinterpreted what the "good first contribution" was about - I was indeed talking about the `uv_read` proposal. However, I'm just as ready to give a shot at the `uv_translate_posix_error()` and `uv_translate_win32_error()`. I'll start working on a PR right away!

**Comment by saghul** [comment]
Excellent, thanks! Sorry if something was unclear.
