### ISSUE TITLE
`fs_event_close_in_callback` fails on SmartOS

### ISSUE THREAD

**Issue by santigimeno** [libuv/libuv#808]
This test is always timing out:
```
`fs_event_close_in_callback` failed: timeout
Output from process `fs_event_close_in_callback`: (no output)
=============================================================
```
I think that the reason might be that the functionality this test is checking is not supported by `port events`  for the same reason it is not supported by `kqueue`
```
/* kqueue doesn't register fs events if you don't have an active watcher.
 * The file descriptor needs to be part of the kqueue set of interest and
 * that's not the case until we actually enter the event loop.
 */
```
It would be great if someone could confirm (or not) this.

**Comment by saghul** [comment]
@libuv/sunos any chance you can look at this? It's the only failing test atm.

**Comment by misterdjules** [comment]
@saghul Yes, it's on my list of things to look at. Is this blocking anything?

**Comment by cjihrig** [comment]
@misterdjules I don't think it's blocking anything, just wouldn't have to manually inspect the CI results.

**Comment by saghul** [comment]
@misterdjules Nope, but since it's now the only failing test I thought I'd call in the cavalry :-)

**Comment by misterdjules** [comment]
Sounds good, I'll take a look tomorrow at the latest, and I'll keep you posted! Thanks for the heads up once again 👍

**Comment by misterdjules** [comment]
That test is timing out on SmartOS because event ports do not support watching for changes in files within directory by just watching the directory, and not the files.

It could be made to work on SmartOS by adding files into the directory `watch_dir` instead of writing to existing files.

However, I don't think i understand the purpose of the `fs_event_close_in_callback` test: it seems that other tests (even some that were written before it) close a `uv_fs_event_t` handle in their callback, so it seems that use cases is already tested in other tests that do not have this problem.

**Comment by bnoordhuis** [comment]
It checks that no more callbacks are made after the handle is closed.  Also, it's an explicit test for a particular behavior, and as we all know, explicit > implicit.

**Comment by misterdjules** [comment]
> It checks that no more callbacks are made after the handle is closed.

I had missed that it closes the `uv_fs_event_t` handle after a smaller number of events than the number of files changed, thanks for the clarification. The test definitely makes sense to me now that I know what I was missing. I'll submit a PR to fix the test asap.

**Comment by misterdjules** [comment]
Created #1011 that I believe fixes that issue.
