### ISSUE TITLE
timers: improve performance proposal

### ISSUE THREAD

**Issue by yjhjstz** [libuv/libuv#809]
Right now, libuv implement `timers` use tree-based algorithm.

why don't try hash time wheeler algorithm[1], like the linux kernel do[2].

[1].http://www.cs.columbia.edu/~nahum/w6998/papers/sosp87-timing-wheels.pdf
[2]. http://lwn.net/Articles/156329/

**Comment by saghul** [comment]
Feel free to give it a try! Then we'll need some numbers to see which one we pick :-)

**Comment by yjhjstz** [comment]
I'd like to try.

**Comment by Fishrock123** [comment]
I took a look at the current timers algo, and it quite efficient.

I find the first article you linked to rather dated. I've read though the entire paper before for node's higher-level impl. I suggest you also do some reading of [my extensive comments in node's timers impl](https://github.com/nodejs/node/blob/master/lib/timers.js#L14-L85) for reference, although I'm not entirely sure the same thing world be viable at this level.

--

I'll read though this entire linux thread sometime soon, but here's some thing I picked up on:

> average per-timer expiry overhead is still O(1)! But expiry worst-case 
is not bounded, it is O(N).

Hmmm, I wonder what worst-cases look like perf-wise in practice compared to fast cases of this sort of impl.

> But there's a hidden win as well from this approach: if a timer is 
removed before it expires, we've saved the remaining cascading steps!  
This happens surprisingly often: on a busy networked server, the 
majority of the timers never expire, and are removed before they have to 
be cascaded even once.

> in other words: we 'lazy sort' timers, and we push most of the sorting 
overhead as much into the future as possible, in the hope of the problem 
of having to sort them going away, because they get removed before they 
expire. (and even if we wanted, we couldnt sort earlier in this model, 
due to the RAM footprint limits)

These may be true, but I'm still not sure they are the best assumptions.

--

On the plus side, there's probably code able to be copied directly form linux core, depending on licensing, I suppose.

**Comment by yjhjstz** [comment]
yes, I have done this mostly, reference to the linux core. @Fishrock123 
code: https://github.com/yjhjstz/libuv/tree/v1.x-time-wheel

benchmark result is below:
before: 
```shell
➜  libuv git:(v1.x)  out/Release/run-benchmarks million_timers
10.60 seconds total
2.15 seconds init
7.86 seconds dispatch
0.58 seconds cleanup
```
after:
```shell
 libuv git:(v1.x) ✗ out/Release/run-benchmarks million_timers
10.36 seconds total
1.12 seconds init
8.88 seconds dispatch
0.36 seconds cleanup
```

And I add a benchmark to test just start million timer and stop them just before timeout. Also see in the branch https://github.com/yjhjstz/libuv/tree/v1.x-time-wheel

before: 
```shell
➜  libuv git:(v1.x) ✗ out/Release/run-benchmarks million_timers_cancel
9.92 seconds total
9.38 seconds start/stop
0.00 seconds run
0.54 seconds cleanup
```
after:
```shell
➜  libuv git:(v1.x-time-wheel) ✗ out/Release/run-benchmarks million_timers_cancel
1.39 seconds total
0.95 seconds start/stop
0.00 seconds run
0.45 seconds cleanup
```
 This case is very suitable for TCP applications[1].

But one question is that,  `int uv__next_timeout(const uv_loop_t* loop)`, I wonder how to achieve it exactly. I want help. 

[1]. http://www.ibm.com/developerworks/aix/library/au-lowertime/?ca=dgr-lnxw06tcptimer&S_TACT=105AGX59&S_CMP=GR

**Comment by Fishrock123** [comment]
I'd prefer if we tried to make the benchmark at least somewhat realistic.

For the benchmark you just made, can you make sure you are timing out one in every, say, 5k timers? Also make sure you are not using continuously larger timeouts. Testing with a couple set timeout durations (say, 50, 180, 340 ms), and also random 1-1k ms timeouts would be appreciated.

Please keep in mind that this implementation also backs all of node's timers, so we can't *only* think about tcp. :)

**Comment by yjhjstz** [comment]
Sure, but first, I must solve how to implement `uv__next_timeout` precise or in a smart way, can you help?

**Comment by yjhjstz** [comment]
https://github.com/yjhjstz/libuv/tree/v1.x-time-wheel almost complete except window platform.
```shell
commit fdaa872f82316d75d78320b82aa61105a46c7e2b
Author: jianghua.yjh <jianghua.yjh@alibaba-inc.om>
Date:   Mon Apr 11 15:32:18 2016 +0800

    pass make check

commit 4e530709cfd43573a440a4d644a87cd513216470
Author: jianghua.yjh <jianghua.yjh@alibaba-inc.om>
Date:   Mon Apr 11 11:19:46 2016 +0800

    remove warnings

commit 02cc4bbfab0ca8b6dd41b07e90dab2dfc01ab00d
Author: jianghua.yjh <jianghua.yjh@alibaba-inc.om>
Date:   Mon Apr 11 10:53:04 2016 +0800

    add benchmark, just start and stop immediatly

commit e09c77b5d48aa72158e195047012fb0a95df86e3
Author: jianghua.yjh <jianghua.yjh@alibaba-inc.om>
Date:   Fri Apr 8 16:28:10 2016 +0800

    wheel timer
```
Can @saghul @Fishrock123 give some advice or help improve that.

**Comment by bnoordhuis** [comment]
@yjhjstz It's probably easiest if you open a pull request with your work so far.  Perhaps you can add a benchmark that stresses the timer wheel's worst case?

> But one question is that, int uv__next_timeout(const uv_loop_t* loop), I wonder how to achieve it exactly.

I'm afraid I don't understand what your question is.

**Comment by yjhjstz** [comment]
Thx @bnoordhuis , I will add worst case and send a PR then.

**Comment by saghul** [comment]
Closing in favor of #823, let's continue the discussion there.
