### ISSUE TITLE
uv_poll_init() doesn't work for kqueue fds

### ISSUE THREAD

**Issue by vavrusa** [libuv/libuv#883]
Versions affected: since 1.2.2 (reproduced on 1.9.0)
Platform: BSDs and OS X

## Problem

`uv_poll_init()` enforces that socket is set to non-blocking mode, but ioctl is N/A for kqueue pollfd so it returns an error. This blocks nesting/embedding other event loops or polling mechanisms in libuv where kqueue is used.

## Steps to reproduce

1. Create a `kq = kqueue()` pollfd
2. Create `uv_poll_t` and call int `uv_poll_init(loop, &some_cb, kq)`
3. Get` ENOTTY (Inappropriate ioctl for device)`

**Comment by bnoordhuis** [comment]
While we can fix that in libuv (and we probably should), I don't think it would help you much. You can't usefully nest kqueue file descriptors (on OS X anyway) because the nested fd is immediately reported as readable, regardless of whether there are actual events available.  It's not like epoll, where events bubble up.

It's possible Apple fixed that in the most recent XNU release but a quick look at `bsd/kern/kern_event.c` suggests they haven't.

**Comment by vavrusa** [comment]
It'd help me a lot. It is indeed reported as readable and that's fine as the nested loop finds out there are no events and yields. Next wakeup happens when there are actual events on the kqueue. Right now I had to hack it a little bit, as in - I have to open the uv_poll_t on a throwaway file descriptor and then switch it with the kqueue before `uv_poll_start(...)`, but that requires fiddling with `uv_poll_t` internals. I don't feel great about it, but it works for now.

**Comment by saghul** [comment]
@bnoordhuis I guess we could ignore the error here: https://github.com/libuv/libuv/blob/v1.x/src/unix/poll.c#L62 kind-of setting the fd non-blocking best-effort.

**Comment by vavrusa** [comment]
Neat, thank you!
