### ISSUE TITLE
fix compile error in vs2015

### ISSUE THREAD

**Issue by sailfish009** [libuv/libuv#988]
i rechecked the case, it is bug.
link the libs does not help.
https://github.com/libuv/libuv/pull/987

uv-win.h

#if _MSC_VER >= 1900
#undef stdin
#undef stdout
#undef stderr
_CRTIMP extern FILE _iob[];
#define stdin   _iob
#define stdout  (_iob+1)
#define stderr  (_iob+2)
#endif

**Comment by saghul** [comment]
You really need to give us more information here. It all boils down to: can you compile libuv iteself with the provided vcbuild.bat file? Can you run the tests? If the answer to those is "yes" then the problem lies in **your** application, and the right place to ask questions would be the mailing list. At any rate, I can't help you without more information.

**Comment by sailfish009** [comment]
the answer is yes, but problem exist in libuv.
i don't need help, above fix works for me.
